새로운 여행 생성 페이지 구현
woowacourse-teams/2023-hang-log pull request #100
Opened 2023-07-19 09:00 UTC by Dahyeeee

## 📄 Summary
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/79e1f1be-6f69-4438-9ca0-d9f6cc5cfc70)
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/77ff66ab-49cd-4991-b6eb-1798d1c104c4)
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/bab16a9a-eebb-4c9e-a9ca-24913f067496)

트립생성 페이지 마크업 +기능 완료했습니다
post기능 useNewTripMutation으로 만들었는데 잘 쓰고 있는지 한 번 봐주십시오~~

## 🙋🏻 More
>

close #75

2023-07-19 13:58 UTC, ashleysyheo requested changes
헤다 짱짱 💯🔥👍

진짜 수고했어요!!!!!!!!!!!

질문들과 코멘트 남겨봤습니다 😊

<br>

지금 달력 클릭했을 때 아이콘을 클릭해야만 달력이 열리는 상황이 발생하고 있어요! 사용자가 당연하게 인풋 창도 클릭 할 수 있다고 생각할 것 같아요. 지금 input에 `disabled`를 걸었던데 readonly로 만들고 input을 클릭해도 열릴 수 있게 하는 것은 어떻게 생각하세요?

<br>

그리고 가운데 정렬해주세요!!!! 😭
![Group 2636](https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/adcc9434-dec2-4b12-9f87-0925122bd927)

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
> +  height: '77.6px',
`77.6px` 뭐죠....?????? container의 height는 `48px`이어야 하는데요??

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
> +  overflowX: 'auto',
👍

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +
`useEffect`를 이용해서 `cityData`를 업데이트 하는 이유가 있나요?

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/common/DateInput/DateInput.style.ts
> +      '> *:nth-of-type(odd)': {
👍

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/common/DateInput/DateInput.style.ts
> +        border: `1px solid ${Theme.color.gray100}`,
border 없애주세요

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/common/DateInput/DateInput.style.ts
>  export const calendarStyling = css({
calendar에도 켜졌을 때 boxShadow 추가해 주세요!

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/common/DateInput/DateInput.tsx
> +  useEffect(() => {
여기서도 useEffect에서 업데이트하는 이유가 있나요? useEffect로 인해 사이드 이펙트가 생길 수도 있지 않을까요?

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +  const moveToTripEditPageWithId = (id: string) => {
moveTo 보다는 goTo ...? 어떻게 생각하세요...!

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +      <Button variant="primary" disabled={!isAllInputFilled} style={{ width: '400px' }}>
style을 사용하면 css 가 inline으로 박히지 않나요? 저희 emotion을 사용하는 만큼 inline css를 사용해요!
```suggestion
      <Button variant="primary" disabled={!isAllInputFilled} css={{ width: '400px' }}>
```

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/hooks/api/useCityQuery.ts
> +    cacheTime: Infinity,
cacheTime: Infinity를 설정한 이유가 있나요?

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/hooks/api/useCityQuery.ts
>    });
suspense, errorboundary 안 사용하는 것인가요?? (이거 혹시 제가 주석처리했던건가요.....????)

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/hooks/api/useNewTripMutation.ts
> +import { NewTripData } from '@type/trips';
타입 온리 임포트!

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/hooks/api/useNewTripMutation.ts
> +    async (newTripData: NewTripData) => postNewTrip(newTripData),
async는 필요없지 않나요??

postNewTrip을 이렇게 작성하면 위에 코드를 더 간단하게 적을 수 있어요.

```js
export const postNewTrip = () => async (newTripData: NewTripData) => {
  const response = await axiosInstance.post(END_POINTS.TRIPS, newTripData);

  return response.headers.location;
};
```

```
export const useNewTripMutation = () => {
  const newTripMutation = useMutation(postNewTrip(), {
    onError: (err, _, context) => {
      //toast 띄우기
      alert('오류가 발생했습니다. 잠시 후 다시 시도해주세요.');
    },
    retry: NETWORK.RETRY_COUNT,
  });

  return newTripMutation;
};
```

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/api/trips/trips.ts
> +export const postNewTrip = async (newTripData: NewTripData) => {
파일 분리해 주세요!!

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/hooks/common/useCitySuggestion.ts
> +  const cityData = useQueryClient().getQueryData<CityData[]>(['city']);
바로 `useQueryClient().getQueryData...` 처럼 적는 것 보다 아래처럼 적는 것이 더 깔끔한 것 같아요


```suggestion
const queryClient = useQueryClient();
const cityData = queryClient.getQueryData<CityData[]>(['city']);
```

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/hooks/newTrip/useNewTripForm.ts
> +  }, [newTripData]);
useEffect에서 validateInputs를 하는 이유가 있나요?? `setCityData`나 `setDateData`에서 하는 것도 가능하지 않나요??

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/pages/TripCreatePage/TripCreatePage.style.ts
> +  top: '150px',
무엇을 위한 150px? 중앙 정렬 해주세요!!

2023-07-19 13:58 UTC, ashleysyheo commented on frontend/src/pages/TripCreatePage/TripCreatePage.tsx
> +  useCityQuery();
`useCityQuery`는 비동기 데이터를 가지고 오는데, suspense 처리해야하지 않을까요?

2023-07-20 01:13 UTC, Dahyeeee commented on frontend/src/types/trips.ts
> +export interface NewTripData {
이거 백엔드에 보내는 데이터인데 이것도 저는 해당한다고 생각했는데! 백엔드랑 소통하는 데이터는 정부 Data...

2023-07-20 01:14 UTC, Dahyeeee commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +
`cityTags` 추가할때, 삭제할때 변동되는 데 그때마다 `setCityData`하는 것보다 useEffect 써서 코드 한줄만 작성하는 게 좋겠다고 생각햇어요!

2023-07-20 01:15 UTC, Dahyeeee commented on frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
> +  height: '77.6px',
ㅋㅋㅋㅋㅋㅋ되돌려놨습니다.

2023-07-20 01:32 UTC, Dahyeeee commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +      <Button variant="primary" disabled={!isAllInputFilled} style={{ width: '400px' }}>
애슐리 코드 보고 form쪽에서 ` > button`으로 주는 걸로 바꿨어요~~

2023-07-20 01:33 UTC, Dahyeeee commented on frontend/src/hooks/api/useCityQuery.ts
> +    cacheTime: Infinity,
일정시간 마다 불러오는 게 아니라 앱이 첫가동될 때 한번만 불러오기로 했었어요! 
새로운 여행 추가할 때도 쓰고, 나중에 수정할때도 저장된 데이터에서 가져와서 쓰면 될 것같아서요~

2023-07-20 01:33 UTC, Dahyeeee commented on frontend/src/hooks/api/useCityQuery.ts
>    });
ㅋㅋㅋㅋ네 풀어놓을게용

2023-07-20 01:43 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
> +  height: '77.6px',
달력 인풋 높이도 48px이어야 하지 않나요??

2023-07-20 01:44 UTC, ashleysyheo commented on frontend/src/pages/TripCreatePage/TripCreatePage.style.ts
> +  backgroundColor: Theme.color.white,
background color 지워주세요!

2023-07-20 01:47 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +
그럼 submit을 할 때 가장 최신 데이터를 서버에 보낸다는 보장이 되나요? 뭔가 타이밍 문제가 있을 수 있을 것 같아요!

2023-07-20 01:48 UTC, ashleysyheo commented on frontend/src/types/trips.ts
> +export interface NewTripData {
흠..... 🤔 그럼 저도 FormType이 아니라 FormData라고 해야 하는 것인가요???

조금 헷갈리네요

2023-07-20 01:52 UTC, Dahyeeee commented on frontend/src/pages/TripCreatePage/TripCreatePage.style.ts
> +  backgroundColor: Theme.color.white,
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/6c2a2e1a-2dea-49da-b577-1351206a4d01)
지우면 이렇게 겹치는 데 이게 의도한 바가 맞나요?

2023-07-20 01:52 UTC, dladncks1217 requested changes
고생 많으셨습니다 헤다👏👏👏
아주 예쁘게 잘 동작하더군요!
리뷰 확인 한번 부탁드릴게요!

그나저나 코드 읽다가 발견한 게 있는데, 이번 pr에는 file changes에 없어서 여기에 남깁니다 ㅎㅎ

`useCityTags.ts` 파일에 보면
`const hasCityTag = prevCityTags.map((tags) => tags.id).includes(selectedCity.id);` 코드 부분이 있습니다!
filter로 한 번만 순회해도 될 것 같은데, 뭔가 불필요하게 map으로 한번, includes로 또 한번 돌며 데이터를 순회할 것 같다는 생각이 들더라구요.
혹시 map과 includes를 조합해 사용한 이유가 있나요?!

2023-07-20 01:52 UTC, dladncks1217 commented on frontend/src/hooks/api/useCityQuery.ts
> +    cacheTime: Infinity,
저도 궁금합니다!

2023-07-20 01:52 UTC, dladncks1217 commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
async로 사용한 이유가 있나요?!

2023-07-20 01:52 UTC, dladncks1217 commented on frontend/src/hooks/newTrip/useNewTripForm.ts
> +import { CityData } from '@type/city';
type import 해주세요!

2023-07-20 01:52 UTC, dladncks1217 commented on frontend/src/hooks/newTrip/useNewTripForm.ts
> +import { DateRangeData, NewTripData } from '@type/trips';
여기도 type import 해주세요!

2023-07-20 01:52 UTC, dladncks1217 commented on frontend/src/components/common/DateInput/DateInput.tsx
>  import { DateRangeData } from '@type/trips';
여기도 type import 빠졌습니다!

2023-07-20 02:14 UTC, Dahyeeee commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +    navigate(PATH.EDIT_TRIP.replace(':tripId', id));
오오오 좋네요!! 좋은 제안 감사합니당

2023-07-20 02:15 UTC, Dahyeeee commented on frontend/src/hooks/api/useNewTripMutation.ts
> +      onError: (err, _, context) => {
모르겠네여 ㅋㅋㅋㅋㅋ 애슐리코드배껴온거라~~~ 양심고백~~~

2023-07-20 02:16 UTC, Dahyeeee commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
서버에서 id를 받아와야해서 붙여줬는데 필요없군요. 리액트 쿼리 짱...

2023-07-20 02:19 UTC, Dahyeeee commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +  const moveToTripEditPageWithId = (id: string) => {
굳

2023-07-20 02:20 UTC, Dahyeeee commented on frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
> +  height: '77.6px',
그러네욤 지웠어요!

2023-07-20 02:25 UTC, Dahyeeee commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +
이해가 잘 안되요 tag가 변경될때마다 새로운 tag로 데이터를 설정해주는데 최신데이터 보장이 안된다는 게 뭘까용..?

2023-07-20 02:25 UTC, Dahyeeee commented on frontend/src/hooks/newTrip/useNewTripForm.ts
> +  }, [newTripData]);
이것도 중복코드 삭제차원에서 해준건데 useEffect 제가 잘 모르는 건가요..? 어떤 사이드 이펙트가 일어나죠 ㅠㅠ?

2023-07-20 02:29 UTC, Dahyeeee commented on frontend/src/pages/TripCreatePage/TripCreatePage.tsx
> +  useCityQuery();
가져오기는 page에서 가져오는데 사용하는 건 `CitySuggestion`인데 전체적으로 suspense fallback처리해주기가 좀 부담스러운 측면이 있군요..! 
쪼금 더 고민해봐도 될까용

2023-07-20 02:31 UTC, Dahyeeee commented on frontend/src/hooks/api/useNewTripMutation.ts
> +      onError: (err, _, context) => {
`useCityTags` filter로 바꿨습니다~ 코드짤때 filter생각이 아니났나봐용 ㅎㅎㅎ

2023-07-20 07:00 UTC, dladncks1217 approved these changes

2023-07-20 07:03 UTC, ashleysyheo commented on frontend/src/pages/TripCreatePage/TripCreatePage.tsx
> +  useCityQuery();
그런데 city suggestion 데이터 로딩 여부가 이 페이지에서는 중요한 데이터니까 suspense로 감싸주는 것이 맞는 것 같아요.

2023-07-20 07:04 UTC, ashleysyheo approved these changes

2023-07-20 07:08 UTC, merged