ErrorBoundary 컴포넌트 구현
woowacourse-teams/2023-hang-log pull request #122
Opened 2023-07-21 08:41 UTC by ashleysyheo

## 📄 Summary
get 요청에 대한 에러를 처리하기 위해 ErrorBoundary 컴포넌트를 구현한다.

- [x] axios 에러 핸들링 로직 추가
- [x] Error 컴포넌트 구현 (fallback)
- [x] ErrorBoundary 컴포넌트 구현

<br>

close #68 

## 🙋🏻 More
>

2023-07-21 11:29 UTC, dladncks1217 requested changes
고생 많으셨어요 애슐리!💯💯
이번주 정말 고생 많으셨습니다👏👏

리뷰 몇 개 남겼는데, 시간 괜찮으실 때 확인 한 번 부탁드릴게요! 
다음주에 뵈어요~!

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +
```
useEffect(() => {
    if (errorState.error && onReset) {
      onReset(errorState.error);
    }
  }, [errorState.error, onReset]);
```
함수형으로 바꾼다면 이 코드도 추가하면 좋을 것 같아요!

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +  static getDerivedStateFromError(error: Error): State {
```suggestion
 const catchError = (error: Error) => {
    setError(error);
  };
```
이런 느낌으로 구현하고 밑에서 this.props.children 대신 fallback container 만들어서 거기에 넣어주는건 어떤가요!

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +  state: State = initialState;
```suggestion
const [errorState, setErrorState] = useState(initialState);
```
함수형으로 변경한다면 위와 같이 수정할 수 있을 것 같아요!

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/utils/typeGuard.ts
> +}
타입가드 👍💯💯💯

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +    return this.props.children;
```suggestion
interface FallbackContainerProps {
  catchError: (error: Error) => void;
  children: React.ReactNode;
}

const FallbackContainer: React.FC<FallbackContainerProps> = ({ catchError, children }) => {
  try {
    return <>{children}</>;
  } catch (error) {
    catchError(error);
    return null; 
  }
};
```

이렇게요!

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/components/common/Error/Error.tsx
> +import ErrorImage from '@assets/svg/error-image.svg';
svg 아주 이쁜데요??
역시 애슐리👍

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/api/axiosInstance.ts
> +import { HTTPError } from './HTTPError';
```suggestion
import { HTTPError } from '@api/HTTPError';
```
절대 경로가 지정되지 않았어요!

2023-07-21 11:29 UTC, dladncks1217 commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +import type { ErrorProps } from '../Error/Error';
```suggestion
import type { ErrorProps } from '@components/common/Error/Error';
```
절대경로가 적용되지 않았어요!

2023-07-21 11:33 UTC, ashleysyheo commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +class ErrorBoundary extends Component<PropsWithChildren<ErrorBoundaryProps>, State> {
ErrorBoundary는 클래스 컴포넌트로 구현해야 해요! `getDerivedStateFromError` 이거 사용하려고요

2023-07-21 11:33 UTC, ashleysyheo commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +  };
class 컴포넌트를 사용해야 해서 useState의 setter 함수는 사용하지 못할 것 같아요

2023-07-21 11:34 UTC, ashleysyheo commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +
이 또한 클래스 컴포넌트를 사용해야 해서요............

2023-07-21 11:35 UTC, ashleysyheo commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +class ErrorBoundary extends Component<PropsWithChildren<ErrorBoundaryProps>, State> {
> A class component becomes an error boundary if it defines either (or both) of the lifecycle methods [static getDerivedStateFromError()](https://legacy.reactjs.org/docs/react-component.html#static-getderivedstatefromerror) or [componentDidCatch()](https://legacy.reactjs.org/docs/react-component.html#componentdidcatch). Use static getDerivedStateFromError() to render a fallback UI after an error has been thrown. Use componentDidCatch() to log error information.

2023-07-21 11:39 UTC, ashleysyheo commented
@dladncks1217 슬링키 코멘트랑 제안 감사합니다! 그런데 에러 바운더리를 구현하기 위해서는 클래스 컴포넌트를 사용해야 해요... 🥲

리액트 훅에는 `static getDerivedStateFromError()`나 `componentDidCatch()` 같은 메서드가 없어서 클래스 컴포넌트를 사용해야되는 것 같아요!

2023-07-21 11:49 UTC, dladncks1217 approved these changes
https://legacy.reactjs.org/docs/error-boundaries.html
그러게요 이런게 있었군요 ㅋㅋㅋㅋ
고생하셨습니다 애슐리!💯💯

2023-07-21 11:49 UTC, dladncks1217 commented on frontend/src/components/common/ErrorBoundary/ErrorBoundary.tsx
> +class ErrorBoundary extends Component<PropsWithChildren<ErrorBoundaryProps>, State> {
헉 그런 이유가 있었군요..!

2023-07-22 00:53 UTC, Dahyeeee approved these changes
늦게해서 죄송합니당~~
에러바운더리 멋있어용 짷짱 고마워요 애슐리!

2023-07-22 00:53 UTC, Dahyeeee commented on frontend/src/hooks/common/useResetError.ts
> +      } else {
else문 if문  ealry return 하고 바깥쪽에서 navigate 해도 될듯?!
바로 직전함수 그렇게 썼으니 통일해도 좋을것같아용

2023-07-22 07:09 UTC, merged