여행 정보(이름, 날짜, 도시, 설명, 대표사진) 수정 모달 구현
woowacourse-teams/2023-hang-log pull request #132
Opened 2023-07-25 04:14 UTC by Dahyeeee

## 📄 Summary
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/76fc8457-a397-49fd-a8ef-0a267893f8b7)
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/e9861ea0-337a-4a12-80f2-de5e74e327bf)

## 🙋🏻 More
변한 파일이 많아보이나 이름변경한 것들이 있으니 그것들은 가볍게 넘기셔도 됩니당.

로직이 복잡해보이신다면... 맞습니다.ㅎㅎㅎㅎ
질문환영~~~

close #69

2023-07-25 05:00 UTC, ashleysyheo requested changes
헤다 수고했습니다! 🔥

리뷰 확인 부탁드려요!!!! 😊

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/types/trip.ts
> +export interface TripPutData extends Omit<TripData, 'cities' | 'id' | 'dayLogs'> {
TripPutData라는 네이밍 말고 TripFormData는 어떤가요? 사용하는 측에서 이게 더 명시적일 것 같아요!

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +          <SupportingText css={cityInputErrorTextStyling}>
SupportingText에 isError를 true로 넘기면 따로 스타일링 할 필요없어요

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +          ⚠︎ 방문 기간을 단축하면 마지막 날짜부터 작성한 기록들이 <br />
경고 아이콘은 이걸로 변경해 주세요! 피그마 prototype - sprint3에 있습니다. size는 line-height랑 비슷하게 하면 될 것 같아요.

 그리고 `<br />` 없애주세요!

<img width="326" alt="Screenshot 2023-07-25 at 1 37 04 PM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/82e62938-4f99-4bab-8c4a-eb03b6e0ad1a">

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +  const handleChangeValue = (key: keyof TripPutData) => (e: ChangeEvent<HTMLInputElement>) => {
이건 useTripInfoForm에 있어도 되지 않을까요?

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +        <Button variant="primary" type="submit">
Button의 type은 디폴트로 submit이어서 안 추가해도 돼요!

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +          <SupportingText css={cityInputErrorTextStyling}>
그리고 에러는 blur될 때 보다 submit할 때 검증하는 것에 대해서는 어떻게 생각하세요? TripItemAddModal이랑 통일하면 좋을 것 같아요

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +          imageAltText="여행 대표 이미지 업로드"
이미지는 업로드 된 이미지니까 `여행 대표 이미지` 아니면 `여행 대표 업로드 이미지`가 더 어울리지 않나요??

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +  Flex,
Flex 안 사용하고 있습니다

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +import type { ChangeEvent, FormEvent } from 'react';
FormEvent도 안 사용하고 있습니다.

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/api/useEditTripMutation.ts
> +    onError: (err, _, context) => {
안 사용하는 `(err, _, context)`는 삭제해 주세요

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/api/useNewTripMutation.ts
> +import { postNewTrip } from '@/api/trips/postNewTrip';
경로 재확인해주세요

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +  const { id: tripId, title, cities, startDate, endDate, description, imageUrl } = information;
이렇게 구조분해 할당을 한 이유가 있나요?

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +const TripAddForm = () => {
TripCreateForm은 어떠세요? 뭔가 더하는 것 보다는 새로 만드는 것이니까요? 그리고 파일명이랑 폴더명은 아직도 `NewTripForm`입니다.

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/mocks/handlers/trips.ts
> +    return res(ctx.status(202));
status code 204인 것 같은데요?? 명세 한 번만 더 확인해주세요!

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +        <Input
여행 설명은 Textarea 사용해주세요! 

![Frame 2692](https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/33cbd1e7-9913-43a8-ae25-fedb51206e7b)

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +          <SupportingText css={cityInputErrorTextStyling}>
<img width="426" alt="Screenshot 2023-07-25 at 1 51 28 PM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/053e49b1-d7ae-47e6-b6c3-64a65c291932">

input 창이랑 supportingText 사이 간격은 4px이어야 해요.

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +      <form onSubmit={handleSubmit} css={formStyling}>
form은 `nonvalidate`를 추가한 다음에 필수 입력 값들은 제출할 때 에러 검증을 한 다음에 저희 에러 스타일에 맞게 처리해 주세요!

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/api/useEditTripMutation.ts
> +export const useEditTripMutation = () => {
useTripEditMutation 어떠세요?

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/api/useEditTripMutation.ts
> +  const tripMutation = useMutation(putTrip(), {
tripMutation이라는 네이밍 보다 tripEditMutation아니면 editTripMutation으로 하는 것이 더 명시적일 것 같아요

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +    setTripInfo((prevTripInfo) => {
여기 useEffect안에서 setTripInfo를 하는 이유가 있나요?

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +    const cityLength = cityDateInfo.cityIds.length;
변수에 할당할 필요가 있나요? 그냥 밑에서 이렇게 해도 되지 않나요??

```js
if (cityDateInfo.cityIds.length > 0) {
  setCityInputError(false);

  return;
}
```

<br>

그리고 `return`위에 개행 추가해 주세요!

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +    if (isCityInputError) {
one line....

2023-07-25 05:00 UTC, ashleysyheo commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +    onClose();
이건 success 했을 때만 실행되어야 하지 않을까요?

2023-07-25 05:09 UTC, ashleysyheo commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +          <SupportingText css={cityInputErrorTextStyling}>
<img width="426" alt="Screenshot 2023-07-25 at 2 08 36 PM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/6a2ac263-51c7-4fd2-a5b7-2ddaddf16ec0">

여기도 마찬가지입니다.

2023-07-25 05:56 UTC, dladncks1217 requested changes
고생 많으셨어요 헤다~! 💯💯💯
그런데 버그를 하나 발견했어요!
뱃지의 x말고 몸통 부분을 누르면 아래와 같이 되어버립니다...🥲
이거랑 코멘트 확인 한번만 부탁드릴게요!👍

<img width="234" alt="스크린샷 2023-07-25 오후 2 08 08" src="https://github.com/woowacourse-teams/2023-hang-log/assets/45068522/842bc07a-e697-439f-adde-b091994a40ec">

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +import { useCityDateForm } from '@/hooks/common/useCityDateForm';
절대경로 확인해주세요!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +import { useTripInfoForm } from '@/hooks/trip/useTripInfoForm';
절대경로 확인해주세요!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/api/trip/putTrip.ts
> +import { TripPutData } from '@type/trip';
type import 해주세요!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
>    return (
지금 확인한건데, 이 윗부분 CityTags 부분에 대한 리뷰입니다!
```
 const CityTags = () => {
    return cityTags.map((cityTag) => (
      <Badge key={cityTag.id} css={badgeStyling}>
        {cityTag.name}
        <CloseIcon
          aria-label="삭제 아이콘"
          css={closeIconStyling}
          onClick={handleDeleteButtonClick(cityTag)}
        />
      </Badge>
    ));
  };
```
이 컴포넌트를 memo로 묶을 수 있을 것 같아요!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/components/newTrip/NewTripForm/NewTripForm.tsx
> +const TripAddForm = () => {
좋습니다 👍👍

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/hooks/api/useNewTripMutation.ts
>      onError: (err, _, context) => {
`(err, _, context)`는 안쓰이니 지워도 될 것 같아요!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/hooks/api/useNewTripMutation.ts
>      onError: (err, _, context) => {
그리고 이 밑에 `// toast 띄우기` 주석이 있는데,
TODO: 형태로 바꿔주세요!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/hooks/common/useCityDateForm.ts
> +  };
컴포넌트가 리렌더링되어도 같은 콜백함수를 쓸 수 있도록 useCallback을 써주는건 어떨까요?!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/hooks/common/useCityDateForm.ts
> +  };
이 부분들도 위 코멘트와 동일하게 useCallback을 써주는건 어떨까요?!

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +    if (isCityInputError) {
근데 진짜 헷갈리긴 해요 ㅋㅋㅋㅋㅋ
코드짜다보면 자주 실수하는...

2023-07-25 05:56 UTC, dladncks1217 commented on frontend/src/mocks/handlers/trips.ts
> +    return res(ctx.status(202));
일단 204로 고치고 이 status도 HTTP Status에 따라 상수화하는건 어떤가요?

2023-07-26 08:00 UTC, Dahyeeee commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +          <SupportingText css={cityInputErrorTextStyling}>
제출했을 때 validate하도록 수정했습니다! 디자인도 수정했어용

2023-07-26 08:05 UTC, Dahyeeee commented on frontend/src/components/trip/TripInfoEditModal/TripInfoEditModal.tsx
> +  const handleChangeValue = (key: keyof TripPutData) => (e: ChangeEvent<HTMLInputElement>) => {
ㅇㅇ 옮겼어여!

2023-07-26 08:05 UTC, Dahyeeee commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +  const { id: tripId, title, cities, startDate, endDate, description, imageUrl } = information;
쓸데 간편하게 쓰려고?! 저는 좀 값이 많은 객체는 구조분해 할당하는 걸 좋아합니당...

2023-07-26 08:06 UTC, Dahyeeee commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +    setTripInfo((prevTripInfo) => {
`cityDateInfo` 는 다른 hook에서 다루고 있어서 변경될때마다 `tripInfo`에 추가해줘야해서요!

2023-07-26 08:07 UTC, Dahyeeee commented on frontend/src/hooks/common/useCityDateForm.ts
> +  };
그 우리 만든 훅이 많고 그 안에 굉장히 많은 메소드가 있는데 언제 useCallback을 쓰고 언제 안쓸지 잘 모르겠어요! 혹시 슬링키만의 기준이 있나용..?

2023-07-27 01:26 UTC, dladncks1217 approved these changes
고생 많으셨습니다 헤다🔥🔥🔥

2023-07-27 01:53 UTC, ashleysyheo commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +  const { id: tripId, title, cities, startDate, endDate, description, imageUrl } = information;
위에서 구조분해 할당을 안 하고 밑에서 한 이유가 궁금했어요!

2023-07-27 01:55 UTC, Dahyeeee commented on frontend/src/hooks/trip/useTripInfoForm.ts
> +  const { id: tripId, title, cities, startDate, endDate, description, imageUrl } = information;
아 그러게요! props에서 하도록 바꿨어요!

2023-07-27 02:03 UTC, ashleysyheo reviewed
수고했습니다! 소소하게 스타일 수정 관련해서 밑에 코멘트 남겼습니다. 확인 부탁드려요!!!

<img width="423" alt="Screenshot 2023-07-27 at 10 57 34 AM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/95c75fe5-7277-4522-8132-84ca09c40695">

너비 맞춰주세요!

<img width="420" alt="Screenshot 2023-07-27 at 10 59 12 AM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/4c1a904a-abf2-4b76-941e-be9d220a4fc9">

그리고 `기록들이`랑 `삭제됩니다` 사이 `<br />` 삭제해주세요.

<img width="405" alt="Screenshot 2023-07-27 at 11 01 10 AM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/e347179e-e96b-4b22-af04-7db23d96e95a">

검색 결과 없다는 메세지에도 padding-left, right 16px로 맞춰주세요!

<img width="415" alt="Screenshot 2023-07-27 at 11 01 55 AM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/acec41e9-43a9-4f6d-9e61-e6a433d877b0">

textarea resize도 막아주세요!

2023-07-27 02:37 UTC, Dahyeeee commented
디자인 수정했어요!
다만 `기록들이 삭제됩니다`는 <br/> 없으면 `삭` 다음으로 줄바꿈이 되는데 저는 `삭제됩니다`가 붙어있는게 더 읽기 좋은 것 같아요. 줄바꿈을 하지 말아야할 이유가 있을까요?

2023-07-27 04:34 UTC, ashleysyheo commented
나중에 모바일에서 화면이 줄어드면 어떻게 될지 모르니까요? 지금 당장은 보기 좋을 수 있어도 모든 상황에서는 대응할 수 없으니까 그냥 `<br>`을 없애는 것이 더 좋을 것 같아요.

2023-07-27 04:38 UTC, Dahyeeee commented
반응형, 모바일 대응 나중에 진행하기로 한 것 같은데 지금은 일단 이게 보기 좋고 width가 줄어들지 않으니까 그때 같이 수정하도록 하시죠~~

2023-07-27 05:34 UTC, ashleysyheo commented
<img width="465" alt="Screenshot 2023-07-27 at 2 32 18 PM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/d2ac4cde-90f4-4cc8-88d0-a0d80fc7f5f4">

그런데 제 컴퓨터에서는 `<br>`을 없애도 전부 다 들어와요. 이런 비슷한 상황들이 있을 수 있으니까 `<br>`을 그냥 없애는 것을 제안한거에요! 그리고 지금 width가 448px이어서 반응형 대응을 하면 무조건 화면 너비가 줄어들 것 같아요.

2023-07-27 05:48 UTC, Dahyeeee commented
브라우저마다 좀 다르게 보이나보네요! 알겠습니당

2023-07-27 06:06 UTC, ashleysyheo approved these changes

2023-07-27 06:12 UTC, merged