검색어 관련 제안 목록 보여주는 기능 debounce 적용
woowacourse-teams/2023-hang-log pull request #134
Opened 2023-07-25 04:59 UTC by Dahyeeee

## 📄 Summary
연속타이핑할때 제안창 깜박거리지 않게 debounce 적용했습니다! 

## 🙋🏻 More
>

close #120

2023-07-25 05:02 UTC, ashleysyheo requested changes
수고했습니다!!

2023-07-25 05:02 UTC, ashleysyheo commented on frontend/src/hooks/common/useDebounce.ts
> +function useDebounce<T>(value: T, delay?: number): T {
화살표 함수!!!!!!

2023-07-25 05:02 UTC, ashleysyheo commented on frontend/src/hooks/common/useDebounce.ts
> +    const timer = setTimeout(() => setDebouncedValue(value), delay || 500);
delay 기본 값은 위에서 설정해줘도 되지 않을까요?

2023-07-25 06:59 UTC, dladncks1217 requested changes

2023-07-25 06:59 UTC, dladncks1217 commented on frontend/src/hooks/common/useDebounce.ts
> +function useDebounce<T>(value: T, delay?: number): T {
arrow! arrow! arrow!

2023-07-26 01:22 UTC, dladncks1217 approved these changes

2023-07-26 02:04 UTC, merged