Feature/#135 expense
woowacourse-teams/2023-hang-log pull request #161
Opened 2023-07-27 07:33 UTC by waterricecake

## 📄 Summary
>#135

경비 조회 기능 구현

## 🙋🏻 More
> restDocs

2023-07-27 08:41 UTC, hgo641 reviewed
달리고생고생하셨습니다~

2023-07-27 08:41 UTC, hgo641 commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/Expense-controller-test/get-expenses/response-fields.adoc[]
대문자 안되지않나요?

2023-07-27 08:41 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/Currency.java
> +    }
stream 줄띄우기!

2023-07-27 08:41 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/Currencies.java
> +    private long id;
Long어떠신가요

2023-07-27 08:41 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +                .orElse(DEFAULT_CURRENCIES);
기본 currencies 반환 안하게 TODO!

2023-07-27 08:41 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +            final Map<Category, Integer> categoryIntegerMap
dayLogIntegerMap, categoryIntegerMap
좀 더 의미가 드러나는 이름은 없을까요?

2023-07-27 08:41 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +    private <T> void add(final Map<T, Integer> map, final T key, final int value) {
add보다 더 자세히 쓰는 건 어떨까요??

2023-07-27 09:27 UTC, waterricecake commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/Expense-controller-test/get-expenses/response-fields.adoc[]
되드라고요

2023-07-27 11:27 UTC, jjongwa requested changes
하나 둘 셋
파이링

2023-07-27 13:16 UTC, LJW25 requested changes
네이밍 점검 필요..
구조가 복잡하니까 이름도 복잡해지네요

RestDocs에서 빠진게 있어서 requestChange 했습니다.
다른것들은 자잘한 컨벤션 수정사항들인데 참고해주세요.
수고하셨습니당

2023-07-27 13:16 UTC, LJW25 commented on backend/src/main/java/hanglog/expense/presentation/ExpenseController.java
> +    }
여기도 id는 Long 타입으로 통일 부탁드립니다

2023-07-27 13:16 UTC, LJW25 commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +    public ExpenseGetResponse getAllExpenses(final long tripId) {
Long 22
놓칠까봐 달아놓음요

2023-07-27 13:16 UTC, LJW25 commented on backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
> +                                responseFields(
RestDocs 적용 👍👍

위에도 남겼지만 테스트에도 pathPatamter 추가해주세요~~
```suggestion
                        restDocs.document(
                                pathParameters(
                                        parameterWithName("tripId")
                                                .description("여행 ID")
                                ),
                                responseFields(
```

2023-07-27 13:16 UTC, LJW25 commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +        when(tripRepository.findById(1L))
알수없는 공백

2023-07-27 13:16 UTC, LJW25 commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +        when(tripRepository.findById(1L))
여기도 알수없는 공백

2023-07-28 03:22 UTC, mcodnjs requested changes
파이팅파이팅파이팅

2023-07-28 03:22 UTC, mcodnjs commented on backend/src/test/java/hanglog/expense/fixture/CurrenciesFixture.java
> +public class CurrenciesFixture {
네이밍 ~~

2023-07-28 03:22 UTC, mcodnjs commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +                        TripExpenseResponse.of(LONDON_TRIP,
```suggestion
                        TripExpenseResponse.of(
                                LONDON_TRIP,
```

2023-07-28 03:22 UTC, mcodnjs commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +                            TripExpenseResponse.of(LONDON_TO_JAPAN,
```suggestion
                            TripExpenseResponse.of(
                                    LONDON_TO_JAPAN,
```

2023-07-28 03:22 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +                .toList();
관련 도메인을 만드는건 어떠신지 ? ?

2023-07-29 05:31 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +    }
static .. ? 그리고 사용되는 메소드 아래 위치되면 좋을거 같아요 ~

2023-07-29 16:58 UTC, jjongwa commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/Expense-controller-test/get-expenses/response-fields.adoc[]
으어어어어어어아아어어으으

2023-07-29 17:53 UTC, jjongwa requested changes
롤로노아 김동연 Let's go

2023-07-29 17:53 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
> +    ) {
여기는 한 줄에 놔도 길이 제한 안넘어갈 것 같은데요?!
```suggestion
    public CategoryExpense(final Category category, final int amount, final int totalAmount) {
```

저희 컨벤션
- 매개변수 4개부터 세로로 작성
- 단, 매개변수 3개여도 가로 라인(120)을 넘으면 세로로 작성

2023-07-29 17:53 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +    }
changeToKRW 메서드와 calculateTotalAmount의 반환 타입이 다른 이유가 있나요? (진짜 궁금해서 그럼)

2023-07-29 17:53 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +        return (int) (expense.getAmount() * rate);
```suggestion
        return Double.valueOf(expense.getAmount() * rate).intValue();
```

요런 식으로도 가능할 것 같아요! 
다른 로직에서도 타입 캐스팅을 하는게 있던데 달리가 보고 괜찮으면 일관성있게 변경해 주세용

2023-07-29 17:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +                    .usingRecursiveFieldByFieldElementComparator()
89번 라인은 줄바꿈 안하고 116라인은 하셨네요..!
115라인에서 acutal.getCategories()에 .이 하나 있어서 .. ?

2023-07-29 17:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +                            contains(item);
여기도요! 129번 라인이랑 150번 라인

2023-07-29 17:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +                            contains(item);
적당히 하십쇼 형님

2023-07-29 17:53 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
>  package hanglog.trip.fixture;
달리가 한건 아니지만 expense fixture쪽으로 이동해 주시면 감사하겠습니다

2023-07-29 17:53 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/CityControllerTest.java
> +                List.of(CityResponse.withCountry(PARIS), CityResponse.withCountry(LONDON)));
```suggestion
when(cityService.getAllCities()).thenReturn(
                List.of(CityResponse.withCountry(PARIS), CityResponse.withCountry(LONDON))
        );
```

2023-07-31 06:41 UTC, LJW25 approved these changes
넘 수고하셨습니다 달리!
도메인쪽 처음 넘어오신데다 규모가 큰 도메인이다 보니 리팩토링 요청이 상당히 많았는데 주말동안 고생하셨어요 😂
처음보다 훨씬 이해하기 편해진것 같아요 👍

디노가 남겨주신 타입 캐스팅에 저도 동의해서, 이부분 한번 확인해주시면 감사하겠습니다.
화이팅~~~

2023-07-31 06:41 UTC, LJW25 commented on backend/src/main/java/hanglog/expense/dto/response/ItemDetailResponse.java
> +    private final Long id;
한칸 띄워주시면 감사하겠습니당~

2023-07-31 06:41 UTC, LJW25 commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/Expense-controller-test/get-expenses/response-fields.adoc[]
기왕이면 소문자로 통일해주시면 모든 docs가 통일되어 더 예쁘지 않을까 하는 사소한 건의 한번 해봅니다 🫠

2023-08-01 01:15 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/dto/response/ItemDetailResponse.java
> +    private final Long id;
@waterricecake
[code: 코드 컨벤션 적용](https://github.com/woowacourse-teams/2023-hang-log/pull/161/commits/89522eaa5915a12a4e888ab955902abca3555823)

2023-08-01 01:23 UTC, jjongwa approved these changes

2023-08-01 02:20 UTC, mcodnjs requested changes
마지막일지도 ?

2023-08-01 02:20 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/dto/response/CurrencyRateResponse.java
> +    }
이거 .. 정팩메 .. 인데 .. 해당 객체의 list를 반환한다 .. ? 

디노: 적당히 하십쇼 형님

2023-08-01 02:20 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/dto/response/TripExpenseResponse.java
> +            final List<TripCity> cities,
여기도 tripCities .. ㅎ

2023-08-01 02:20 UTC, mcodnjs commented on backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
> +        final TripExpenseResponse tripExpenseResponse = TripExpenseResponse.of(LONDON_TO_JAPAN,
찾았다

2023-08-01 02:20 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
> +                    TripFixture.LONDON_TRIP),
ㅎㅎ 개행

2023-08-01 02:28 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
> +                    TripFixture.LONDON_TRIP),
[refactor: cities 변수명 변경](https://github.com/woowacourse-teams/2023-hang-log/pull/161/commits/63dfd99256f8cba5523fc4679b67fc268d6da524)

2023-08-01 02:28 UTC, waterricecake commented on backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
> +        final TripExpenseResponse tripExpenseResponse = TripExpenseResponse.of(LONDON_TO_JAPAN,
[refactor: cities 변수명 변경](https://github.com/woowacourse-teams/2023-hang-log/pull/161/commits/63dfd99256f8cba5523fc4679b67fc268d6da524)

2023-08-01 02:28 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/dto/response/TripExpenseResponse.java
> +            final List<TripCity> cities,
[refactor: cities 변수명 변경](https://github.com/woowacourse-teams/2023-hang-log/pull/161/commits/63dfd99256f8cba5523fc4679b67fc268d6da524)

2023-08-01 02:29 UTC, mcodnjs approved these changes

2023-08-01 02:30 UTC, merged