Trip API 리팩토링
woowacourse-teams/2023-hang-log pull request #163
Opened 2023-07-27 10:22 UTC by mcodnjs

## 📄 Summary
> #136 

## 🙋🏻 More
> 나 이제 진짜 Trip 끝나나 ?????????? 

> 나 한거

 Trip 전체 조회, 단일 조회 API에 cities 필드 추가
 Trip 전체 조회 API에서 DayLog 리스트 제외
 Trip 단일 여행 수정 API imageUrl 추가

2023-07-27 10:44 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        saveTripCities(cities, trip);
이거 Trip 수정할 때 City 업데이트하는건데 .. 
Trip이 List<City> 가지고 있으면 영속성 전이 ~~ 할 수 있는데 ~~ 
일단은 이렇게 해봤는데 의견 부탁드려요 ..  ~~

2023-07-27 12:06 UTC, LJW25 requested changes
끝나지 않는 Trip,, 수정사항이 많은데 고생하셨습니다 라온

2023-07-27 12:06 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +    private final List<City> CITIES = List.of(PARIS, LONDON);
이거 대문자인데 상수인가요? static이 없어서 물어봄

2023-07-27 17:06 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/presentation/TripController.java
>      }
아아아 ..

2023-07-27 17:06 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +    }
그렇네요 좋아요좋아요

2023-07-27 17:06 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +    private final List<City> CITIES = List.of(PARIS, LONDON);
아차차 static을 깜빡 ~

2023-07-27 17:06 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +                .toList();
머가 좋을지 몰라서 .. 분리 했는데 .. 좀 더 가독성이 높아졌나 .. ?

2023-07-27 17:09 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +                .toList();
[refactor: 메소드 분리 및 네이밍 수정](https://github.com/woowacourse-teams/2023-hang-log/pull/163/commits/102f24bebd29744c37d8ff35d916d92b8a9cd3ab)

2023-07-28 00:54 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +        );
변수는 봐줘야죠~~

2023-07-28 00:58 UTC, LJW25 approved these changes

2023-07-28 01:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/TripController.java
>      }
진짜 무섭다 무서워 ..

2023-07-28 01:53 UTC, jjongwa approved these changes
Good

2023-07-28 01:53 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/Trip.java
>      private String description;
good ..

2023-07-28 01:53 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/dto/response/CityWithPositionResponse.java
> +        return new CityWithPositionResponse(
23이랑 24 사이에 한 칸 띄워주면 조금 더 이쁠것 같은 느낌이 드는데 그냥 의견입니다

2023-07-28 01:53 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        saveTripCities(cities, trip);
Trip이 TripCity를 리스트로 가지고 있으면 좋곘어요 
이것도 그냥 제 의견 ..

2023-07-28 01:53 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        saveTripCities(cities, trip);
아니면 TripCity를 가져와서 비교 후 없는거만 추가/삭제 하는 방법은 어떤가요?

2023-07-28 02:45 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        saveTripCities(cities, trip);
저도 경비 페이지 조회할때 똑같이 `TripCity`를 가져와야 하는데 `TripService`와 `ExpenseService` 두 곳에서 `TripCityRepository`를 주입받는 것보다 양방향 관계를 통해 `trip`이 `tripcity`를 가지고 있는 것이 좋을 것 같다고 생각합니다.

2023-07-28 02:48 UTC, waterricecake approved these changes

2023-07-31 08:02 UTC, merged