이미지 업로드 기능 구현
woowacourse-teams/2023-hang-log pull request #193
Opened 2023-07-31 08:43 UTC by LJW25

## 📄 Summary
> #145 
> 이미지 업로드 기능 완료
> 아이템 생성 및 수정 시 이미지 할당 로직 수정

## 🙋🏻 More
 
### 이미지 업로드
- 이미지 MultiPartFile로 업로드 요청 -> 정해진 디렉토리(/home/ubuntu/hang-log-images)에 저장
- 디렉토리에 저장 되는 이름은 원래 이름+시간으로 해싱한 값

2023-07-31 12:28 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +
이 부분 이해가 조금 어려울 것 같아서 코멘트 남깁니다! 이해가 되시면 넘어가도 괜찮아유



현재 아이템 수정 request에서, `List<String> imageUrls`가 넘어오고 있습니다. 이 `imageUrls`들을 가지고 아이템의 필드인 `List<Image> images`를 새로 세팅해줘야합니다. `(updatedItem.images = updatedImages)`



우선 `getUpdatedImages` 메소드는 요청받은  `imageUrls`를 `Image`객체 리스트로 만들어 반환하는 메소드입니다. 이 때, `imageUrls`의 종류에 따라 `Image`객체를  가져오는 방법이 달라집니다.

`imageUrls`의 종류는 다음과 같이 두 가지가 있습니다.

1. 원래부터 아이템에 등록돼 있었던 이미지.
2. 아이템에 새로 추가된 이미지.



때문에 `updatedImages`를 생성할 때, 

원래부터 아이템에 등록된 이미지(1번)라면 해당 아이템 객체의 `images`를 순회하며 요청받은 `imageUrl`을 가지는 이미지 객체를 찾아와 할당하고,

새로 등록된 이미지(2번)라면 새로운 이미지 객체를 생성해서 할당해주어야합니다.

이 부분이 바로 `getUpdatedImage`메소드의 return 부분입니다.

```java
return originalImages.stream() // 아이템의 기존 이미지들을 순회한다
                .filter(originalImage -> originalImage.getImageName().equals(imageName)) // 요청으로 들어온 image가 아이템의 기존 이미지였는지 확인한다.
                .findAny()
                .orElseGet(() -> new Image(imageName)); // 아이템의 기존 이미지라면 스트림을 통해 찾은 이미지를 반환하고, 기존 이미지가 아니라면 새로운 이미지 객체를 생성한다.
```



정리하면, `getUpdatedImage` 메소드는  request에서 받은 `imageUrl`을 가지는 객체가 이미 아이템의 이미지로 존재한다면 해당 이미지 객체를 반환하고, 아이템의 이미지로 존재하지 않는다면 새로운 이미지 객체를 생성해서 반환하는 메소드입니다.

2023-07-31 12:28 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +
`getUpdatedImage`라는 메소드의 이름만 보고 내부 로직을 파악하기 어려울 것 같아 다른 이름을 사용하고 싶은데, 마땅한 이름이 생각나지 않았습니다ㅠㅠ

메소드를 분리하는 것도 조금 애매하더군요... 좋은 의견이 있으시다면 코멘트 부탁드립니다...

2023-07-31 14:11 UTC, LJW25 commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    IMAGE_PATH_INVALID(5100, "이미지를 저장할 경로가 올바르지 않습니다.");
+ 후보로 volume도 생각했긴 하지만 실제 설정 시 
```
      max-file-size: 10MB
      max-request-size: 101MB
```
와 같은 파라미터를 사용하기 때문에 size로 뒀습니다 🫠

2023-07-31 16:30 UTC, jjongwa requested changes
이오 홍고 생고생 하셨습니다.

itemService부터는 집중력이 떨어져서 코멘트가 부실합니다.. 내일 마저 달겠습니당

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
> +
로거 달았는데 .?!

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +    }
```suggestion
    private void validateImageNull(final List<MultipartFile> images) {
        final boolean hasNullImage = images.stream()
                        .anyMatch(MultipartFile::isEmpty);
        if (hasNullImage) {
            throw new ImageException(IMAGE_NULL);
        }
    }
```

이런 방식도 있는데 길이는 똑같네요 ..

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +public class ImageService {
transactional 은 없어도 되는 건가요? (진짜 몰라서 그럼)

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +    }
랜덤게에임 랜덤게임

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +    }
이거 로직 한 번 설명 부탁드림다.
new File을 해서 directory를 만드는데 exists 검사를 하는 이유를 모르겠어요..!

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +        }
요것도 뭔가 stream 돌릴 수 있을 것 같은데 ... try catch 있어서 더 복잡해 지려나요 ..

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +            return bytesToHex(hashbytes) + filenameExtension;
hashBytes 어떠신지 ..?

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +            throw new RuntimeException(e);
<img width="487" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/77482065/47691bbb-cfc9-4929-87fc-9ddd2a4288fa">
소나린트가 뭐라 해요

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +        return sb.toString();
```suggestion
        return IntStream.range(0, bytes.length)
                .mapToObj(i -> String.format("%02x", bytes[i] & 0xff))
                .collect(Collectors.joining());
```

신기한 스트림의 세계 ..

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +    private static final String IMAGE_BASE_URL = "https://hanglog.com/img/";
갈비찜 레시피는 언제든 준비돼 있습니다.

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +package hanglog.image.util;
util이란 네이밍이 맞을까? 싶지만 그렇다고 다른 기똥찬걸 추천할 자신은 없음

2023-07-31 16:30 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/Item.java
> +        }
```suggestion
        images.forEach(image -> image.setItem(this));

```

2023-07-31 18:40 UTC, mcodnjs requested changes
이오홍고이오홍고생하셨습니다 👍
1+1 = 3이 되는 매직? 

아직 Converter 부분이랑, Item, Test code는 못봤어요 🥲
먼저 반영하시는 동안 마저 리뷰 작성해놓겠습니다 ~~

2023-07-31 18:40 UTC, mcodnjs commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +    }
```suggestion
    private String hashImageName(final MultipartFile image) {
        final String originalImageName = image.getOriginalFilename();
        final String originalImageNameAndDate = originalImageName + LocalDateTime.now();
        try {
            final MessageDigest sha256 = MessageDigest.getInstance("SHA3-256");
            final byte[] hashedBytes = sha256.digest(originalImageNameAndDate.getBytes(StandardCharsets.UTF_8));
            final String imageExtension = EXTENSION_DELIMITER + getFilenameExtension(originalImageName);
            return bytesToHex(hashedBytes) + imageExtension;
        } catch (final NoSuchAlgorithmException e) {
            throw new RuntimeException(e); // 에러 처리 필요해보여요!
        }
    }
```

2023-07-31 18:40 UTC, mcodnjs commented on backend/src/main/java/hanglog/image/presentation/ImageController.java
> +    public ResponseEntity<ImagesResponse> uploadImage(@RequestPart final List<MultipartFile> images) {
근데 저 근본적으로 궁금한게 생겼는데, 이미지 들어올 때 여러개 들어오나요 ??

2023-07-31 18:40 UTC, mcodnjs commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +public class ImageNameUrlConverter {
클래스명`ImageUrlConverter` 추천 ㅎㅎ
메소드명`convertToName()`, `converToUrl()` 추천 ㅎㅎ 

소소한 의견 남기고 갑니다 ,, >

2023-08-01 00:48 UTC, hgo641 commented on backend/src/test/java/hanglog/image/service/ImageServiceTest.java
> +    //    @DisplayName("이미지들의 이름을 해싱하여 저장하고 URL을 반환한다.")
머야... 이건

2023-08-01 00:56 UTC, LJW25 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +public class ImageService {
DB 접근 안해서 필요없을듯?!

2023-08-01 00:57 UTC, LJW25 commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +package hanglog.image.util;
반박시 대안 필요

2023-08-01 00:57 UTC, LJW25 commented on backend/src/main/java/hanglog/image/presentation/ImageController.java
> +    public ResponseEntity<ImagesResponse> uploadImage(@RequestPart final List<MultipartFile> images) {
넹 리스트로 최대 10개까지 리스트로 들어옵니다. 여행 대표 이미지도 배열에 하나만 담긴 형태로 들어와요.

2023-08-01 01:28 UTC, hgo641 commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    IMAGE_PATH_INVALID(5100, "이미지를 저장할 경로가 올바르지 않습니다.");
@jjongwa 
개별 이미지 용량 초과 : `EXCEED_IMAGE_CAPACITY`
이미지 리스트 사이즈 초과 : `EXCEED_IMAGE_LIST_SIZE`로 최종 결정했습니다...ㅎㅎ 괜춘?

2023-08-01 01:36 UTC, hgo641 commented on backend/src/main/java/hanglog/global/exception/GlobalExceptionHandler.java
> +
@jjongwa 
저희가 만든 message넣었는데 괜찮나요?! (log.warn(message, e)

2023-08-01 01:42 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +    }
반영완!

2023-08-01 01:51 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +    }
@jjongwa 
new File은 단순히 File객체를 만드는 로직이며, 해당 경로에 실제 폴더를 생성하는 로직은 아닙니다!
그래서 directory의 exist 여부를 판단해서 경로에 폴더가 없다면 새로 생성하게 해주었습니다.
저도 몰랐어요 이오가 알려줬어요

2023-08-01 02:04 UTC, waterricecake reviewed
이홍고 수고하셨습니다

2023-08-01 02:04 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +
`findOrElseCreateImage()`어떤가요?

2023-08-01 02:34 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +        }
음... 이 부분 조금... 아니 굉장히 많은 변화가 발생했습니다...
한 번 봐주세요^^...

2023-08-01 02:35 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +            return bytesToHex(hashbytes) + filenameExtension;
적용완!

2023-08-01 02:38 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +            throw new RuntimeException(e);
ImageException으로 대체 완!

2023-08-01 02:38 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +        return sb.toString();
반영완!

2023-08-01 02:44 UTC, mcodnjs commented on backend/src/test/java/hanglog/image/service/ImageServiceTest.java
> +class ImageServiceTest {
여기 개행들 확인해주시면 좋을거같아영 ~~~! 
```
        final MockMultipartFile file = new MockMultipartFile(
                "images",
                "static/images/logo.png",
                "image/png",
                new FileInputStream("./src/test/resources/static/images/logo.png")
        );
```

2023-08-01 02:45 UTC, hgo641 commented on backend/src/main/java/hanglog/image/domain/Image.java
> +    private String imageName;
반영완!

2023-08-01 02:55 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +
@mcodnjs 
메소드 정렬완!

최종네이밍인데 괜찮으신가요?
`validateSizeOfImages`
`validateNullImage`

2023-08-01 03:02 UTC, hgo641 commented on backend/src/main/java/hanglog/image/service/ImageService.java
> +    }
@mcodnjs 
`hashName`메소드를 `ImageFile`이라는 객체의 내부로 옮기면서, 
기존 네이밍인 name, url을 사용해도 직관적일 것 같아 유지했습니다!

+ 이오왈 `final String imageExtension = EXTENSION_DELIMITER + getFilenameExtension(originalImageName);`은 에러가 발생하는 코드가 아니라 try문밖에 있는 게 파악하기 쉬울 것 같다고 하셔서 뺐습니다. 두분합의보세요

2023-08-01 03:03 UTC, hgo641 commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +public class ImageNameUrlConverter {
@mcodnjs 
`ImageUrlConverter` 좋은데요? 반영했습니다!
메소드명은 `convertNameToUrl`, `convertUrlToName`이 더 직관적일 것 같아 그대로 가려는 데 괜찮으신가요?

2023-08-01 03:04 UTC, hgo641 commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    IMAGE_PATH_INVALID(5100, "이미지를 저장할 경로가 올바르지 않습니다.");
반영완!

2023-08-01 03:05 UTC, hgo641 commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +    private static final String IMAGE_BASE_URL = "https://hanglog.com/img/";
반영완!

2023-08-01 03:05 UTC, hgo641 commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +        validateContainBaseUrl(url);
@mcodnjs 
지웠습니당

2023-08-01 03:07 UTC, hgo641 commented on backend/src/main/java/hanglog/image/util/ImageNameUrlConverter.java
> +    }
반영완!

2023-08-01 03:08 UTC, hgo641 commented on backend/src/test/java/hanglog/image/service/ImageServiceTest.java
> +class ImageServiceTest {
반영완!

2023-08-01 04:58 UTC, mcodnjs approved these changes
상수 개행과 변수명만 선택해서 수정 부탁드리겠습니다 ㅎㅎ 
이오홍고생하셨습니다 👍👍👍

2023-08-01 04:58 UTC, mcodnjs commented on backend/src/main/java/hanglog/image/domain/ImageFile.java
> +    private static final String EXTENSION_DELIMITER = ".";
개행 ㅎㅎ ..

2023-08-01 04:58 UTC, mcodnjs commented on backend/src/main/java/hanglog/image/domain/ImageFile.java
> +            final MessageDigest digest = MessageDigest.getInstance("SHA3-256");
변수명 `digest` 대신 `sha256`은 어떠신지 ㅎㅎ ..

2023-08-01 05:37 UTC, hgo641 commented on backend/src/main/java/hanglog/image/domain/ImageFile.java
> +    private static final String EXTENSION_DELIMITER = ".";
악!!!!! 지송

2023-08-01 06:21 UTC, jjongwa approved these changes

2023-08-01 06:21 UTC, merged