Item 생성 API 구현
woowacourse-teams/2023-hang-log pull request #21
Opened 2023-07-12 12:06 UTC by hgo641

## 📄 Summary
> #14
여행 아이템 생성 API를 구현했습니다.
Image 업로드 방식이 아직 정해지지 않아, 우선 Image 없이 생성되게 구현했습니다. 
추후 Image 업로드 방식이 확정되면 업데이트하겠습니다.
그 외 유저 인가 로직과 DayLogFixture 분리를 TODO로 남겨뒀습니다.

## 🙋🏻 More
> * test 코드에서 사용되는 Request DTO가 많아 코드가 길어졌습니다. 개선 방법이 떠오르시면 코멘트 부탁드립니다!(ex. fixture로 request 분리)
> * `ItemService`에서 repository로 탐색한 객체가 존재하지 않으면 `IllegalArgumentException`을 던지고 있습니다. 커스텀 예외로 변경하는 등 의견이 있으시다면 코멘트로 남겨주세요~
> * `ItemService`에서 `ItemRequest`를 받아 `Item`으로 변환하는 로직이 계속 중복될 것 같습니다. 변환 과정이 길어서 코드를 분리하고 싶은데 의견이 있으시다면 남겨주세요! (ex. `Item`에 `ItemRequest`를 인자로 받는 생성자를 추가 or `ItemMapper`같은 클래스를 따로 생성 or `ItemService`내에서 메서드 분리)

2023-07-12 16:32 UTC, jjongwa requested changes
홍고생고생하셨습니다

2023-07-12 16:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/type/ItemType.java
> +    }
Optional check가 안되어 있는데 이 부분은 얘기를 해봐야 할 것 같네용

2023-07-12 16:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/dto/request/ItemRequest.java
> +    private ExpenseRequest expense;
컨벤션 정하죠

2023-07-12 16:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/dto/request/ExpenseRequest.java
> +@AllArgsConstructor
우선 필요한 생성자만 만들어 보고 사용 여부를 얘기해 보는게 좋을 것 같습니당

2023-07-12 16:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/dto/request/ItemRequest.java
> +@AllArgsConstructor
ditto.

2023-07-12 16:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/dto/request/PlaceRequest.java
> +@AllArgsConstructor
ditto.
(오늘의 tmi: ditto는 메타몽의 영어 이름입니다.)

2023-07-12 16:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +    }
place랑 item 만드는데 줄을 많이 잡아먹네요 저거만 아니었으면 메서드가 좀 짧아 보일텐데 지금 적고 있는 글처럼 보면 내용 별거 없는데 괜히 길고 복잡하게 느껴지는 이 느낌 어떡하죠 어떻게 할까요 메서드를 분리해 볼까요 내일 이야기를 나누어 볼까요

2023-07-12 16:32 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +                category);
```suggestion
        Place place = new Place(
                placeRequest.getName(),
                placeRequest.getAddress(),
                placeRequest.getLatitude(),
                placeRequest.getLongitude(),
                category
        );        
```

2023-07-12 16:32 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
> +        );
true도 줄바꿈한다 한 표

2023-07-13 01:37 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/domain/type/ItemType.java
> +    }
이 부분 `get()` 메소드에서 `optional` 관련 워닝 뜨는데, 없으면 에러 처리해주는 로직도 같이 넣어주면 좋을 것 같아요!
그리고 이 부분 수정하면서 개행 변경과 메소드 명 `get`으로 가지가도 좋을 것 같아요
홍고가 선택해서 반영해주세요 ~! 

```suggestion
    public static ItemType get(boolean isSpot) {
        return Arrays.stream(ItemType.values())
                .filter(type -> type.isSpot.equals(isSpot))
                .findFirst()
                .orElseThrow(IllegalArgumentException::new);
    }
```

2023-07-13 01:42 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +    public Long save(final Long tripId, final ItemRequest itemRequest) {
이 부분은 메소드 분리를 하고 싶은데 .. ... .. 조금 더 구현하면서 살펴보죠 ㅎㅎ 
그리고 `tripId`는 나중에 사용되는 필드겠죠 ?!

2023-07-13 01:50 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
> +        );
뚜두뚜두

2023-07-13 01:56 UTC, LJW25 requested changes
홍고 멋있어요🍊
수고하셨습니다~~~

2023-07-13 01:56 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/domain/type/ItemType.java
> +    }
한 라인에 점 하나 컨벤션 부탁드려요~

2023-07-13 01:56 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/presentation/dto/request/ItemRequest.java
> +    private ExpenseRequest expense;
validation 어노테이션 붙이는거 어떤가요?
ex, 필수인 값들은 @NotNull,
rating은 @Min, @Max 등..

+ Expense, Place Request도 같은 피드백입니다.

2023-07-13 01:56 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/fixture/PlaceFixture.java
> +            new Category("문화", "apiId"));
apiCategory로 바꿔주세요. 헷갈려요🫠

2023-07-13 01:56 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/presentation/ItemControllerTest.java
> +                expenseRequest
변수사이에 붙여주세요~~

2023-07-13 11:38 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/dto/request/PlaceRequest.java
> +@AllArgsConstructor
tmi감사합니다 디로씨

2023-07-13 11:39 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/domain/type/ItemType.java
> +    }
if문으로 반영완!

2023-07-13 11:40 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +    public Long save(final Long tripId, final ItemRequest itemRequest) {
나중에 유저 인가 때 사용할듯요?? 유저가 해당 trip에 접근이 가능한가

2023-07-13 11:48 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/ItemController.java
> +        return ResponseEntity.created(URI.create("/trips/" + tripId + "/items/" + id)).build();
@LJW25 합의보세요

2023-07-14 03:59 UTC, mcodnjs requested changes
와우오아우와웅와와우왕 
final이랑 접근제한자 수정만 부탁드립니더 🍊

2023-07-14 03:59 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/domain/type/ItemType.java
> +    }
👍

2023-07-14 03:59 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/domain/type/ItemType.java
> +    }
이거는 접근제한자 default로 둔 이유가 있을까요 !?!

2023-07-14 03:59 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/presentation/ItemController.java
> +        return ResponseEntity.created(URI.create("/trips/" + tripId + "/items/" + id)).build();
itemId랑 final 까지!

2023-07-14 04:20 UTC, jjongwa commented on backend/src/main/java/hanglog/global/BaseEntity.java
> +    }
어어 이거 건들면 컨플릭트 날텐데

어짜피 제 pr 먼저 머지할꺼니까 상관은 없습니다

2023-07-14 04:20 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/Item.java
> +    @ManyToOne(fetch = LAZY, cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
static import

2023-07-14 04:20 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +    public Trip(
어어어 이것도 왜 건들죠? 제가 바꿨습니다만

2023-07-14 05:26 UTC, waterricecake reviewed
수고했습니다 홍고

2023-07-14 05:26 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/presentation/dto/request/ExpenseRequest.java
> +}
```suggestion
@Getter
@AllArgsConstructor
public record ExpenseRequest(
        @NotNull(message = "화폐의 통화명 입력해주세요.") @Size(max = 45, message = "화폐 통화명은 45자를 초과할 수 없습니다.") String currency,
        @NotNull(message = "화폐의 금액을 입력해주세요.") Integer amount,
        @NotNull(message = "화폐의 카테고리를 입력해주세요.") Long categoryId) {
}
```
intellij에서 record 추천하던데 어떤가요?

2023-07-14 05:36 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +    public Trip(
제껀줄 ㅎ; ㅈㅅ

2023-07-14 05:45 UTC, mcodnjs approved these changes

2023-07-14 05:48 UTC, LJW25 approved these changes

2023-07-14 06:06 UTC, waterricecake approved these changes

2023-07-14 06:11 UTC, jjongwa approved these changes

2023-07-14 06:30 UTC, merged