RestDocs 적용
woowacourse-teams/2023-hang-log pull request #25
Opened 2023-07-12 14:53 UTC by LJW25

## 📄 Summary
> #15   
> RestDocs 기본 셋팅 완료하고, `TripControllerTest`의 `createTrip()`에 시험 적용하였습니다.  

## 🙋🏻 More

> 동작을 테스트해보고 싶으시면 터미널에서
> ```
>  ./gradlew clean build
> ````
> 명령어를 사용하여 실행 후, 생성되는 `main/resources/static/docs/docs.html` 파일을 열어보시면 됩니다.

> 구체적인 사용법은 금주 내로 노션에 정리 후 공유하겠습니다.

2023-07-12 15:42 UTC, jjongwa requested changes

2023-07-12 15:42 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
teco-style이 적용되어 있지 않은 것 같아요.! option+cmd+L 로 정렬하면 static import가 최상단으로 와야 합니다..!

2023-07-12 15:42 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +                                        fieldWithPath("cityIds").type(JsonFieldType.ARRAY).description("도시 ID 목록").attributes(field("constraint", "1개 이상의 양의 정수"))
```suggestion
requestFields(
                                        fieldWithPath("startDate").type(JsonFieldType.STRING).description("여행 시작 날짜")
                                                .attributes(field("constraint", "yyyy-MM-dd")),
                                        fieldWithPath("endDate").type(JsonFieldType.STRING).description("여행 종료 날짜")
                                                .attributes(field("constraint", "yyyy-MM-dd")),
                                        fieldWithPath("cityIds").type(JsonFieldType.ARRAY).description("도시 ID 목록")
                                                .attributes(field("constraint", "1개 이상의 양의 정수"))
                                ),
```

여기도 가로줄 제한을 넘겨서 정렬하면 이렇게 바뀌는데 type과 description도 줄바꿈 하는 방법도 좋아 보입니다.!

2023-07-12 15:42 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/restdocs/RestDocsConfiguration.java
> +    }
<img width="630" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/77482065/c2629813-38e5-467f-bd6a-427d1c6c580c">


```suggestion
    public static Attribute field(final String key, final String value) {
        return new Attribute(key, value);
    }
```

2023-07-12 15:42 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/restdocs/RestDocsTest.java
> +    protected MockMvc mockMvc;
필드 사이에 띄우나요 안띄우나요?

2023-07-13 01:41 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/restdocs/RestDocsTest.java
> +    protected MockMvc mockMvc;
일반 필드 사이에는 띄우지 않고, 어노테이션이 붙은 필드는 띄우는 것으로 결정되었습니다 🔨

2023-07-13 01:41 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +                                        fieldWithPath("cityIds").type(JsonFieldType.ARRAY).description("도시 ID 목록").attributes(field("constraint", "1개 이상의 양의 정수"))
적용하였습니다 :)

2023-07-13 01:42 UTC, jjongwa approved these changes

2023-07-13 01:44 UTC, hgo641 approved these changes

2023-07-13 01:53 UTC, mcodnjs approved these changes
굿굿굿굿 🏊‍♂️👍

2023-07-13 02:51 UTC, merged