일일 환율 api 조회 기능 구현
woowacourse-teams/2023-hang-log pull request #332
Opened 2023-08-06 11:42 UTC by waterricecake

## 📄 Summary
>#168
일일 환율 데이터를 가져오는 기능을 구현하였습니다.
`CurrencyService`의 `saveDailyCurrency`를 통해 특정 날짜의 환율 데이터를 가져올 수 있게 하였습니다.

Test의 경우 직접 공공 api에 요청하여 데이터를 가져오기 때문에 인터넷이 연결 되어있어야 가능합니다.

트리거의 경우 어떻게 할지 아직 논의가 되지 않았기 때문에 service까지만 구현을 해놓았습니다.

중간 중간 공공 api에서온 response의 중국화 통화코드가 `cnh`인지 판단하는 코드들은 db에는 `cny`로 하였지만 api에서 제공하는 통화코드들이 `cnh`로 되어있기 때문에 그렇습니다.
## 🙋🏻 More
>

2023-08-07 07:31 UTC, LJW25 approved these changes

2023-08-07 07:31 UTC, LJW25 commented on backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
> +                .extracting("code").isEqualTo(3006);
줄바꿈?
```suggestion
        assertThatThrownBy(() -> currencyService.saveDailyCurrency(weekend))
                .isInstanceOf(InvalidDomainException.class)
                .extracting("code")
                .isEqualTo(3006);
```

2023-08-07 07:31 UTC, LJW25 commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +
👍

2023-08-07 11:27 UTC, waterricecake commented on backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
> +                .extracting("code").isEqualTo(3006);
@waterricecake
[code: 코드 컨벤션 적용](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/1431610fd0d37c8295d356cc482c5aae984a7e88)

2023-08-07 11:27 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/domain/type/CurrencyType.java
> +                .filter(value -> value.code.equals(currencyCode.toLowerCase().replace("(100)", "")))
[refactor: 구분자 상수화](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/ac1b0c100fb71e797fc8b3dd29fa2068b4cf6822)
하는 김에 모든 구분자 상수화 진행했습니다.

2023-08-07 11:28 UTC, waterricecake reviewed
currency에 controller를 추가하면서 currency로직이 expence패키지 안에 있기에는 너무 경비와 관련없는 로직들이라 패키지분리를 했는데 어떤가요?

2023-08-07 18:33 UTC, mcodnjs requested changes
고생하셨습니다ㄹ리달리달 ~

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/main/java/hanglog/currency/dto/CurrencyResponse.java
> +    private String currencyCode;
CurrencyType이랑 동일하게?? 가려면 currencyCode보단 그냥 `code`가 더 좋은거같아요

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
> +        final Currency actual = currencyService.saveDailyCurrency(date);
저는 여기서 NPE 발생하는데 달리는 통과되나요 ??

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/main/java/hanglog/currency/domain/type/CurrencyType.java
> +                .filter(value -> value.code.equals(currencyCode.toLowerCase().replace("(100)", "")))
여기도 상수화해주면 좋을거 같네용

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/main/java/hanglog/currency/domain/type/CurrencyType.java
> +        }
cnh와 관련된 로직이 생긴 이유가 뭔가요 ?!

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    INVALID_DATE_WHEN_WEEKEND(3006, "공휴일에는 공공 환율 api를 조회할 수 없습니다."),
정확히는 공휴일이 아닌 주말 ??

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    private List<CurrencyResponse> getCurrencyList(final LocalDate today) {
모두 `get~~` 메소드라서 어디서 요청보내는지 알기 쉽게 request라는 단어를 붙이는건 어떤가요 ??

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/test/java/hanglog/currency/presentation/CurrencyControllerTest.java
> +    @DisplayName("")
`@DisplayName` 써줍시다!

2023-08-07 18:33 UTC, mcodnjs commented on backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
> +    void failSaveCurrencyAtWeekend(final int date) {
우리의 컨벤션과 다른 느낌?? 
네이밍은 완전히 직관적인데 저희 앞에 메소드명은 항상 붙이기로 했었던거 같아서 ㅎㅎ ..

2023-08-08 01:47 UTC, waterricecake commented on backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
> +        final Currency actual = currencyService.saveDailyCurrency(date);
저는 통과되요. github action 통과된거면 테스트 통과되지 않나요?

2023-08-08 02:01 UTC, waterricecake commented on backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
> +    void failSaveCurrencyAtWeekend(final int date) {
메서드명을 쓰는 것을 위에 사용했어서 뭔가 다르게 해야되는데 어쨌던 실패 테스트라 네이밍을 붙였는데 여러개라면 _붙이는 컨벤션을 제가 잊고있었네요;;

2023-08-08 02:05 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/domain/type/CurrencyType.java
> +        }
중간 중간 공공 api에서온 response의 중국화 통화코드가 cnh인지 판단하는 코드들은 db에는 cny로 하였지만 api에서 제공하는 통화코드들이 cnh로 되어있기 때문에 그렇습니다.
국내용을 CNY, 국외용을 CNH라고 하며, CNY는 중국 본토에서, CNH는 주로 홍콩에서 거래되는 위안화라고 하네요. 처음 db 설계할때 CNY로 설계를 하였는데 공공 api에서 제공하는 통화가 cnh라 이렇게 반영했습니다. 여행을 간다고 하면 중국내에서 사용하는 돈이라 CNY로 한것 같은데 이거는 다같이 얘기해봐야 하겠네요.

2023-08-08 02:08 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    public Currency saveDailyCurrency(final LocalDate date) {
date로 통일시켜야겠네요.

2023-08-08 02:12 UTC, waterricecake commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    INVALID_DATE_WHEN_WEEKEND(3006, "공휴일에는 공공 환율 api를 조회할 수 없습니다."),
주말로 할까 하다가 나중에 만약에 공휴일 전체를 잡을 수 있다면 같이 쓸 수 있지않을까 하며 내부 message를 저렇게 설정해 두었는데 `INVALID_CURRENCY_DATE`로 변경해두었습니다.

2023-08-08 02:21 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        final Map<CurrencyType, Double> currencyTypeRateMap = new EnumMap<>(CurrencyType.class);
[refactor: 변수명 변경](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/9b0d5c1c9c02f20991b89cb0a63b26ad38dda3f2)

2023-08-08 02:21 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/dto/CurrencyResponse.java
> +    private String currencyCode;
[refactor: 변수명 변경](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/9b0d5c1c9c02f20991b89cb0a63b26ad38dda3f2)

2023-08-08 02:21 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/domain/type/CurrencyType.java
> +                .filter(value -> value.code.equals(currencyCode.toLowerCase().replace("(100)", "")))
[refactor: JPY 단위 문자열 상수화](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/e0f8ef4a73099b111cb36f6ed99e109390734c33)

2023-08-08 02:22 UTC, waterricecake commented on backend/src/test/java/hanglog/currency/presentation/CurrencyControllerTest.java
> +    @DisplayName("")
[code: 코드 컨벤션 적용](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/c4b9004e727699d05b9ff338e554dff0438d4a6d)

2023-08-08 02:25 UTC, jjongwa reviewed
어어 리뷰 다는동안 업데이트 됐나보네요 다시 한 번 보겠습니당

2023-08-08 02:25 UTC, jjongwa commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +                .toList();
```suggestion
  return Arrays.stream(
                        Optional.ofNullable(restTemplate.getForObject(getCurrencyUrl(today), CurrencyResponse[].class))
                                .orElseThrow(() -> new InvalidDomainException(NOT_FOUND_CURRENCY_DATA))
                )
                .toList();
```

2023-08-08 02:27 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/presentation/CurrencyController.java
> +        return ResponseEntity.created(URI.create("/currency/" + currency.getDate())).build();
- 물론 프론트와 소통하는 api가 아니긴 한데 사용하는 입장에서 오늘 날짜가 정확히 들어갔는지 확인한다는 의미에서 보내주었습니다
- 정확히는 `/currency/2023-08-03`으로 갑니다.
- `currency.getDate()`를 통해 저장한 currency의 날짜를 보내줄려고 currecny.getDate()를 사용하였습니다.

확인한다는 의미에서 넣어주었는데 재활용할리도 없을것 같고... 굳이라는 생각이 들어서 `ResponseEntity.ok().build()`로 수정하였습니다.
[refactor: controller 응답 수정](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/4cc81697a90ec96b6b63f2dd5749ed5164da2fd8)

2023-08-08 02:29 UTC, jjongwa commented on backend/src/test/java/hanglog/currency/service/CurrencyServiceTest.java
> +        final Currency actual = currencyService.saveDailyCurrency(date);
로컬에서 yml 안바꿔줘서 그런듯

2023-08-08 02:40 UTC, jjongwa commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    INVALID_DATE_WHEN_WEEKEND(3006, "공휴일에는 공공 환율 api를 조회할 수 없습니다."),
음 지금 로직이
1. 공공데이터 api 안쏘고 주말인지 확인 -> 주말이면 INVALID_CURRENCY_DATE
2. 공공데이터 api 쏘고 반환 데이터가 없으면 예외처리 -> NOT_FOUND_CURRENCY_DATA 반환

해당 날짜가 주말이 아닌 공휴일인지는 2번 경우에서 밖에 거를 수 없다고 생각하는데, 
그러면 1번에서 반환하는 코드가 INVALID_DATE_WHEN_WEEKEND(3006, "주말에는 공공 환율 api를 조회할 수 없습니다.") 로 가도 좋을 것 같아요. 

달리가 생각하는 `나중에 만약에 공휴일 전체를 잡을 수 있다면 같이 쓸 수 있지않을까 하며 내부 message를 저렇게 설정해 두었는데` 부분에서 생각해둔 로직이 있을까요?

2023-08-08 02:42 UTC, jjongwa commented
지금 구조에서는 해당 날짜의 데이터가 중복해서 저장될 수 있는 것 같은데, db에서 해당 날짜의 데이터가 이미 존재하는지 검증하는 로직도 필요할 것 같습니다..!

2023-08-08 06:11 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/domain/type/CurrencyType.java
> +        if (currencyCode.equals("cnh")) {
[refactor: 중궁엔화 상수화](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/d811beabf0f2972f5002f551e7d2d666c2e0f9fd)

2023-08-08 06:11 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        }
[refactor: 메서드 로직 변경 및 중복 날짜 예외처리](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/97e373f3efa7da1016e6d6c93a42aeaff45920d0)

2023-08-08 06:12 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +                .toList();
[refactor: 메서드 로직 변경 및 중복 날짜 예외처리](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/97e373f3efa7da1016e6d6c93a42aeaff45920d0)

2023-08-08 06:13 UTC, waterricecake commented
> 지금 구조에서는 해당 날짜의 데이터가 중복해서 저장될 수 있는 것 같은데, db에서 해당 날짜의 데이터가 이미 존재하는지 검증하는 로직도 필요할 것 같습니다..!

[refactor: 메서드 로직 변경 및 중복 날짜 예외처리](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/97e373f3efa7da1016e6d6c93a42aeaff45920d0)
예외처리 추가하였습니다.

2023-08-08 06:47 UTC, waterricecake commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    INVALID_DATE_WHEN_WEEKEND(3006, "공휴일에는 공공 환율 api를 조회할 수 없습니다."),
refactor: 주말 예외코드 수정 및 INVALID_REQUEST 코드 수정

2023-08-08 06:50 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    private List<CurrencyResponse> getCurrencyList(final LocalDate today) {
@waterricecake
[refactor: 메서드명 수정](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/985566c781e6397b2e0941380844e999570adb41)
getter랑 혼동이 올 수도 있어서 생성의 경우 create를 요청의 경우 request를 붙였습니다.

2023-08-08 07:44 UTC, hgo641 approved these changes
고생하셨습니다!!!!!👍👍👍

2023-08-08 07:44 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        return Arrays.stream(
여기에 `Filtered`라는 이름이 붙은 이유가 
api에서 받아온 환율 정보 중, 저희 서비스에서 사용중인 환율의 정보만 가져오기 때문 맞나요?

이거 때문이면 여기 메서드 이름에 `Filtered`가 없는 게 오히려 이해하기 쉬울 것 같기도 해요! 처음에 메서드 이름보고 어떤 걸 필터링 해온다는 건지 떠올리기가 힘들었습니다.

개발자 입장에서는 당연히 저희 서비스에서 사용중인 화폐 정보만 불러올 거라고 기대할 것 같아요. 그래서 `Filtered`라는 키워드가 없는 게 더 이해하기 쉬울 것 같은데 어떻게 생각하시나요? 지금 이름이 더 직관적이라면 그대로 가셔도 괜찮습니다!

2023-08-08 07:44 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        final List<CurrencyResponse> currencyResponses = requestFilteredCurrencyResponses(date);
`CurrencyResponse`는 한 국가의 환율 정보이고 `Currency`는 (저희 서비스에서 지원하는)모든 국가의 환율 정보 맞죠?

`CurrencyResponse`가 좀 더 작은 단위를 표현하고 있는데 이름이 `Currency`의 응답이라서 조금 헷갈리네요ㅠㅠ 다른 네이밍 없을까요?

2023-08-08 07:44 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/domain/type/CurrencyType.java
>      }
저희 서비스에서 지원하는 화폐 타입인지를 반환하는 메소드죠?
이름 `isProvided` 어떤가요?

2023-08-08 07:44 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/domain/Currency.java
> +package hanglog.currency.domain;
패키지 분리 좋은데요?

2023-08-08 07:44 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/domain/repository/CurrencyRepository.java
> +    boolean existsByDate(LocalDate date);
jpa는 정말 신기한 메소드들을 많이 지원하는군요...ㅋㅋ 배워갑니다

2023-08-08 07:44 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    private static final String JAPAN_UNIT_STRING = "(100)";
`CurrencyType`에도 있던 상수인데 중복적으로 등장하는군요!
api로 받은 code를 `CurrencyType`에서 사용하는 code명으로 매핑해주기 위해 있는 상수인 것 같은데, 

"`api의 code와 매핑되는 CurrentType의 code 반환`"하는 기능을 `CurrencyType`에게 아예 위임해버리면 어떨까요?

2023-08-08 07:48 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/domain/repository/CurrencyRepository.java
> +    Currency findByDate(LocalDate date);
이전 controller 로직에서 exist로 검증을 하고 반환하는 로직이었기 때문에 optional일 필요가 없었지만 void로 반환값이 없어지면서 아에 필요없는 메서드가 됬네요 제거하였습니다.

2023-08-08 08:05 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        final List<CurrencyResponse> currencyResponses = requestFilteredCurrencyResponses(date);
예 맞아요. CurrencyResponse는 한 국가의 환율 정보이고 Currency는 어떤날의 모든 국가의 환율 정보인데...
확실히 혼동이 오기는 하네요. 그럼 `SingleCurrencyResponse`는?
[refactor: dto 클래스명 변경](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/ca27af63fa1f233b12add1dd644a139a926a62b6)

2023-08-08 08:05 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/domain/type/CurrencyType.java
>      }
[refactor: dto 클래스명 변경](https://github.com/woowacourse-teams/2023-hang-log/pull/332/commits/ca27af63fa1f233b12add1dd644a139a926a62b6)

2023-08-08 08:08 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        return Arrays.stream(
직관적인게 더 좋긴한데... 이대로 가겠습니다. 원래 filter로직이 외부에 있었는데 어쨌든 필요한 로직이라 생각해서 이후에 사용하더라도 이 메서드가 거른다는걸 메서드만으로 알 수 있으면 좋겠다 생각했습니다.

2023-08-08 08:32 UTC, mcodnjs approved these changes

2023-08-08 08:33 UTC, merged