소셜 인증 인가 구현
woowacourse-teams/2023-hang-log pull request #39
Opened 2023-07-13 08:32 UTC by waterricecake

## 📄 Summary
>
소셜 인증 후 유저 정보를 가져와 member에 저장하는 것까지 구현하였습니다.

## 🙋🏻 More
>
테스트하는데 문제가 있네요 RestTemplate가 nullable이 많은데 mock으로 처리하려고 하니 계속 에러가 뜨네요. acesstoken이 실시간으로 바꿔서 매번 유저 정보를 인가받는 것도 불가능한데 좋은 방법이 있을까요...

그리고 유저의 id는 구글과 카카오의 유저 id를 저장하였습니다.

2023-07-13 12:09 UTC, hgo641 reviewed
고생하셨습니다! 달리!!! 👍👍

2023-07-13 12:09 UTC, hgo641 commented on backend/src/main/java/hanglog/member/Member.java
> +    public Member(Long id, String name, String image) {
인자에 final 붙여주세요!

2023-07-13 12:09 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +public class OAuthLoginService {
`@Transactional`!

2023-07-13 12:09 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +            throw new IllegalArgumentException("member already exist");
예외메시지 한글? 영어? 논의해봐야할 것 같네요

2023-07-13 12:09 UTC, hgo641 commented on backend/src/main/java/hanglog/member/Member.java
> +    private String name;
Size Validation 없어도 될까요?

2023-07-13 12:14 UTC, waterricecake commented on backend/src/main/java/hanglog/member/Member.java
> +    private Long id;
이거 식별자를 OAuth 에서 받아온걸 (구글 id 나 kakao id) 넣어주고 있습니다. 어차피 id가 고유값이라 이 값을 id로 써도 될것 같아서 굳이 auto increament로 따로 안만들어도 될 것 같아 없엤습니다.

2023-07-13 12:25 UTC, waterricecake commented on backend/src/main/java/hanglog/member/Member.java
> +    private StatusType status = USABLE;
아 가져오면서 지우는 걸 잊었네요 member의 status가 휴면, 활성, 삭제 3가지를 가져야해서 baseEntity의 status와 다르다고 생각해서 base를 상속받지 않고 이렇게 작성했습니다. 위의 status를 지우고 statusMember를 살릴 것 같네요

2023-07-13 12:25 UTC, waterricecake commented on backend/src/main/java/hanglog/member/Member.java
> +    private String name;
구글이나 카카오에서 제공하는 이름의 제한이 몇인지 모르겠어서 일단 제한을 두지 않았습니다.

2023-07-14 01:31 UTC, jjongwa commented on backend/src/main/java/hanglog/member/Member.java
> +    private Long id;
되겠냐

2023-07-14 01:31 UTC, jjongwa commented on backend/src/main/java/hanglog/member/Member.java
> +    private Long id;
아아아

2023-07-14 06:10 UTC, waterricecake commented on backend/src/main/java/hanglog/member/Member.java
> +    private Long id;
되겠냐라고 해서 식별자랑 socialId 값으로 반영했습니다

2023-07-14 16:47 UTC, jjongwa commented
https://github.com/woowacourse-teams/2023-hang-log/pull/39/commits/5b465835aab40080ce5f761f210d9be315ee3ae6 이 레전드 커밋을 뒤늦게 봐버렸습니다.
타코야끼 배달시켜놓고 기다리면서 싱글벙글 하고 있었는데 이건 먼저 달아 놔야겠어요.
이제라도 본게 다행이라고 생각이 들기도 합니다. 
무슨 생각으로 이러신건진 모르겠지만 
현재 상태의 PR이 머지된다면 
우리들의 멋진 동반자 프론트 팀원들이 열심히 만들어 놓은 작업물들이 
한 순간 자취를 감춰버리는 레레전드 develop 브랜치가 탄생하게 됩니다.
물론 revert 시키면 되니까 그렇게 크리티컬한 일은 아닐지도? 
라고 생각이 들면서도 
실시간으로 저 자신에게 화가 나네요. 
이걸 이제야 파악해? 
우상단에 -34,000줄이 삭제됐다고 나와있는데? 
refactor도 아니고 feature가? 
커밋 메시지도 [social id 0 값 반환 해](https://github.com/woowacourse-teams/2023-hang-log/pull/39/commits/5b465835aab40080ce5f761f210d9be315ee3ae6) 
저도 커밋 메시지를 잘 쓴다고 생각하지는 않지만 이런 명령문 메시지는 처음 접하네요.
약간 마법?주문?이런건가 아아아 농담농담 
결국 "반환 해" 했더니 
frontend 패키지가 사라져 버리는 리얼 레전드 스펠이 발동해 버렸습니다.
주절주절 말이 많았네요 죄송합니다.
근데 저희 그라운드 룰 정했잖아요
"네 잘못은 우리 잘못"
그러니까 당신의 실수를 이제야 파악한 저의 잘못은
우리 백엔드 크루 모두의 잘못입니다. 
반성하세요.
혹시라도 주말동안 self merge를 하고 
다른 크루들이 새로운 PR을 merge하는 경우를 방지하기 위해서
2명 이상의 팀원이 approve를 해 주었을때만 merge가 가능하도록
제한을 호다닥 걸어놨습니다.
merge 조건은 월요일에 다시 얘기를 놔눠보도록 하죠.
우선 지금 상황에서는 **git pull origin develop** 해서
프론트 코드들을 다시 가져오기만 하면 될 것 같네요.
어어어 근데 restDocs 관련 파일도 지워놨군요 도대체 무슨 마법을 부리신 겁니까 휴먼
휴먼이 아니라 매지션의 경지에 도달하셨습니까
한낱 머글인 저의 입장에서는 이해가 되지 않습니다.
도대체 어떠한 과정을 통해 저 코드들이 사라지게 됐는지
월요일에 들어볼 생각 하니까 재밌네 이거
다시 기분이 좀 좋아지네요
근데 타코야끼 왜이렇게 안오지
타코야끼가 늦게 오니까 글이 점점 더 길어지네요
근데 이렇게 글 안썼으면
월요일에 이거 그대로 얘기했을거에요
그거 아십니까? 대부분의 타코야끼는 
문어가 아닌 가문어 즉 대왕오징어를 넣어서 단가를 낮춘답니다.
하지만 제가 시킨 곳은 타코야끼연구소. 진짜 문어를 넣고
정성을 다해 조리하는 곳이죠.
신림 부근에서 타코야끼가 먹고싶다면 여기를 기억해주세요.
근데 그것보다 더 중요하게 기억해야 할 사항이 있습니다.
PR을 올렸을 때,
우 상단에 초록색으로 몇 라인이 추가됐고 
빨간색으로 몇 라인이 삭제되었는지 표시가 되는데요.
+408 −34,880 이라고 적혀있죠?
408라인이 새로 생성됐고
34,880라인이 삭제됐다는 소리입니다.
딱 보면 어 뭔가 사곤데 싶죠?
그러면 다시 한 번 자신의 커밋들을 돌아가 보면서
어디가 잘못됐는지 파악하는 습관을 가지는게 좋을 것 같습니다.
근데 사실 인텔리제이에서 커밋할때 저 파일들 삭제하는거 체크했을텐데
아닌가 그냥 폴더 삭제하고 터미널에서 add . 한건가
내막을 잘 모르겠지만
일단 월요일에 만나서 들어볼께요
그럼 이만 줄이겠습니다.
우리 다같이 체크아웃 박수 외치고 끝내볼까요?
자 하나 둘 셋
파이팅
짝짝짝짝짝짝짝

2023-07-15 08:18 UTC, jjongwa requested changes
제가 해당 개념에 대해 자세하게 알지 못하지만 지금 작성된 코드는 정확히 말하면 인증 로직 구현 까지라고 볼 수 있겠네요

아는게 많이 없다 보니까 세부 로직에 대해 comment를 달기 힘들어서 우선은 전체적인 컨벤션이랑 궁금한 점 위주로 달아놨습니다~

테스트코드도 따로 이슈 만들기 보단 여기서 추가해줘야 머지 가능할듯..!

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/Member.java
> +    private LocalDateTime lastLoginDate;
요놈도 nullable = false 걸어주면 좋을 것 같아용

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/repository/MemberRepository.java
> +@Repository
https://www.inflearn.com/questions/110045/jparepository%EB%82%98-crudrepository-%EA%B0%99%EC%9D%80-%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4%EC%97%90-repository-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98%EC%9D%B4-%EC%95%88%EB%B6%99%EB%8A%94-%EC%9D%B4%EC%9C%A0%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C-%EA%B6%81%EA%B8%88%ED%95%A9%EB%8B%88%EB%8B%A4

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/repository/MemberRepository.java
> +    boolean existsBySocialId(String id);
한 칸 띄우기 컨벤션

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/exception/AlreadyExistUserException.java
> +    public AlreadyExistUserException(String message) {
컨벤션벤션

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/exception/UserAuthorizeException.java
> +    public UserAuthorizeException(String message) {
컨벤션벤션벤션

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +    //todo : exception custom
todo를 대문자로 바꿔보세용

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +        params.add("grant_type", "authorization_code");
뭔가 더 깔끔하게 만들 수 있을 것 같아요

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +        final ResponseEntity<JsonNode> responseNode = restTemplate.exchange(tokenUri, HttpMethod.POST, entity,
JsonNode 타입이 무엇인가용?
진짜 몰라서 그럼

2023-07-15 08:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/service/mapper/OAuthProvider.java
> +        throw new IllegalArgumentException();
일단은 메시지도 넣어놔주면 좋을듯요

2023-07-15 08:18 UTC, jjongwa commented on backend/src/test/java/hanglog/feature/MemberFeature.java
> +    public static final String GOOGLE_USER_INFO_JSON_STRING =
컨벤션벤션벤션벤션

2023-07-15 08:18 UTC, jjongwa commented on backend/src/test/java/hanglog/member/mapper/OAuthProviderTest.java
> +    @ParameterizedTest(name = "{0} OAuth2 요청에서 id, 닉네임, 프로필사진을 가져온다.")
컨벤션벤션벤션벤션벤션

2023-07-15 08:18 UTC, jjongwa commented on backend/src/test/java/hanglog/member/mapper/OAuthProviderTest.java
> +        //then
숨은그림찾기 재밌네요

2023-07-15 08:18 UTC, jjongwa commented on backend/src/test/java/hanglog/member/mapper/OAuthProviderTest.java
> +    private static Stream<Arguments> oAuthRegisterProvider(){
함수 extract 하는데 자동으로 static이 붙었고 그걸 캐치하지 못했다
는 흐름 예상해 봅니다

2023-07-17 12:11 UTC, waterricecake commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +        params.add("grant_type", "authorization_code");
고민중입니다... 이게 근데 RestTemplate이 외부 uri에 요청을 보낼때 body에 넣어주는 string 만드는 거라...

2023-07-17 12:14 UTC, waterricecake commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +        final ResponseEntity<JsonNode> responseNode = restTemplate.exchange(tokenUri, HttpMethod.POST, entity,
Json String을 편하게 읽기 위한 라이브러리입니다. 예를 들어 {"id" : "123"}이라는 json String이 오면 이것을 json node로 감싸주고나서 jsonnode.get("id")를 하면 123이라는 값을 받아올 수 있습니다.

2023-07-17 12:41 UTC, waterricecake commented on backend/src/main/java/hanglog/member/config/LoginConfigure.java
> +}
이거는 제가 나중에 알게된 사실인데 Spring boot에는 restTemplate이 bean에 등록되어 있지않고 RestTemplateBuilder가 등록되어 있더라고요. 저는 restTemplate이 없어서 config로 등록해주었습니다.
restTemplate은 spring내에서 외부로 rest요청을 보낼때 사용하는 클라이언트 라이브러리입니다. restTemplate은 HttpAccessor를 상속받는데 이게 Rest(POST, PUT 등) 요청을 할 수 있게 해주더라고요. 빈에 등록하는 이유는 정확하지는 않은데 추측하는 것은 OS에 http 프로토콜 요청을 할때 연결하는 행위를 줄이기 위해서가 아닐까로 생각합니다.

2023-07-17 12:43 UTC, waterricecake commented on backend/src/test/java/hanglog/member/mapper/OAuthProviderTest.java
> +    private static Stream<Arguments> oAuthRegisterProvider(){
static으로 안하면 initializationerror가 나더라고요. 
```
org.junit.platform.commons.PreconditionViolationException: Cannot invoke non-static method [private java.util.stream.Stream<org.junit.jupiter.params.provider.Arguments> hanglog.member.mapper.OAuthProviderTest.oAuthRegisterProvider()] on a null target.
```

2023-07-18 07:14 UTC, LJW25 approved these changes
넘 수고하셨습니다.
진짜 복잡하네요.
자잘한 컨벤션만 봐주시면 감사하겠습니다

2023-07-18 07:14 UTC, LJW25 commented on backend/src/main/java/hanglog/member/provider/OAuthProvider.java
> +        }
google, kakao 상수화 하는거 어떤가요?

2023-07-18 07:14 UTC, LJW25 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +    private static final String PROPERTY_PATH = "spring.oauth2.client.registration.";
상수 뒤 공백 부탁드립니다

2023-07-18 07:14 UTC, LJW25 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +        String socialLoginId = userResourceNode.get("id").asText();
final?

2023-07-18 07:14 UTC, LJW25 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +        MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
final? put하면 불가능한가요? 진짜 몰라서 질문드림

2023-07-18 08:50 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +                env.getProperty(PROPERTY_PATH + registrationId + ".token-uri"),
`@Value`대신 environment에서 값을 가져오신 이유가 있나요?

2023-07-18 08:50 UTC, hgo641 commented on backend/src/main/java/hanglog/member/controller/OAuthLoginController.java
> +    public void loginOAuth(@RequestParam final String code, @PathVariable final String registrationId) {
`registrationId`가 google, kakao이런 거 맞나요? 
`oauthProvider`같은 이름은 어떠신가요?

2023-07-18 08:50 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +    public JsonNode getUserInfo(final String accessToken, final String registrationId) {
JsonNode대신 다른 걸로 return하면 어떨까요?

2023-07-18 09:13 UTC, hgo641 reviewed
달리고생고생하셨습니다~~~

2023-07-18 09:13 UTC, hgo641 commented on backend/src/main/java/hanglog/member/provider/GoogleOAuthProvider.java
> +public class GoogleOAuthProvider extends OAuthProvider {
인터페이스로 구현할 수도 있는데 상속을 선택하신 이유가 있나요?

2023-07-18 09:13 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +    private static final String PROPERTY_PATH = "spring.oauth2.client.registration.";
`annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"` 이거 사용해보시는 게 어떨까요?

2023-07-18 09:13 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +        headers.set("Authorization", "Bearer " + accessToken);
Authorization Spring에서 제공하는 상수를 사용하면 어떨까요?

2023-07-19 01:15 UTC, waterricecake commented on backend/src/main/java/hanglog/member/service/OAuthLoginService.java
> +                env.getProperty(PROPERTY_PATH + registrationId + ".token-uri"),
`@Value`로 property에 접근할 수 있다는 것을 몰랐습니다! 좋은 정보 감사합니다~

2023-07-19 01:28 UTC, waterricecake commented on backend/src/main/java/hanglog/member/controller/OAuthLoginController.java
> +    public void loginOAuth(@RequestParam final String code, @PathVariable final String registrationId) {
예 맞아요. oauthProvider가 더 명확한거 같네요!

2023-07-21 07:32 UTC, hgo641 reviewed
달리 고생고생많으십니다@!!!

2023-07-21 07:32 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/LoginService.java
> +    }
로그인 시 멤버repo에 멤버가 존재하지 않으면 새 멤버를 만드는 게 맞을까요? 예외를 터뜨리는 게 좋지않을까요?

2023-07-21 07:32 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/LoginService.java
> +    private HttpEntity getEntity(final String code) {
이름이 모호한 것 같아요. 좀 더 기능을 드러내는 이름은 없을까요?.?

2023-07-21 07:32 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/GoogleLoginService.java
> +            @Value(PROPERTIES_PATH + "client-id}") final String clientId,
`@Value`보다 더 좋아보이는 거 찾았습니다...ㅎㅎ
[@ConfigurationProperites](https://blog.yevgnenll.me/posts/spring-configuration-properties-fetch-application-properties)

2023-07-21 07:32 UTC, hgo641 commented on backend/src/main/java/hanglog/member/controller/OAuthLoginController.java
> +    private final Provider provider;
컨트롤러가 service를 가지고 있는 구조에서, 
컨트롤러가 provider를 가지고 provider가 service를 생성하는 구조로 바꾸신 이유가 뭔가요?

2023-07-21 07:32 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/Provider.java
> +        throw new IllegalArgumentException();
예외메시지추가해주세요!

2023-07-21 07:32 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/Provider.java
> +}
if문으로 나눠서 반환해주는 것도 좋은데 enum으로 oauthProviderName이랑 각 LoginService 매핑해서 반환해주는 건 어떠신가요? oauthProvider가 많이 추가될 것 같진 않은데, 추가된다면 if문이 계속 늘어난다는 게 조금 걸리네요

2023-07-21 07:46 UTC, hgo641 commented on backend/src/main/java/hanglog/member/controller/OAuthLoginController.java
> +    private final LoginService kakaoLoginService;
두 개의 서비스를 할당하는 것보다 LoginSevice에서 oauthProviderName을 보고 각 oauthProvider에 맞게 로직을 실행하게 하는 게 좋지 않을까요?

2023-07-21 11:12 UTC, waterricecake commented on backend/src/main/java/hanglog/member/service/dto/GoogleUserInfoResponseDto.java
> +    private String picture;
역직렬화 할때 사용하고 있습니다. 이상하게 안먹히더라고요. 그래서 JsonProperty로 Json의 필드명을 잡아주었습니다.

2023-07-21 11:18 UTC, waterricecake commented on backend/src/main/java/hanglog/member/service/LoginService.java
> +    }
로그인시 아이디가 repo에 존재하면 로그인 아니면 회원가입 후 로그인으로 구현하였습니다.

2023-07-26 02:20 UTC, waterricecake commented on backend/src/main/java/hanglog/member/controller/OAuthLoginController.java
> +    private final LoginService kakaoLoginService;
@waterricecake
[refactor: OAuth 서비스 통일](https://github.com/woowacourse-teams/2023-hang-log/pull/39/commits/3ee85abfb84d8cf0bc16f157c87c1a8023ee1a82)

2023-07-26 02:23 UTC, hgo641 approved these changes
달리 2주간의 영혼이 잘 보이네요... 달리 고생고생고생하셨습니다... ㅠㅠ 👍👍👍👍👍

2023-07-26 02:25 UTC, merged