Feature/#3
woowacourse-teams/2023-hang-log pull request #4
Opened 2023-07-08 16:28 UTC by jjongwa

## 📄 Summary
> #3 
우선 전체적인 프로젝트 구조 설정과 Member를 제외한 기본 Entity와 Repository 생성 완료했습니다.

## 🙋🏻 More
> 아직 고칠게 많습니다..! 백엔드 팀원분들의 많은 관심과 리뷰가 필요합니다!

2023-07-10 05:31 UTC, mcodnjs requested changes
오 굿굿 주말에도 열일 하셨네요 👍
만나서 말씀드렸던 논의사항 아래에 적어놓았습니다!

- intellij 에서 final 설정
- 패키지 구조가 ERD 상에 있는 테이블 기준으로 만들어진 것 같은데 기능 위주로 바꿔보는건 어떨까요 ?? 
  - 저는 우선 trip / expense 이 정도로 가도 충분할 것 같긴한데 조금 더 논의해보죠! 아니면 우선 그냥 trip에 모두 넣고 나중에 구현하면서 분리해도 될 것 같아요!
  - 현재 `trip > domain > 기능 > repository`로 가는 패키지 구조도 조금 논의 해봤으면 좋겠어요

2023-07-10 05:36 UTC, hgo641 reviewed
디노... 도메인 코드 작성하시느라 고생하셨습니다!!! 최고!

2023-07-10 06:06 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/category/Category.java
> +@NoArgsConstructor
어이쿠 놓쳐버렸네요 레전드

2023-07-10 06:07 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/category/Category.java
> +    public Category(String name, Long googleApiId) {
변경했습니다! https://github.com/woowacourse-teams/2023-hang-log/pull/4/commits/ba1a04fab35f9e7546f8bb4de959098245d5c798

2023-07-10 06:16 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/expense/Expense.java
> +    private Item item;
뭔가 expense 도메인 쪽에서 시작하는 API가 있을 것 같다는 생각에 item의 하위로 두지 않았는데요,
생각해보니 expense에서 item을 가져와도 해당 아이템이 어떤 여행이고 누구의 것인지 보기 위해선 위쪽으로 참조를 계속 해 가야 할 것 같네요..
홍고 말씀대로 item의 하위로 두거나 양방향 참조 설정을 두는 쪽으로 변경해 보겠습니다!

2023-07-10 06:16 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/picture/Picture.java
> +package hanglog.trip.domain.picture;
회의 안건으로 한 번 넣어 보시죠..

2023-07-10 06:17 UTC, jjongwa commented on backend/src/main/resources/application.properties
> +logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
Thx.

2023-07-10 06:21 UTC, waterricecake reviewed
디노! 주말동안 열정이 넘치셨군요! 감사합니다

질문 있습니다. 각 entity에 equals와 hashcode를 정의 안하신 이유가 있나요?

2023-07-10 06:21 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/domain/expense/Expense.java
> +    private Item item;
<img width="669" alt="스크린샷 2023-07-10 오후 3 17 56" src="https://github.com/woowacourse-teams/2023-hang-log/assets/91263263/703e043a-44c8-425f-81de-c0c0ba7549cd">

table은 결국 expense, picture, place 3개를 계속 참조해야하니까 양방향 참조를 하던가 아니면 item이 
각 요소를 가지고 있는 것이 편리하지 않을까요?

2023-07-10 06:21 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/domain/item/Item.java
> +    private ItemType itemType;
👍

2023-07-10 06:33 UTC, LJW25 reviewed
너무 수고하셨습니다 디노!!

2023-07-10 06:33 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/domain/picture/Picture.java
> +package hanglog.trip.domain.picture;
저도 image가 더 적절한것같습니다! 변수명도 blobImg라 통일하는 편이 좋을것같아요.

2023-07-10 06:33 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/domain/category/Category.java
> +    private Long googleApiId;
googleApiId는 구글 API의 카테고리 id일까요? 제가 알기로 구글 place API의 경우 장소 유형과 장소 ID는 String인 것으로 알고있어서요 :)

2023-07-10 06:40 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/category/Category.java
> +    private Long googleApiId;
네 구글에서 제공하는 카테고리 id를 생각했습니다! 
뭐가 있을지 몰라서 일단 저것만 넣었는데 다 String이군요.. 변경하겠습니다!

2023-07-10 06:41 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/picture/Picture.java
> +package hanglog.trip.domain.picture;
달리와 홍고도 image가 좋다고 하네용 바로 변경하겠습니다~

2023-07-10 06:42 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/domain/category/Category.java
> +    private Long googleApiId;
Google Places API docs
[장소 유형](https://developers.google.com/maps/documentation/places/web-service/supported_types?hl=ko)
[장소 ID](https://developers.google.com/maps/documentation/places/web-service/place-id?hl=ko)

2023-07-10 06:48 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/picture/Picture.java
> +package hanglog.trip.domain.picture;
https://github.com/woowacourse-teams/2023-hang-log/pull/4/commits/3aedcbe0b1766f6c6d1caa05520e1355f4d72a6d

2023-07-10 06:58 UTC, hgo641 approved these changes

2023-07-11 05:19 UTC, mcodnjs approved these changes

2023-07-11 10:05 UTC, LJW25 approved these changes

2023-07-11 10:06 UTC, waterricecake approved these changes

2023-07-11 10:07 UTC, merged