비용 타입 변경 및 범위 제한 추가
woowacourse-teams/2023-hang-log pull request #403
Opened 2023-08-10 08:01 UTC by hgo641

## 📄 Summary
> #338 

Amount VO 생성
비용 범위 제한 (0이상 - 1억 이하)
비용 타입 변경 (double -> Amount)

## 🙋🏻 More
>

2023-08-10 11:53 UTC, jjongwa requested changes
갈비찜에 당첨된 홍고에게 
다음 음식 추천 받겠습니다.
추천 해줄때까지 approve 안 해줄꺼임

2023-08-10 11:53 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +public class Amount extends Number {
```suggestion
@Embeddable
@RequiredArgsConstructor
@ToString
@EqualsAndHashCode
@Getter
public class Amount extends Number {
```

요 친구들은 어떠신지

2023-08-10 11:53 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +        final BigDecimal augend = new BigDecimal(augendValue.toString());
Meaning of augend for the defined word.
문법적으로, 이 워드 "augend" 는 명사, 좀 더 구체적으로, 셀 수 있는 명사.

셀 수 있을 때만 더해준다 그런 건가요?

2023-08-10 11:53 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +
개인적으로 클래스와 같은 이름의 필드는 지양하는 편입니다. (바꾸라고 강요하는거 아님)

2023-08-10 11:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/domain/AmountTest.java
> +                .isEqualTo(3008);
```suggestion
       assertThatThrownBy(() -> new Amount(amountValue))
                .isInstanceOf(InvalidDomainException.class)
                .hasMessage(INVALID_EXPENSE_OVER_MAX.getMessage())
                .extracting("code")
                .isEqualTo(INVALID_EXPENSE_OVER_MAX.getCode());
```

요런식으로 ExceptionCode 가져와서 비교하는 건 어떤가요?

2023-08-10 11:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
> +    }
옹 이런거 처음봐

2023-08-10 11:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
> +        }
```suggestion
       dayLogs.stream()
                .filter(dayLog -> !trip.getDayLogs().contains(dayLog))
                .forEachOrdered(dayLog -> trip.getDayLogs().add(dayLog));
```

2023-08-10 11:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
> +    }
```suggestion
       items.stream()
                .filter(item -> !dayLog.getItems().contains(item))
                .forEachOrdered(item -> dayLog.getItems().add(item));
```

2023-08-10 11:53 UTC, jjongwa commented on backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
> +                List.of(new DayLogExpense(EXPENSE_LONDON_DAYLOG, new Amount(20000)))
new Amount(20000)을 상수화 시키는거 어떠신가요

2023-08-10 11:53 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
> +            new Amount(10000.0),
여기도 1L이나 new Amount 같은거 하나로 묶어보면 어떨까 싶은데 투머치 같으면 그냥 무시하십쇼

2023-08-10 14:39 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +public class Amount extends Number {
오버라이딩해서 커스텀 equals, toString만들었는데 명시적으로 어노테이션이 붙여져있는게 좋아서 그러시는건가요?

2023-08-10 14:43 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +
헷갈릴수도 있겠네요! value로 변경할까요?

2023-08-10 14:47 UTC, hgo641 commented on backend/src/test/java/hanglog/expense/domain/AmountTest.java
> +                .isEqualTo(3008);
좋아요
다른 테스트에서 사용한 방식이랑 통일한건데... 한 번에 고치는 게 낫겠네요
`TripServiceTest`, `CurrencyServiceTest`, `ImageFileTest`

2023-08-10 14:48 UTC, hgo641 commented on backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
> +    }
양쪽 엔티티에 바로 연관관계 지어주면 에러나서 static메소드로 뺐는데... 다른 해결방법은 모르겠어요 ㅠ
좋은 방법 아시면 추천 부탁

2023-08-10 17:30 UTC, mcodnjs reviewed
테스트 쪽은 아직 못봐서 내일 조금 더 볼게요 .. ! 
많은 고민의 흔적이 느껴지는 코드였습니다 ㅎㅎ 👍

2023-08-10 17:30 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +        final BigDecimal augend = new BigDecimal(augendValue.toString());
잘 모르지만 더하는 값을 가수라고 한다는데 이를 영어로 `addend` 라고 한대요!
근데 현재 로직 상 저 값은 피가수가 아닌 가수로 보여져서 `addend`도 좋은거 같아요! (아님 말고 ㅎㅎ .. )

> augend(피가수) + addend(가수)
(`augend`가 `addend`로 구분 없이 불리기도 하는거 같아요)

2023-08-10 17:30 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +
add, multiply, divide 함수도 파라미터가 그냥 value 이면 어떨까 하는 의견이 있는데 ㅎㅎ ... 
둘다 value는 조금 헷갈릴거 같고 .. (저도 강요 아님)

2023-08-10 17:30 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +public class Amount extends Number {
number 상속 받은 이유가 연산할 때 Number 를 상속받은 어떤 타입이든 받을 수 있게 하려고 인가용 ?!

2023-08-10 17:30 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
> +        if (totalAmount.equals(new Amount(0))) {
`new Amount(0)`이 많이 사용되서 `Amount.zero()`로 정팩메 만들어도 좋을듯 ~~ (그냥의견)
혹은 BigDecimal 처럼 상수로 .. !

2023-08-10 17:35 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +public class Amount extends Number {
@mcodnjs 맞습니다 산술연산할 때 Amount 바로 받고 싶어서 Number 상속받았습니다

2023-08-10 17:37 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +        final BigDecimal augend = new BigDecimal(augendValue.toString());
addend가 더 직관적이네요 ㅎㅎ 바꾸겠습니다

2023-08-10 17:37 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +
말씀하신것처럼 둘 다 value는 헷갈릴 것 같습니다 ㅎㅎ 함수 인자는 그대로 가려는 데 괜찮나요?

2023-08-10 17:52 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
> +        if (totalAmount.equals(new Amount(0))) {
@mcodnjs 
맞아 이걸 얘기를 안했네요...

처음에 상수로 뺐었는데 (`public static final Amount ZERO = new Amount(0);`)
얘가 public 필드라 코드 스타일을 적용하면 private 필드 상단에 배치가 됩니다.

그래서 Amount의 필드 중 가장 먼저 초기화가 되는데, `new Amount(0)`을 실행하는 시점에서 예외가 발생합니다.
* 생성자 내부의 `validateAmount()`로직을 호출하면서 , 이 시점에서는 `Amount`의 private변수인 `MAX_AMOUNT`와 `MIN_AMOUNT`가 초기화 되지 않아 `amount.compareTo(MIN_AMOUNT)` 부분에서 NPE 발생

해결하는 방법은 두 가지가 떠올랐는데,
1. ZERO가 public 필드이긴 하지만 private필드인 `MAX_AMOUNT`와 `MIN_AMOUNT` 아래에 배치시킨다.
2. `MAX_AMOUNT`와 `MIN_AMOUNT`를 `validateAmount`내부의 변수로 변경한다. (validateAmount 호출시 바로 사용이 가능하게)

둘 다 맘에 안들어서 보류했습니다ㅠㅠ 어떤 걸로 할까요? 아니면 다른 방법 추천있으신가요!!

2023-08-11 03:12 UTC, LJW25 reviewed
어마어마한 수정사항..! 홍고생하셨습니다. 🍊
다른분들이 리뷰 많이 남겨주셔서 저는 간단한거 하나만 남겼어요!

2023-08-11 03:12 UTC, LJW25 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +    }
@EqualsAndHashCode, @ToString 어노테이션과는 별도인가요?
제가 로컬에서 돌리니 중복이라고 warning이 떠서 물어봅니당.
```
 /Users/user/HangLog/2023-hang-log/backend/src/main/java/hanglog/expense/domain/Amount.java:19: warning: Not generating equals and hashCode: A method with one of those names already exists. (Either both or none of these methods will be generated).
@EqualsAndHashCode

/Users/user/HangLog/2023-hang-log/backend/src/main/java/hanglog/expense/domain/Amount.java:20: warning: Not generating toString(): A method with that name already exists
@ToString
```

2023-08-11 03:18 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +    }
오버라이딩해서 어노테이션이 필요없긴한데 디노가 붙여달래서 일단은 붙였습니다? ? ?

2023-08-11 05:49 UTC, waterricecake reviewed
고생하셨습니다!
개인적인 생각인데 ExpenseRequest dto에서도 최대가격 1억 잡아주는건 어떤가요?

2023-08-11 05:49 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
> +        if (totalAmount.equals(new Amount(0))) {
```java
public final class Integer extends Number
        implements Comparable<Integer>, Constable, ConstantDesc {
    /**
     * A constant holding the minimum value an {@code int} can
     * have, -2<sup>31</sup>.
     */
    @Native public static final int   MIN_VALUE = 0x80000000;

    /**
     * A constant holding the maximum value an {@code int} can
     * have, 2<sup>31</sup>-1.
     */
    @Native public static final int   MAX_VALUE = 0x7fffffff;
```

 `Integer`의 `MAX_NUMBER`인데 `@Native`를 통해 메소드에서 써서 1. 방법? 나쁘지 않을지도?

2023-08-11 05:49 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +    }
개인적으로 오버라이딩한 부분을 빼도 되지 않나요? 어노테이션으로 충분? 어노테이션보다 오버라이딩을 쓴 이유는 무엇인가요?

2023-08-11 05:49 UTC, waterricecake commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    INVALID_EXPENSE_UNDER_MIN(3009, "금액이 최솟값보다 작습니다."),
최댓값 최솟값 써주는거 어떨까요?
"금액이 1억보다 클 수 없습니다."
"금액이 0보다 작을 수 없습니다."

2023-08-11 08:16 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
> +        if (totalAmount.equals(new Amount(0))) {
오 `@Native`... 신기

2023-08-11 08:16 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +    }
@waterricecake 값객체가 객체 주소값으로 동등성 비교를 하면 어색할 것 같아서요!

2023-08-11 12:52 UTC, hgo641 commented on backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
> +        }
e50f296e8e485bd2aecf1c71706a585cfb8f8f5a

2023-08-11 12:52 UTC, hgo641 commented on backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
> +    }
e50f296e8e485bd2aecf1c71706a585cfb8f8f5a

2023-08-11 12:53 UTC, hgo641 commented on backend/src/test/java/hanglog/expense/presentation/ExpenseControllerTest.java
> +                List.of(new DayLogExpense(EXPENSE_LONDON_DAYLOG, new Amount(20000)))
ca19f9d4bf13c0649e4756ecd553c6bb778a4459

2023-08-11 12:53 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/fixture/ExpenseFixture.java
> +            new Amount(10000.0),
ca19f9d4bf13c0649e4756ecd553c6bb778a4459

2023-08-11 12:54 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/CategoryExpense.java
> +        if (totalAmount.equals(new Amount(0))) {
validateAmount 메소드가 Item쪽으로 이동하게 되어서...ㅎㅎ public static final 상수로 만들었습니다

a98984fb318d2d607d457b04b0536bb5ce30c3be

2023-08-11 12:55 UTC, hgo641 commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    INVALID_EXPENSE_UNDER_MIN(3009, "금액이 최솟값보다 작습니다."),
147104968653e7902ec593d02d5f8215a5f0fcb9

2023-08-11 13:13 UTC, LJW25 commented on backend/src/main/java/hanglog/expense/domain/Amount.java
> +    }
둘중에 안쓰이는걸 빼는게 좋지 않을까요? 하는 개인적인 생각생각

2023-08-12 14:11 UTC, LJW25 approved these changes

2023-08-13 06:30 UTC, waterricecake approved these changes

2023-08-13 07:26 UTC, merged