RefreshToken, AccessToken 이용한 로그인 기능 구현
woowacourse-teams/2023-hang-log pull request #404
Opened 2023-08-10 10:48 UTC by jjongwa

## 📄 Summary
> 만들다 보니까 작업 단위가 너무 커지는 것 같아 우선 여기서 끊어가겠습니다.
서비스랑 컨트롤러 테스트도 좀 짜보려 했는데 머리아파서 일단 멈췄습니다.
이거 끝나면 각 요청에서 토큰 유효성 검증하고 멤버 id값 뽑아내는 기능 넣어야 되는데 이건 다른 사람들 추가 기능 구현 작업 안할때 마지막으로 해야할듯..?

## 🙋🏻 More
> jwtProvider 테스트는 여차저차 했는데 서비스부터 답이 없어요 어떻게 짜요짜요 난 모르겠어 아돈노

2023-08-10 16:41 UTC, jjongwa commented on backend/src/test/java/hanglog/member/presentation/AuthControllerTest.java
> +
ㅇㄴ 
다음 커밋때 then 추가하겠음

2023-08-10 19:24 UTC, mcodnjs requested changes
어려워어려워어려워!
이 어려운 로그인을 해내느라 고생하셨씁니다! 🦖

2023-08-10 19:24 UTC, mcodnjs commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +        final Cookie cookie = new Cookie("refresh-token", memberTokens.getRefreshToken());
사실 여기서는 AccessToken만 받아오는 거겠쥐 .. ?

2023-08-10 19:34 UTC, hgo641 approved these changes
역시 디노 코드가 굉장히 깔꼼하네요
테스트 짱 꼼꼼해요 고생하셨습니다

2023-08-10 19:34 UTC, hgo641 commented on backend/src/main/java/hanglog/member/service/AuthService.java
> +        final Member member = findOrCreateMember(userInfo.getId(), userInfo.getNickname(), userInfo.getImageUrl());
`userInfo.getSocialLoginId()` 어떠신가요?
아니면 `UserInfo` 이름 자체를 `SocialLoginUserInfo`...

2023-08-10 19:34 UTC, hgo641 commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +    }
private 메소드 아래에 두는 거 어떠세요

2023-08-10 19:34 UTC, hgo641 commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +        final String refreshToken = makeTestJwt(SAMPLE_EXPIRATION_TIME, SAMPLE_SUBJECT, SAMPLE_SECRET_KEY);
`SAMPLE_SECRET_KEY`가 잘못된 key인거 맞죠? 
`WRONG_SECRET_KEY` 나 `INVALID_SECRET_KEY`어떤신가요
다른 상수들이랑 이름 통일하고 싶으시면 SAMPLE- 하셔도 괜찮습니당

2023-08-10 19:34 UTC, hgo641 commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +    private String realSecretKey;
진짜 비밀 열쇠

2023-08-10 19:34 UTC, hgo641 commented on backend/src/test/java/hanglog/member/presentation/AuthControllerTest.java
> +        final AccessTokenResponse expectResponse = new AccessTokenResponse(memberTokens.getAccessToken());
expected 어떤가요?

2023-08-11 05:11 UTC, waterricecake reviewed
어렵네요;;;; 고생하셨어요 다이노

2023-08-11 05:11 UTC, waterricecake commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
```suggestion
    private TokenState validateToken(final String token){
        try{
            Jwts.parserBuilder()
                    .setSigningKey(secretKey)
                    .build()
                    .parseClaimsJws(token);
        } catch (final ExpiredJwtException e) {
            return TokenState.EXPIRED;
        } catch (final JwtException | IllegalArgumentException e) {
            return TokenState.INVALID;
        }
        return VALID;
    }
```
토큰이 유효한지, 기간이 만료가 되었는지에 따라 enum을 만들어서 반환하고 이에따라 로직을 돌리면 어떨까요? 그러면 밑에 accesstoken 재발급에서도 try catch 보다 직관적으로 보여줄 수 있을것 같은데
```
public MemberTokens regenerateAccessToken(final String refreshToken, final String accessToken) {
        validateRefreshToken(refreshToken);
        final TokenState tokenState = validateToken(accessToken);
        if (tokenState == VALID) {
            return new MemberTokens(refreshToken, accessToken);
        }
        if (tokenState == INVALID) {
            throw new InvalidJwtException(INVALID_ACCESS_TOKEN);
        }
        final String subject = getSubject(accessToken);
        final String renewalAccessToken = createToken(subject, accessExpirationTime);
        return new MemberTokens(refreshToken, renewalAccessToken);
    }
    ```

2023-08-11 05:11 UTC, waterricecake commented on backend/src/main/java/hanglog/member/dto/AccessTokenResponse.java
> +    private String accessToken;
`NoArgsConstructor` 때문에 아닐까요?

2023-08-11 06:20 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +            HttpServletResponse response
response.addCookie 있어서 안붙였는데 final 붙여도 경고 안띄우네요..!

2023-08-11 06:20 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +            @RequestParam final LoginRequest loginRequest,
아차차

2023-08-11 06:20 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +    public ResponseEntity<AccessTokenResponse> extendLogin(
로그인 연장이요

2023-08-11 06:21 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +            HttpServletResponse response
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/6fe314e469802bd16d07182536cd69fc1e334abc

2023-08-11 06:21 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +            @RequestParam final LoginRequest loginRequest,
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/6fe314e469802bd16d07182536cd69fc1e334abc

2023-08-11 06:25 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +        } catch (JwtException | IllegalArgumentException e) {
레전드

2023-08-11 06:36 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    private String createToken(final String subject, final Long validityInMilliseconds) {
subject는 말 그대로 주제를 의미하는데 이 토큰이 어떤 유저를 나타내는데 주로 사용된다고 하네요. setPayload도 있는데 setSubject나 setPayload나 둘 다 jwt의 Patload 부분에 포함됩니다.

둘 중 어느 방법을 써도 상관 없는데 setSubject를 쓰면 나중에 토큰을 decrypt해서 getSubjcet 하고 LongValue로 바꾸기만 하면 되서 id값을 반환하기 쉽기도 하고,
다른 이유도 있는데 이건 보안상 직접 말씀드리겠습니다.

2023-08-11 06:39 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    private String createToken(final String subject, final Long validityInMilliseconds) {
jwt 생성할 때 expirationTime을 밀리초 기준으로 설정할 수 있는데, 
현재 코드 구조 상에서 기준이 밀리초라는 걸 알 수가 없기 때문에 
다른 팀원들이 보고 쉽게 파악할 수 있지 않을까 하는 생각이었는데 투머치면 바꾸겠습니다.

2023-08-11 06:47 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +                .setAllowedClockSkewSeconds(refreshExpirationTime)
와 큰일날 뻔 했네 맞아요 refreshToken 유효기간 넣으면 안됩니다.
-> 60초로 재설정

2023-08-11 06:55 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +                .setAllowedClockSkewSeconds(refreshExpirationTime)
아니다 아까 적은거 아님

2023-08-11 07:03 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
`사용자는 refreshToken의 만료주기마다 한번씩 다시 로그인하는 과정이 필요하다.
(ex. refreshToken의 만료일자가 1달이라면, 한달에 한번씩 꼭 다시 로그인해야 한다.)`
이 정책을 생각하긴 했습니다..!

2023-08-11 07:05 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
제안해 주신거 잘 봤습니다.
반영 안하겠습니다.

2023-08-11 07:05 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/Member.java
> +    private String refreshToken;
이 부분 슬링키와 얘기해 봤는데, 
어짜피 이후에 바뀔 것 같아서 어느 방식을 써도 상관 없을 것 같습니다.
분리할까요..?

2023-08-11 07:06 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
아아아 농담이고 달리도 비슷한 코멘트 남겼던데 
두 가지 다 고려해보고 좀 더 이쁘게 변경해 보도록 하겠습니다.!

2023-08-11 07:07 UTC, jjongwa commented on backend/src/main/java/hanglog/member/dto/MemberTokens.java
> +public class MemberTokens {
아 그러네요 만들고 중간에 쓰임새가 변경되었는데 지금은 도메인에 가까운 것 같습니다.
Tokens는 ... 고려해 보겠습니다.

2023-08-11 07:10 UTC, jjongwa commented on backend/src/main/java/hanglog/member/service/AuthService.java
> +    public void removeMemberRefreshToken(final String refreshToken, final String accessToken) {
member가 가지고 있는 refresh토큰 정보를 삭제한다는 의미로 사용하긴 했는데
member 네이밍 부분은 전체적으로 재검토 해보겠습니다.!

2023-08-11 07:18 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +        final Cookie cookie = new Cookie("refresh-token", memberTokens.getRefreshToken());
아 맞네;

2023-08-11 07:19 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +        final Cookie cookie = new Cookie("refresh-token", memberTokens.getRefreshToken());
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/a0762a088e2f1d597870184dfab260daa2cfdc4b

2023-08-11 07:23 UTC, jjongwa commented on backend/src/main/java/hanglog/member/dto/AccessTokenResponse.java
> +    private String accessToken;
ControllerTest에서 objectMapper로 만드는데 NoArgsConstructor가 필요해서 그렇게 됐습니다 ..

2023-08-11 07:25 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +    }
굿

2023-08-11 07:25 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +            HttpServletResponse response
아이쿠 파이널 와이리 많니

2023-08-11 07:26 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +            HttpServletResponse response
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/02e92870937653fae560c3ddae24bea794fffb8d

2023-08-11 07:26 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +    }
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/02e92870937653fae560c3ddae24bea794fffb8d

2023-08-11 07:26 UTC, jjongwa commented on backend/src/main/java/hanglog/global/exception/ExceptionCode.java
> +    NOT_FOUND_MEMBER(1010, "요청한 ID에 해당하는 멤버가 존재하지 않습니다."),
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/02e92870937653fae560c3ddae24bea794fffb8d

2023-08-11 07:32 UTC, jjongwa commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +    }
어어 저 tripControllerTest 짤 때도 위쪽에다 올리긴 했는데.. 
다른 분들이 그렇게 했다면 따라 가겠습니다.

2023-08-11 07:33 UTC, jjongwa commented on backend/src/main/java/hanglog/member/service/AuthService.java
> +        final Member member = findOrCreateMember(userInfo.getId(), userInfo.getNickname(), userInfo.getImageUrl());
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/b6f0b1f8a2747c404af0ec3096b62de7a33daeb2

2023-08-11 07:35 UTC, jjongwa commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +    private String realSecretKey;
시크릿-키

2023-08-11 07:36 UTC, jjongwa commented on backend/src/test/java/hanglog/member/presentation/AuthControllerTest.java
> +        final AccessTokenResponse expectResponse = new AccessTokenResponse(memberTokens.getAccessToken());
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/20472efa4c7ccfee0292b1437e7004bd22c3b883

2023-08-11 07:37 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +        final String accessToken = createToken(subject, accessExpirationTime);
accessToken의 기간을 짧게 두는 이유가 안에 든 내용을 탈취할 가능성을 줄이기 위해서인데 기간을 길게 두는 refreshToken에도 id를 넣어버리면 의미가 없어지게 됩니다.

2023-08-11 07:41 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
suggested는 parseToken인데 validateToken 메서드 넣어져 있고 
또 밑에 있는 코드는 regenerateAccessToken 이 나와 있어서 어디를 어떻게 제안하는지 잘 모르겠어요.
enum을 만들어서 반환하는게 어떻냐는 아이디어만 파악 가능함

2023-08-11 08:17 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
```
public MemberTokens regenerateAccessToken(final String refreshToken, final String accessToken) {
        validateRefreshToken(refreshToken);
        if (isTokenExpired(accessToken)) {
            final String subject = getSubject(accessToken);
            final String renewalAccessToken = createToken(subject, accessExpirationTime);
            return new MemberTokens(refreshToken, renewalAccessToken);
        }
        throw new InvalidJwtException(INVALID_ACCESS_TOKEN);
    }

    private boolean isTokenExpired(final String accessToken) {
        try {
            validateAccessToken(accessToken);
        } catch (final ExpiredPeriodJwtException e) {
            return true;
        }
        return false;
    }
```

이런 식으로 변경되는데 음 잘 모르겠어요 ...

2023-08-11 09:45 UTC, waterricecake commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
parseToken 대신에 enum으로 관리해보자는 의미였는데 잘 안보였군요. try catch에서 예외를 던지지말고 그 예외마다 해당 token의 상태를 의미하는 enum 반환해서 각 메서드에서 예외처리를 하자라는 의미였습니다.

2023-08-11 13:11 UTC, LJW25 approved these changes
안녕하세요 디노.
제가 리뷰를 하는 사이에도 업데이트가 되는걸 보고 서둘러 submit 합니다.
사실 제가 늦게보는 바람에 로직 관련해선 다른분들이 남겨주신것도 충분해 보였음.
컨벤션 관련해서만 좀 추가했어요.
수고하셨습니다!

2023-08-11 13:11 UTC, LJW25 commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +        final MemberTokens memberTokens = new MemberTokens(refreshToken, accessToken);
다른 테스트들에서는 개행 없는 것 같은데 여기도 개행 없이 가는거 어떤가요

2023-08-11 13:11 UTC, LJW25 commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +        });
진짜 잘 모르겠어서 여쭤보는건데 아래처럼 `softly.` 안붙여도 soft 적용 되나요? 예시코드는 ItemServiceTest에서 가져옴.
```
        // then
        assertSoftly(softly -> {
            softly.assertThat(items.get(0)).usingRecursiveComparison()
                    .isEqualTo(ItemResponse.of(ItemFixture.LONDON_EYE_ITEM));
            softly.assertThat(items.get(1)).usingRecursiveComparison()
                    .isEqualTo(ItemResponse.of(ItemFixture.TAXI_ITEM));
        });
```

2023-08-11 13:11 UTC, LJW25 commented on backend/src/test/java/hanglog/member/presentation/AuthControllerTest.java
> +        );
`//when` 실종사건

2023-08-11 13:15 UTC, jjongwa commented on backend/src/test/java/hanglog/member/presentation/AuthControllerTest.java
> +        );
눈이 침침한가.. 저거 보고 붙인줄..허허허허허
<img width="548" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/77482065/508c987c-890d-4b00-9de1-6622479c0f57">

2023-08-11 13:16 UTC, LJW25 commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +        });
업데이트되면서 없어진것같으니 패스해주십쇼

2023-08-11 13:16 UTC, jjongwa commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +        });
soft가 적용된다는게 에러 발생 시 해당 라인에서 터졌다는걸 알려주는지 인가요?
솔직히 말하겠습니다. 잘 모르겠어요.
그냥 돌아가길래 뺌


-> 근데 테스트 변경 후 다 사라졌습니다..!

2023-08-11 13:17 UTC, jjongwa commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +        final MemberTokens memberTokens = new MemberTokens(refreshToken, accessToken);
아차차

2023-08-11 13:18 UTC, jjongwa commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/auth-controller-test/logout/http-response.adoc[]
근데 아직 끝나지 않았습니다..
응답에 쿠키도 준다는 정보를 포함하고 싶은데 gpt가 알려준대로 해도 안되고 검색해도 잘 안나오네요..
restDocs 장인 이오의 도움이 필요합니다..

2023-08-11 13:19 UTC, jjongwa commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +        final MemberTokens memberTokens = new MemberTokens(refreshToken, accessToken);
https://github.com/woowacourse-teams/2023-hang-log/pull/404/commits/ec29d97f50bd6a2cd8c564b1c2ce96f4b945fd30

2023-08-11 13:31 UTC, LJW25 commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +    }
근데 뒤늦게 든 생각: 저희 Post 요청에는 201 created로 응답하기로 정했었는데 인증인가쪽 api는 예외인가요?

2023-08-11 13:34 UTC, LJW25 commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/auth-controller-test/logout/http-response.adoc[]
restdocs 쿠키는 springboot 3.0부터 지원하기 때문에 무료버전 gpt는 알려주지 않습니다. 걔가 알려주는거 다 구라임. 
저도 쿠키는 적용 안해봤는데 나중에 시도해보겠습니다.

2023-08-11 14:03 UTC, jjongwa commented on backend/src/main/java/hanglog/auth/domain/RefreshToken.java
> +}
질문 들어올까봐 미리 적어놓겠습니다.

이렇게 짠 이유

보통 refreshToken은 Redis에 key-value 형태로 저장한다.
근데 전 Redis 써본적 없어서 일단 RDB에 저장하도록 만들었습니다.
하지만 RDB에다 저장해 놓으면 당연히 성능상 속도가 떨어지겠죠
그래서 일단 id를 따로 안만들고 token을 인덱스로 사용하도록 설정해 놓았습니다.

member 참조 안하고 그냥 Long memberId로 해놓은 이유도 멤버와의 연관을 일부러 주지 않기 위한 의도입니다.

이런식으로 만들어 놓으면 Redis로 전환할 때, 의존성 추가하고 어노테이션만 달아주면 끝나요.

예상안:
```
@RedisHash(value = "refreshToken", timeToLive = 60)
public class RefreshToken {

    @Id
    private String refreshToken;

    private Long memberId;
}
```

그럼 왜 지금 굳이 refreshToken을 적용시켰냐?

RDB에 refreshToken을 넣어 놓음으로서 생기는 성능 저하보다
사용자의 로그인 편의성을 챙기는게 조금 더 낫다고 판단했습니다.



그래~~~~~서

Redis로 전환은 레벨 4때 기능 고도화 과정에서 가장 우선적으로 진행하고 싶습니다. (내가 하고싶다는 뜻)

2023-08-11 14:35 UTC, mcodnjs commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    }
아아 ..

2023-08-11 14:35 UTC, mcodnjs commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +    public ResponseEntity<AccessTokenResponse> extendLogin(
아아아!

2023-08-11 14:35 UTC, mcodnjs commented on backend/src/test/java/hanglog/member/domain/auth/JwtProviderTest.java
> +    }
저는 보통 public에서 쓰이는 private 메소드들은 해당 public 메소드 바로 아래 배치하는 편 ~

2023-08-11 14:36 UTC, mcodnjs approved these changes

2023-08-11 15:11 UTC, jjongwa commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/auth-controller-test/logout/http-response.adoc[]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

그래도 이제 springboot 3.1 쓰는 자그마한 이유가 생겼네요 ..! 괜찮을지도..?

2023-08-11 15:17 UTC, jjongwa commented on backend/src/main/java/hanglog/member/presentation/AuthController.java
> +    }
어우야 원래 get이었다가 post로 변경됐는데 미처 생각을 못했네요

2023-08-12 07:37 UTC, jjongwa commented on backend/src/main/java/hanglog/member/domain/auth/JwtProvider.java
> +    private String createToken(final String subject, final Long validityInMilliseconds) {
전 네이밍 못해서 ...
expirationMiiliSeconds으로 바꾸겠습니다..

2023-08-12 07:57 UTC, waterricecake approved these changes

2023-08-12 11:00 UTC, merged