공유기능 구현
woowacourse-teams/2023-hang-log pull request #405
Opened 2023-08-10 14:03 UTC by Dahyeeee

## 📄 Summary
뭔가 마음에 안드는데 피드백받고 차차 리팩토링 해볼게유
url은 일단 baseUrl을 가져와서 쓰고 있는데 맞나?? 로컬에서도 배포에서도 되야하니까..

아 애슐리가 토글 디자인시스템에 만들어달라고했눈데~~ 저는 디자인시스템 배포를 못해서 일단 여기하고 옮겨놓도록 하겠습니당~~ 
## 🙋🏻 More
>

2023-08-11 05:19 UTC, ashleysyheo requested changes
🔥

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripButtons/TripButtons.tsx
> +      <TripShareButton tripId={tripId} sharedStatus={sharedStatus} />
<img width="861" alt="Screenshot 2023-08-11 at 2 01 02 PM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/85426de7-d665-4b5f-b3a3-e7124efdcf45">

공유 버튼 위치가 이상해졌어요!

원래 스타일
<img width="864" alt="Screenshot 2023-08-11 at 2 04 22 PM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/d7646b8a-0c01-4fcc-9219-adab4707c6a8">

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +      communicateWithServer(sharedStatus);
useEffect에 안 넣고   useTripShareStatusMutation에서 invalidateQueries를 한 다음에 데이터를 재패칭하면 되지 않을까요?

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/hooks/api/useTripShareStatusMutation.ts
> +  const tripMutation = useMutation({
tripShareStatusMutation

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +  const patchTripSharedStatus = useTripShareStatusMutation();
tripShareStatusMutation ?? 

patchTripSharedStatus는 직접적 api요청을 날리는 걸 의미하는 것 같은데요.

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +      communicateWithServer(sharedStatus);
단일 여행 조회할 때도 shareCode(?) 내려준다고 했어요

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +      .catch(() => {
try catch?!

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +  const handleCopyButtonClick = () => {
커스텀 훅으로 분리하면 좋을 것 같아요

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +          setShareUrl(BASE_URL + PATH.SHARE(sharedCode));
<img width="299" alt="Screenshot 2023-08-11 at 2 05 44 PM" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/e61731f3-3927-4cfe-9f41-1807ef684a4f">

path가 조금 이상해요

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +  width: '45%',
width percentage로 설정 안 했으면 좋겠어요! 지금 복사 버튼이 너무 많은 공간을 차지해요.

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +  padding: '8px 4px',
8px 16px + Theme 사용하기

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +  backgroundColor: Theme.color.white,
css 순서?

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +  backgroundColor: Theme.color.gray100,
css 순서

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +    backgroundColor: Theme.color.blue600,
css 순서!

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +    content: '""',
그냥 `content: ''` 해도 되지 않아요??

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +  borderRadius: '16px',
Theme에 있는 값 사용하기

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/hooks/api/useTripShareStatusMutation.ts
> +
낙관적 업데이트를 적용해도 좋을 것 같아요. 이런 마이너(?)한 인터랙션은 서버 요청을 보내고 또 기다리고 하는 것 보다 바로 즉각적으로 사용자한테 알려줘도 좋지 않을까요?

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/mocks/data/trip.ts
> +  sharedStatus: true,
sharesStatus를 단일 여행 조회할 때 안 내려주고 `"sharedCode": "xxxxxxx",`만 내려준대요. 만약 공유된 상태면 값이 있고, 아니면 `null`로 와요. 명세 한 번 더 확인해주세요!!

2023-08-11 05:19 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +            message: '공유 url이 클립보드에 복사되었습니다.',
공유 링크가 클립보드에 복사되었습니다.

2023-08-11 05:25 UTC, ashleysyheo commented
스위치 버튼 디자인 시스템에 올려주세요!

2023-08-11 06:13 UTC, Dahyeeee commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +  const patchTripSharedStatus = useTripShareStatusMutation();
오 왜그랬지? 자면서했나??

2023-08-11 06:13 UTC, Dahyeeee commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +      communicateWithServer(sharedStatus);
!!!!!

2023-08-11 06:19 UTC, Dahyeeee commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +    content: '""',
저도 처음에 그렇게 햇는데 오류나더라구요?! 그래서 넣어줬어용

2023-08-11 06:48 UTC, Dahyeeee commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +      .catch(() => {
복사가 실패하는 일이 있을 수 있다고 하더라구여? 유저가 클립보들 사용을 막아놓았거나, 브라우저가 navigtor.clipboard를 지원하지 않을 수 있는 경우 인데~~ 
고려하지 말까여? ㅋㅋㅋㅋㅋ

2023-08-11 07:00 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +      .catch(() => {
아 체이닝말고 try catch로 할 수 없나 해서요....ㅋㅋㅋ 조금 더 깔끔

2023-08-11 07:00 UTC, ashleysyheo commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.style.ts
> +    content: '""',
오 그렇군요!!!! 신기함

2023-08-11 07:01 UTC, ashleysyheo commented on frontend/src/hooks/api/useTripShareStatusMutation.ts
> +
마이 베드... ㅋㅋㅋㅋ shareCode를 받아와야 하는데........

2023-08-11 07:08 UTC, Dahyeeee commented on frontend/src/components/common/TripInformation/TripShareButton/TripShareButton.tsx
> +      .catch(() => {
아! 오키!!

2023-08-11 08:41 UTC, ashleysyheo approved these changes
💯💯💯

링크 복사 버튼 스타일 제가 수정했어요! 

`npm run lint`해서 임포트 순서 한 번만 더 확인해주세요!!

2023-08-12 05:47 UTC, dladncks1217 approved these changes
좋습니다 좋습니다👍👍

2023-08-12 05:47 UTC, dladncks1217 commented on frontend/src/hooks/api/useTripShareStatusMutation.ts
> +          message: '여행 공유 설정 변경에 실패했습니다. 잠시 후 다시 시도해주세요.',
이거 상수로 빼도 괜찮을듯?!

2023-08-12 05:47 UTC, dladncks1217 commented on frontend/src/hooks/trip/useTripShare.ts
> +          message: '복사에 실패했습니다. 브라우저 상태를 확인 후 다시 시도해주세요.',
메시지들 상수화 어떤가요?!

2023-08-12 11:31 UTC, merged