#16 Trip 수정 및 삭제 API 구현
woowacourse-teams/2023-hang-log pull request #42
Opened 2023-07-13 09:49 UTC by jjongwa

## 📄 Summary
> #16 

## 🙋🏻 More
>

2023-07-13 12:41 UTC, hgo641 reviewed
고생많으셨습니다 Dino~ ~

2023-07-13 12:41 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +        this(id, title, startDate, endDate, description, USABLE);
BaseEntity의 status필드에서 이미 USABLE로 초기화되어있으니까 생성자에서 초기화 안해도되지않을까요? 근데 이 생성자에서 USABLE빼면 this()로 할당은 못하겠네요 ㅎㅎ...

2023-07-13 12:41 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/dto/request/TripUpdateRequest.java
> +    private final String title;
size validation 추가 어떠세요

2023-07-13 12:41 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/dto/request/TripUpdateRequest.java
> +    private final String description;
size ditto

2023-07-13 12:41 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        );
아... 근데 DELETED 하나 정도는 setter로 jpa 변경감지 이용하는 게 더 편할 것 같기도 하고?... 별로에요? ㅇㅋ

2023-07-13 12:41 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        if (target.getStatus().equals(DELETED)) {
target.isDeleted() 만드는 거 어때요?  BaseEntity에 메소드 추가

2023-07-13 12:41 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +        );
request fixture로 분리할 타이밍?

2023-07-13 13:04 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +        this(id, title, startDate, endDate, description, USABLE);
맞아요 this로 만들까 각각 따로 할당할까 고민하다가 this를 사용했습니다.. 다른 분들도 의견 남겨 주시면 감사하겠습니다..!

2023-07-13 13:06 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/dto/request/TripUpdateRequest.java
> +    private final String title;
레전드

2023-07-13 13:06 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/dto/request/TripUpdateRequest.java
> +    private final String description;
레레전드

2023-07-13 13:23 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        );
아무래도 setter는 어색하긴 한데.. 조금 더 인사이트를 얻고 고민해 보겠습니닷

2023-07-13 13:26 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +        );
아 이게 잘 보시면 아래 것들은 필드가 하나씩 Null 이 들어가 있어서 생각보다 겹치는게 없더라구요.. 그래도 Fixture 만들어 놓는게 나으려나요..? 고민고민

2023-07-13 13:39 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        if (target.getStatus().equals(DELETED)) {
https://github.com/woowacourse-teams/2023-hang-log/pull/42/commits/a46407eff79843adf0e6285055cd62e67c5a23af

2023-07-14 04:11 UTC, mcodnjs requested changes
아자아자 파이팅
디로 파이팅

2023-07-14 04:11 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/presentation/TripController.java
> +            @PathVariable Long tripId,
찾았다 final

2023-07-14 04:11 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +                        .content(objectMapper.writeValueAsString(updateRequest)))
메소드 분리 할 수 있을지도?

```
    private ResultActions updateTripApi(final TripUpdateRequest updateRequest, final Long tripId) throws Exception {
        return mockMvc.perform(put("/trips/" + tripId)
                .contentType(APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(updateRequest)));
    }
```

2023-07-14 04:33 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +                        .content(objectMapper.writeValueAsString(updateRequest)))
https://github.com/woowacourse-teams/2023-hang-log/pull/42/commits/431d04c76e384c38b74839d0b9669445f752282f

분리해 봤는데 괜찮은가 함 봐주세요

2023-07-14 04:33 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/TripController.java
> +            @PathVariable Long tripId,
이걸 찾네

2023-07-14 04:33 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/TripController.java
> +            @PathVariable Long tripId,
https://github.com/woowacourse-teams/2023-hang-log/pull/42/commits/431d04c76e384c38b74839d0b9669445f752282f

2023-07-14 05:14 UTC, LJW25 reviewed
수고하셨습니다 디노
넘 잘하셔서 리뷰할게 없네여

2023-07-14 05:14 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +                .content(objectMapper.writeValueAsString(tripCreateRequest)));
Hoxy,, restDocs 적용하실 생각 있으신가요,,?

2023-07-14 05:14 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/service/TripServiceTest.java
> +        Long actualId = tripService.save(tripCreateRequest);
final?

2023-07-14 05:14 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +        new TripCreateRequest(null, null, null);
이 코드는 무슨 용도 인가요? 진짜 모르겠어서 여쭤보는 것,,

2023-07-14 05:39 UTC, waterricecake reviewed
다이노 수고하셨습니다!

2023-07-14 05:39 UTC, waterricecake commented on backend/src/main/java/hanglog/global/BaseEntity.java
>  public class BaseEntity {
jpa 미션에서 리뷰받았던 내용인데 구상 클래스 보다 추상 클래스로 사용하는건 어떤가요?

2023-07-14 05:51 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +                .content(objectMapper.writeValueAsString(tripCreateRequest)));
sorry...https://github.com/woowacourse-teams/2023-hang-log/pull/42/commits/3f66567bf91c0998b3a0e999e70e74ba3fbe0564

2023-07-14 05:52 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/service/TripServiceTest.java
> +        Long actualId = tripService.save(tripCreateRequest);
sorry...https://github.com/woowacourse-teams/2023-hang-log/pull/42/commits/325ca90bd64907bab5f1b0bd1518b84421a1483c

2023-07-14 05:53 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/TripControllerTest.java
> +        new TripCreateRequest(null, null, null);
여러분들이 꼼꼼하게 리뷰하는지 확인하기 위한 저의 함정이었습니다~

제거 완료했습니다...sorry

2023-07-14 06:00 UTC, jjongwa commented on backend/src/main/java/hanglog/global/BaseEntity.java
>  public class BaseEntity {
good https://github.com/woowacourse-teams/2023-hang-log/pull/42/commits/1d2bbed69ab0f5ac5d20f157bca2a221464a9c22


그으으런데 리뷰를 남길 때는 근거를 바로 제시해 주는게 좋을 것 같습니다아아아아 jpa 미션에서 리뷰 받았던 내용이 원지 제가 어떻게 압니까아아아

추상클래스로 바꾸면 어떤 점에서 변경사항이 있고 이점이 생기는지 본인의 의견을 조금 더 적어주시면 좋을 것 같습니다아아 저희 그라운드 룰도 정했잖아요?
아니면 링크를 올려주던가아아아

2023-07-14 06:03 UTC, mcodnjs approved these changes

2023-07-14 06:05 UTC, waterricecake approved these changes
근거 꼭 적겠습니다~ 고생하셨서요

2023-07-14 06:07 UTC, hgo641 approved these changes

2023-07-14 06:08 UTC, merged