공유 상태 수정 및 공유 여행 조회 api 구현
woowacourse-teams/2023-hang-log pull request #424
Opened 2023-08-11 09:41 UTC by waterricecake

## 📄 Summary
>#392
share update시 공유 상태에 공유요청, 비공유 상태에 비공유 요청이어도 에러없이 진행되게 하였습니다.
테스트의 경우 controller와 mock을 넣은 dto테스트를 작성하였는데 통합테스트의 경우 이유를 알수 없는 역직렬화 및 직렬화 에러가 생겨서 해결후에 추가하겠습니다.

## 🙋🏻 More
>

2023-08-11 13:57 UTC, LJW25 reviewed
다른 부분은 거의 페어프로그래밍 했던 내용인듯해서 따로 해주신 조회 응답 관련해서만 코멘트 남겼습니다! 수고하셨어요~~

2023-08-11 13:57 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
> +    }
어라라 잠시만 이건 못봤던건데?

2023-08-11 13:57 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
> +    }
정팩메가 있는데 파라미터로 다 받는 생성자를 만드신 이유가 있나요? 보니까 테스트 픽스쳐 만드는곳 외에서는 안쓰이는 것 같아서요

2023-08-11 13:57 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
> +        )).orElseGet(() -> new TripDetailResponse(
이부분 중복 코드가 많고 어떤 흐름인지 한눈에 잘 들어오지 않는것 같아요!
차라리 여기서부터 return까지의 부분을
```
        final Optional<SharedTrip> sharedTrip = Optional.ofNullable(trip.getSharedTrip());
        final String sharedCode = sharedTrip.map(SharedTrip::getSharedCode).orElse(null);

        return  new TripDetailResponse(
                trip.getId(),
                cityWithPositionResponses,
                trip.getTitle(),
                trip.getStartDate(),
                trip.getEndDate(),
                trip.getDescription(),
                convertNameToUrl(trip.getImageName()),
                sharedCode,
                dayLogGetResponses
        );
```
이런식으로 가는건 어떤가요? 

이러면 새로 만든 생성자도 제거할 수 있어서 response가 의도하지 않은 방향으로 생성될 가능성을 막아줄 수 있을것 같습니다!

2023-08-11 17:46 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
> +    }
어 이거 단순히 shareCode가 null값을 반환해야할때 쓸려고 넣었는데 이오가 밑에 추천해준 방식이 좋은것 같네요! 이 생성자는 필요가 없겠어요...

2023-08-11 17:46 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
> +        )).orElseGet(() -> new TripDetailResponse(
오 이런방법이 있었네요;;;

2023-08-12 02:28 UTC, hgo641 reviewed
달리 고생고생하셨습니다!!!!

2023-08-12 02:28 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +
양방향 필요할까요?
`SharedTripService`보면 Repository 통해서 Trip의 SharedTrip찾아오는 것 같은데, Trip은 SharedTrip 몰라도 될 것 같아요!
`sharedTripRepository.findByTripId(tripId)
                .orElseGet(() -> SharedTrip.createdBy(trip));` 

`@OneToOne`이라서 Trip쪽은 항상 SharedTrip 즉시로딩할 수 밖에 없는데, 항상 참조하는 객체는 아니라서 얘는 지워도 될 것 같아요! 어떻게 생각하시나요?

2023-08-12 02:28 UTC, hgo641 commented on backend/src/main/java/hanglog/share/domain/SharedTrip.java
> +    private Trip trip;
음 대부분의 상황에서 Trip이 참조될 것 같긴한데 지연로딩하는 게 더 좋을지도?

2023-08-12 02:28 UTC, hgo641 commented on backend/src/main/java/hanglog/share/domain/SharedTrip.java
> +    }
음... 진짜 별거아닌데 위에 private생성자 지우고
`return new SharedTrip(null, trip, createCode(trip.getId()), SHARED);` 해도 괜찮을거같아요. 
생성 인자가 많은 애도 아니라서 그냥 저렇게 해도 될듯???

2023-08-12 02:28 UTC, hgo641 commented on backend/src/test/java/hanglog/share/fixture/ShareFixture.java
> +    );
둘이 어떤 차이가 있나요? 각자 어떤 상황에서 사용되나요??

2023-08-12 02:28 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/dto/response/TripDetailResponse.java
> +
?!! 이게 여기서 쓰이는 군요?...

2023-08-12 02:28 UTC, hgo641 commented on backend/src/test/java/hanglog/share/fixture/ShareFixture.java
> +    );
요기 한칸띄워주세요!

2023-08-12 04:37 UTC, waterricecake commented on backend/src/test/java/hanglog/share/fixture/ShareFixture.java
> +    );
통합테스트할때 다 넣어야하나 해서 넣다가 통합테스트를 빼면서 필요가 없어졌네요... 지금은 지우고 통합테스트 구현할때 추가하도록 하겠습니다.

2023-08-12 04:43 UTC, waterricecake commented on backend/src/main/java/hanglog/share/domain/SharedTrip.java
> +    }
또잉....
[40b9bdd](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/40b9bdd96ea83effa9a072e822b71ff170abd9ca)

2023-08-12 04:43 UTC, waterricecake commented on backend/src/main/java/hanglog/share/domain/SharedTrip.java
> +    }
[392ee0e](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/392ee0e299b9624c848bba91f94c3c08eef2ec27)

2023-08-12 04:44 UTC, waterricecake commented on backend/src/main/java/hanglog/share/domain/SharedTrip.java
> +    private Trip trip;
[392ee0e](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/392ee0e299b9624c848bba91f94c3c08eef2ec27)

2023-08-12 04:44 UTC, waterricecake commented on backend/src/main/java/hanglog/share/domain/SharedTrip.java
> +    public void updateSharedStatus(final SharedTripStatusRequest sharedTripStatusRequest) {
[392ee0e](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/392ee0e299b9624c848bba91f94c3c08eef2ec27)

2023-08-12 04:44 UTC, waterricecake commented on backend/src/main/java/hanglog/share/domain/SharedTrip.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
[392ee0e](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/392ee0e299b9624c848bba91f94c3c08eef2ec27)

2023-08-12 04:49 UTC, waterricecake commented on backend/src/test/java/hanglog/share/fixture/ShareFixture.java
> +    );
[style: fixture간 개행](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/a1d908fcf589f731e5917d0a5aadf97678ece99d)

2023-08-12 09:41 UTC, hgo641 reviewed
Trip이 SharedTrip 조회할 때 fetch join 적용 어떤가요?

2023-08-12 13:45 UTC, LJW25 approved these changes

2023-08-13 13:00 UTC, jjongwa requested changes
늦어서 죄송합니다ㅜㅜ
근데 주말이잖아

2023-08-13 13:00 UTC, jjongwa commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +
get이니까 Transactional readOnly 붙이시죠

2023-08-13 13:00 UTC, jjongwa commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +
이번에도 validateSharedStatus 메서드 분리가 납득이 잘 가지 않아요. (개인적 의견입니다. 다른 사람들은 괜찮을 수도 있음)

1. 분리한 메서드의 로직이 복잡한가? ( = 긴가?)
   -> 짧고 간단합니다.
3. 분리한 메서드의 네이밍을 통해 해당 행위의 가독성을 증가시킬 수 있는가?
   -> SharedStatus를 검증한다는 네이밍 
   -> if문의 조건절 `(sharedStatusType == UNSHARED)` 이 이미 충분히 그 역할을 해주고 있지 않나.?

```suggestion
public TripDetailResponse getTripDetail(final String sharedCode) {
        final SharedTrip sharedTrip = sharedTripRepository.findBySharedCode(sharedCode)
                .orElseThrow(() -> new BadRequestException(NOT_FOUND_SHARED_CODE));
        
        if (sharedTrip.getSharedStatus() == UNSHARED) {
            throw new BadRequestException(INVALID_SHARE_CODE);
        }
        
        final Long tripId = sharedTrip.getTrip().getId();
        final Trip trip = tripRepository.findById(tripId)
                .orElseThrow(() -> new BadRequestException(NOT_FOUND_TRIP_ID));
        final List<City> cities = getCitiesByTripId(tripId);

        return TripDetailResponse.of(trip, cities);
    }
```

제가 봤을땐 해당 구문을 다시 안으로 넣어놔도 이해하는데 전혀 문제 없는데? 라는 생각이 들었습니다.

2023-08-13 13:00 UTC, jjongwa commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +
TripService에도 getTripDetail이라는 메서드가 존재하는데요, 지금 만들어놓은 SharedTripService의 getTripDetail의 후반 부분과 로직이 같아요

```
public TripDetailResponse getTripDetail(final Long tripId) {
        final Trip trip = tripRepository.findById(tripId)
                .orElseThrow(() -> new BadRequestException(NOT_FOUND_TRIP_ID));
        final List<City> cities = getCitiesByTripId(tripId);
   return TripDetailResponse.of(trip, cities);
    }
```

지금 SharedTripService에서의 getTripDetail은 다음과 같은 흐름이죠?
1. sharedTrip에서 코드 가져와 검증 ->  코드가 없으면 예외처리, 코드가 있어도 비공유 상태이면 예외처리
3. 해당하는 Trip에 대한 DetailResponse 조립해 반환

여기서 1, 2 를 서로 분리해서 Controller에서 호출하는 방식은 어떤가요? 그러면 TripService에 있는getTripDetail을 재사용할 수 있을 것 같아요.!


```
@GetMapping("/shared-trips/{sharedCode}")
    public ResponseEntity<TripDetailResponse> getSharedTrip(@PathVariable final String sharedCode) {
       sharedtripService.validate(sharedCode);  // 네이밍은 그냥 예시임
        final TripDetailResponse tripDetailResponse = tripService.getTripDetail(sharedCode);
        return ResponseEntity.ok().body(tripDetailResponse);
    }
```

2023-08-13 13:00 UTC, jjongwa commented on backend/src/test/java/hanglog/share/service/SharedTripServiceTest.java
> +        final SharedTrip sharedTrip = new SharedTrip(1L, TRIP, "xxxxx", SHARED);
요런 중복되는 친구들을 분리하면 좋을 것 같아요.

2023-08-13 13:00 UTC, jjongwa commented on backend/src/test/java/hanglog/share/service/SharedTripServiceTest.java
> +                .willReturn(Optional.ofNullable(null));
```suggestion
        given(sharedTripRepository.findByTripId(anyLong()))
                .willReturn(Optional.empty());
```
요친구랑 의미하는 바가 다른가요?

2023-08-13 13:45 UTC, waterricecake commented on backend/src/main/java/hanglog/share/presentation/SharedTripController.java
> +        return ResponseEntity.ok().body(sharedTripCodeResponse);
body에 sharedCode를 담아서 보내는데 noContent면 못보내지 않나요?

2023-08-13 14:04 UTC, waterricecake commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +
검증 로직 같은 경우에는 명시적으로 보여주는것이 좋지 않은가 하여 분리를 하였습니다. 근데... 디노 말대로 어려운 로직도 아니긴 해서 분리해도 상관 없을것 같네요.

2023-08-13 16:22 UTC, jjongwa commented on backend/src/main/java/hanglog/share/presentation/SharedTripController.java
> +        return ResponseEntity.ok().body(sharedTripCodeResponse);
왜 Response를 보내야 하는건가요?

2023-08-13 18:33 UTC, waterricecake commented on backend/src/main/java/hanglog/share/presentation/SharedTripController.java
> +        return ResponseEntity.ok().body(sharedTripCodeResponse);
비공유 상태에서 공유상태로 변했을때 프론트 측에서 이미 trip에 대한 데이터를 갖고 있지만 shareCode는 없으니까 code를 보여줘야 해서 입니다.

2023-08-13 18:37 UTC, waterricecake commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +
중복되는 코드라 tripService를 통해 처리해줘도 좋을 것 같다고 생각하긴 했는데 Share의 로직과 Trip의 로직이 분리되는 것이 좋을 것 같다는 생각이 들어 최대한 분리하려고 하였습니다.

2023-08-13 18:55 UTC, waterricecake commented on backend/src/test/java/hanglog/share/service/SharedTripServiceTest.java
> +        final SharedTrip sharedTrip = new SharedTrip(1L, TRIP, "xxxxx", SHARED);
[7b73629](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/7b73629d9acc3ca29ff0ee72b4c1b8e75320503a)

2023-08-13 18:56 UTC, waterricecake commented on backend/src/test/java/hanglog/share/service/SharedTripServiceTest.java
> +                .willReturn(Optional.ofNullable(null));
[7b73629](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/7b73629d9acc3ca29ff0ee72b4c1b8e75320503a)

2023-08-13 18:57 UTC, waterricecake commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +
[34c85fc](https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/34c85fcd6437f4b6b3834b6e246c52b050df510b)

2023-08-14 00:51 UTC, jjongwa commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +
` Share의 로직과 Trip의 로직이 분리되는 것이 좋을 것 같다는 생각이 들어` 이러면 오히려 검증 부분만 SharedService에서 맡고 있고 Trip detail을 가져오는건 TripService의 메서드를 호출하는게 더 좋지 않을까요?

달리가 말하는 Shared의 로직과 Trip의 로직이 분리되는 것이 좋을 것 같다 의 의미를 완벽하게 이해하지 못하겠어요..!
추가적인 설명 부탁 드립니닷..

2023-08-14 00:56 UTC, jjongwa commented on backend/src/main/java/hanglog/share/service/SharedTripService.java
> +    }
음 여기는 조회만 하는게 아니라 save도 하는데 readOnly true면 안되지 않을까요..!

2023-08-14 00:56 UTC, jjongwa commented on backend/src/main/java/hanglog/share/presentation/SharedTripController.java
> +        return ResponseEntity.ok().body(sharedTripCodeResponse);
그럼 공유상태에서 비공유상태를 바꿨을 때는 의미 없는 response를 반환하는 상황인거네요?

`비공유 상태에서 공유상태로 변했을때 프론트 측에서 이미 trip에 대한 데이터를 갖고 있지만 shareCode는 없으니까 code를 보여줘야 해서 입니다.`
이 말은 결국 수정을 하는데 특정 경우에 대해서는 반환해줘야 하는 값이 있어서 모든 경우에 반환값을 넣었다는 건데,

수정은 그냥 수정하는 역할만 하고, sharedCode만 따로 반환해줄 수 있는 get 메서드를 만들어 분리하면 안되는걸까요 ..?

2023-08-14 01:01 UTC, jjongwa requested changes
커밋이랑 file change 상태가 왜이러죠 ..? 

https://github.com/woowacourse-teams/2023-hang-log/pull/424/commits/e9f044972fca809be19786f7fd5092d1ce2f36e6

홍고처럼 해결 못하겠다 싶으면 close 하고 pr 새로 파야할듯..!

2023-08-14 02:47 UTC, closed without merging

2023-08-14 02:47 UTC, waterricecake commented
하... 새로 파겠습니다...