DayLog 조회 API 구현
woowacourse-teams/2023-hang-log pull request #43
Opened 2023-07-13 15:28 UTC by LJW25

## 📄 Summary
> #35 
> dayLogId로 날짜 별 기록을 조회하는 기능 구현 완료하였습니다.
> 

## 🙋🏻 More
>

2023-07-13 16:27 UTC, jjongwa approved these changes
홍고생고생하셨습니다 이오 멋지네요
건들게 딱히 없어서 바로 approve 하겠슴다~

백엔드 폼 미쳤따이

2023-07-13 16:27 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/DayLogController.java
> +
크흠

2023-07-13 16:27 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/presentation/dto/response/DayLogGetResponse.java
> +    }
어어 정팩메
이것도 컨벤션 정해 볼까요 ,,,

2023-07-13 16:27 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/DayLogControllerTest.java
> +
이런거 지적하면 좀 그런가요 ..
그만큼 건드릴게 없다는 뜻입니다 하하하

2023-07-13 16:27 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
> +        BDDMockito.given(dayLogRepository.findById(1L))
static import 어떤가용

2023-07-13 16:41 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/service/DayLogServiceTest.java
> +        BDDMockito.given(dayLogRepository.findById(1L))
반영하였습니당

2023-07-14 01:25 UTC, hgo641 reviewed
이오짱! 이오짱!

2023-07-14 01:25 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/DayLogController.java
> +@RequestMapping("/trips/{tripId}/daylog/{id}")
dayLogId 어때요~~

2023-07-14 01:25 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/dto/request/DayLogUpdateTitleRequest.java
> +    private String title;
size validation 추가하는 거 어떠신가요?

2023-07-14 01:25 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/service/DayLogService.java
> +        return DayLogGetResponse.of(dayLog);
deleted 일 때 예외던지면 좋을거같아요~

2023-07-14 04:21 UTC, mcodnjs requested changes
좋은데요? 좋은데요? 좋은데요 ?

2023-07-14 04:21 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/domain/DayLog.java
>      }
이거 나중에 사용할 생성자인거 같은데, 필드에 그냥 `new ArrayList<>()` 박는 것도 좋을지도 ?!?

2023-07-14 04:21 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/presentation/DayLogController.java
> +@RequestMapping("/trips/{tripId}/daylog/{id}")
어때요 22 ~~~~

2023-07-14 05:20 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/domain/DayLog.java
>      }
이거 홍고가 써야하는 생성자인데 컨플릭트를 줄여보려고 똑같이 넣었습니다 🫠

2023-07-14 05:21 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/presentation/DayLogController.java
> +@RequestMapping("/trips/{tripId}/daylog/{id}")
수정할게요~~~~~~

2023-07-14 05:46 UTC, waterricecake reviewed
이오 수고하셨습니다

2023-07-14 05:46 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/presentation/DayLogController.java
> +                                                  @RequestBody @Valid final DayLogUpdateTitleRequest request) {
```suggestion
    public ResponseEntity<Void> updateDayLogTitle(
                                                  @PathVariable final Long tripId,
                                                  @PathVariable final Long id,
                                                  @RequestBody @Valid final DayLogUpdateTitleRequest request) {
```

2023-07-14 05:46 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/service/DayLogService.java
> +    public DayLogGetResponse getById(final Long id) {
조회에 해당되는데 `@Transactional(readOnly=true)` 어떤가요?

2023-07-14 06:30 UTC, waterricecake approved these changes

2023-07-14 06:32 UTC, hgo641 approved these changes

2023-07-14 06:38 UTC, merged