Trip 테스트 및 통합 fixture 추가
woowacourse-teams/2023-hang-log pull request #430
Opened 2023-08-12 13:25 UTC by mcodnjs

## 📄 Summary
> #401 

## 🙋🏻 More
> 서비스랑 레포도 할건데! 중간 점검 차 pr 올립니다!

2023-08-12 13:39 UTC, LJW25 reviewed
덕분에 실직했습니다 라온 감사해요..
라온 pr 머지될때까지 기다려야겠어요🥳

2023-08-12 13:39 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/dto/response/DayLogResponse.java
> +public class DayLogResponse {
혹시 이름 바꾸신 이유가 뭘까요? 
이거 이름 정할때 request 같은 다른 dto들은 대부분 용도도 함께 이름에 포함했어서 데이로그도 Get을 포함하기로 한거였어서요!

2023-08-12 13:39 UTC, LJW25 commented on backend/src/test/java/hanglog/IntegrationTest.java
> +    }
mock 데이터 안쓰고 하려고 integrationTest 새로 만드신걸까요? 
근데 도시랑 카테고리랑 환율 세가지는 저희도 sql로 db에 넣어두는 데이터인데 그냥 sql 쓰는게 낫지 않을까 하는 의견이 있습니당.. 
어차피 수정되면 안될&안되는 데이터인데 매번 beforeEach 할 필요 없이 한번만 sql로 넣어도 되지 않을까요?!

2023-08-12 13:39 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/integration/DayLogIntegrationTest.java
> +
?! 이오 실직.
감사합니다 라온

2023-08-12 13:39 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/integration/DayLogIntegrationTest.java
> +    }
확인

2023-08-12 13:39 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/integration/TripIntegrationTest.java
> +    protected static ExtractableResponse<Response> 여행_생성_요청(final TripCreateRequest tripCreateRequest) {
근데 개인적으로는 여기는 메소드명이 한글이고 테스트는 영어라서 인수테스트랑 controller 통합테스트랑 섞인 느낌인데 통일하면 어떨까요?
이것도 막 확고한 의견은 아니라서 참고만 해주시면 감사하겠습니다.

2023-08-12 13:40 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/service/TripService.java
>      }
끝나지 않는 일정 수정 .. 
테스트 짜다가 터져서 보니까 로직에 또또 버그가 있어서 수정했습니다 ~

2023-08-12 13:40 UTC, mcodnjs commented on backend/src/test/java/hanglog/IntegrationFixture.java
> +public class IntegrationFixture {
일단, 도메인 위주로 넣어놨는데! Request Dto도 많이 중복되면 넣어놔도 좋을거 같아요!
Response Dto가 아닌 도메인을 fixture로 만든 이유는 아래와 같습니다
- Response 만들 때도 활용도가 높고, (보통 response를 도메인으로 만듬)
- 실제 db에 넣을 때 도메인(엔티티) 집어넣고,
- 수정할 경우 Response 가 바뀌는 경우가 많아서 등등.. 

+) 사용할지 안할지 모르지만 몇개 만들어놨는데 테스트 짜시다가 사용안하시는거 있으면 삭제하거나 추가하시면 됩니당

2023-08-12 13:40 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/integration/DayLogIntegrationTest.java
> +public class DayLogIntegrationTest extends IntegrationTest {
@LJW25 
이거 제가 생각하는 데이로그통합 테스트 대충! 만들어봤는데 참고하시면 좋을거 같아요 !! (참고용!)

2023-08-12 13:40 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/integration/TripIntegrationTest.java
> +                            .ignoringFields("id", "cities", "dayLogs")
cities 제외한 이유는 사진과 같습니다.. 어떻게 해결할지 몰라서 아래 처럼 따로 뺐어요 ㅠㅠ 

<img width="320" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/64852591/2e01989c-7833-4921-ab0e-382828ea6fe5">

2023-08-12 13:45 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/dto/response/DayLogResponse.java
> +public class DayLogResponse {
<img width="198" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/64852591/25fd2af3-e011-420f-9723-66465c666079">

엇 근데 현재 dto들이 http 메소드를 포함한 dto는 보이지 않고, dayLogResponse 하나 밖에 존재하지 않는거 같아서 변경했어요!
다른 분들 의견도 궁금 !! 저는 갠적으론 DayLogResponse로 만해도 충분하다고 생각합니다 ㅎㅎ ..

2023-08-12 13:46 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/integration/DayLogIntegrationTest.java
> +
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 아니아니 ~~ 참고용 ~~~ 
이오 확인하시고 삭제할 예정이었습니다 ㅎㅎ

2023-08-12 13:57 UTC, mcodnjs commented on backend/src/test/java/hanglog/IntegrationTest.java
> +    }
> mock 데이터 안쓰고 하려고 integrationTest 새로 만드신걸까요?

IntegrationTest는 원래 있었던 클래스였는데, sql문들을 제거했어요!
아마 패키지를 global에서 그냥 상위로 옮기면서 제거됐다고 뜨는거 같아용

> 어차피 수정되면 안될&안되는 데이터인데 매번 beforeEach 할 필요 없이 한번만 sql로 넣어도 되지 않을까요?!

맞아요 .. 글킨한데 이제 fixture로 저희가 카테고리랑 도시들을 만들잖아요, 
근데 그럼 관리요소가 2개가 생기는거 같기도 해서 그냥 beforeEach로 데이터를 박아놓는 방식을 선택했는데, 매 테스트마다 실행되는건 저도 비효율적이라하긴 합니다 .. 한번만 실행시킬 수 있는 beforeAll 이라는 어노테이션을 사용하면 될지도 ? 

근데? 갑자기 sql 어노테이션은 매 테스트마다 실행이 되지 않나 .. ? 라는 생각이 들었고,, ? 그럼 테스트마다 격리 수준이 보장되는거 같긴한데 .. ? 하는 생각이 .. ?

2023-08-12 13:59 UTC, mcodnjs commented on backend/src/test/java/hanglog/IntegrationTest.java
> +    }
저는 beforeAll로 바꾸고 지금 방식에 한표 ㅎㅎ

2023-08-12 13:59 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/integration/TripIntegrationTest.java
> +                            .ignoringFields("id", "cities", "dayLogs")
좀 더 복잡하긴 하지만 
```
.ignoringFieldsMatchingRegexes(".*latitude", "*.longitude")
```
추가하면 도시 id, name은 비교하고 위,경도는 비교 안해서 적당히 검증도 할 수 있어서 괜찮을듯 합니다!

2023-08-12 19:13 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/TripService.java
>      }
굿굿

2023-08-13 06:18 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/dto/response/DayLogResponse.java
> +public class DayLogResponse {
혼동이 될 수 있는 dto가 DayLogExpenseResponse밖에 없다고 생각되는데 다른 패키지에 있고 이름도 충분히 expense에서 쓰이는 이름이라 DayLogResponse로 해도 충분할 것 같아요.

2023-08-13 06:29 UTC, waterricecake approved these changes
수고하셨습니다 라온

2023-08-13 06:29 UTC, waterricecake commented on backend/src/test/java/hanglog/IntegrationFixture.java
> +import static hanglog.trip.domain.type.ItemType.SPOT;
trip 뿐만이 아니라 외부 expense나 공유 패키지에서도 쓰일 것 같은데 global이나 그런 곳으로 옮기는건 어떤가요?

2023-08-13 09:16 UTC, hgo641 approved these changes
라온고생!!!하셨습니다!!!

2023-08-13 09:16 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/integration/DayLogIntegrationTest.java
> +        dayLogId = tripDetailResponse.getDayLogs().get(0).getId();
음 `ExtractableResponse<Response>` 객체랑 저희가 만든 DTO 객체의 네이밍 규칙이 비슷해서 조금 헷갈리는거같기도... 그치만 마땅한 좋은 이름은 안떠오르네요 ㅎㅎ... tripCreateResult?...

2023-08-13 09:16 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/integration/DayLogIntegrationTest.java
> +                            .ignoringFields("id")
`.ignoringFields("id")` 요거는 왜 있는건가요?

2023-08-13 17:23 UTC, LJW25 requested changes
제가 DayLogIntegrationTest를 PR 올렸기때문에 충돌날까봐 일단 request changes 해두겠습니다! 
없애주시면 베리 땡스

2023-08-15 10:24 UTC, jjongwa approved these changes

2023-08-15 14:01 UTC, merged