도시입력창 & 제안목록 컴포넌트 구현
woowacourse-teams/2023-hang-log pull request #49
Opened 2023-07-15 09:23 UTC by Dahyeeee

## 📄 Summary
> 
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/27221d04-28ec-40a1-9fbd-3972d6e88582)
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/102305630/f04d2b2c-db8b-4b0b-ac7c-6e8d6bd23d72)

### 기능
- 검색어 첫 글자(모음+자음)에 해당하는 제안 목록
- 키보드로 제안 목록 탐색 & 선택 가능
- 선택시 태그 생성 
- 태그 삭제

### 미완기능
- 제안목록 스크롤바있을 때 키보드 동작 시 자동 스크롤링
- tag 있을 때 입력창 width 줄이기 

## 🙋🏻 More
> 미완기능 리뷰받으면서 계속 구현해볼게요!

2023-07-15 09:43 UTC, ashleysyheo requested changes
헤다 수고 많았습니다 👍🔥

지금 연결된 이슈 번호가 "trip생성페이지 구현"에 대한 이슈인데, 새로운 이슈를 파거나 이슈 네이밍을 변경해 주면 좋을 것 같아요!

가장 먼저 피그마 시안이랑 만든 컴포넌트랑 많이 다른 것 같아요. 한 번 더 확인부탁드려요. 그리고 컴포넌트를 확인할 방법이 없네요. 스토리북을 추가해주시면 리뷰하는데 도움이 될 것 같아요~
추가적으로 코멘트들도 추가해주면 좋을 것 같아요. 지금 바로 이게 무엇을 위한 로직인지 알기 어려운 부분도 없지 않아 있어요. 

일단, 컴포넌트를 바로 확인 할 수 없는 관계로 코드 컨벤션 관련 코멘트들을 주로 남겼습니다!

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/hooks/common/useSuggestion.ts
> +const cities = [
mockData는 파일 분리하는 것이 좋을 것 같아요. mockData 폴더의 data폴더에 넣는 것에 대해서 어떻게 생각하세요?

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/hooks/common/useSuggestion.ts
> +export default useSuggestion;
커스텀 훅은 네임드 export하기로 했습니다.

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/hooks/common/useCityTags.ts
> +export default useCityTags;
커스텀 훅은 네임드 export하기로 했습니다.

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/constants/city.ts
> +  MAX_NUM: 15,
이 CITY의 MAX_NUM이 뭘 말하는지 명확하지 않는 것 같아요. CITY라는 네이밍 대신 보다 명시적인 이름이면 좋을 것 같아요.

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/hooks/common/useSuggestion.ts
> +const useSuggestion = () => {
city에 대한 suggestion을 위한 hook 같은데, 지금 네이밍은 좀 모호한 것 같아요. 전반적인 모든 suggestion을 위한 훅 같아요.  useCitySuggestion은 어떤가요?

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/hooks/common/useSuggestion.ts
> +  const [focusedSuggestionIndex, setFocusedSuggestionIndex] = useState(-1);
이 -1은 뭘 의미하는 것인가요?

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.style.ts
> +export const container = css({
styling postfix ??? (다른 것들에도 마찬가지 입니다)

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +import { FormEvent, useRef, useState } from 'react';
FormEvent는 타입 온리 임포트

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +import useCityTags from '@components/common/CitySearchBar/useCityTags';
커스텀 훅은 hooks 폴더에 분리하기로 했습니다.

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +  wrapper,
어떤 것은 styling postfix가 있고 어떤 것은 없어요!

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +          aria-label="remove tag"
aria label은 한국어로 하는 것은 어떠세요?

2023-07-15 09:43 UTC, ashleysyheo commented on frontend/src/components/common/Suggestion/Suggestion.tsx
> +} from 'hang-log-design-system';
이름을 다르게 임포트한 이유가 있나요?

2023-07-15 14:00 UTC, jjongwa commented
너무 멋져요 
주말에도 고생하는 행록 파이팅~~~

2023-07-17 08:14 UTC, dladncks1217 commented on frontend/src/hooks/common/useCityTags.ts
> +import { City } from '@/components/common/CitySearchBar/CitySearchBar';
절대경로가 아니에요!

2023-07-17 08:14 UTC, dladncks1217 commented on frontend/src/mocks/data/city.ts
> +import { City } from '@/components/common/CitySearchBar/CitySearchBar';
절대경로가 아니에요!

2023-07-17 08:14 UTC, dladncks1217 commented on frontend/src/components/common/CitySearchBar/CitySearchBar.tsx
> +import { useCityTags } from '@/hooks/common/useCityTags';
절대경로가 아니에요!

2023-07-17 08:17 UTC, dladncks1217 commented on frontend/src/hooks/common/useCitySuggestion.ts
> +      const filteredSuggestions = cities.filter(({ name }) => new RegExp(`^${word}`).test(name));
filter를 돌면서 매번 `new RegExp(`^${word}`)`를 생성하는건 비효율적인 것 같아요! 분리하는건 어떨까요?

2023-07-17 08:18 UTC, dladncks1217 commented on frontend/src/hooks/common/useCitySuggestion.ts
> +  });
의존성 배열 빈 배열이 빠진 것 같아요!

2023-07-17 08:19 UTC, dladncks1217 commented on frontend/src/mocks/data/city.ts
> +];
목데이터 분리 좋네요👍

2023-07-17 12:06 UTC, Dahyeeee commented on frontend/src/hooks/common/useSuggestion.ts
> +  const [focusedSuggestionIndex, setFocusedSuggestionIndex] = useState(-1);
index가 0부터 시작이라 해당되지 않는 수로 시작했는데 음 null로 할까요?!

2023-07-17 12:07 UTC, Dahyeeee commented on frontend/src/components/common/Suggestion/Suggestion.tsx
> +} from 'hang-log-design-system';
사용하는 측에서 좀 명확하면 좋을 것 같아서요! 어떠신가유

2023-07-17 12:09 UTC, Dahyeeee commented on frontend/src/hooks/common/useCitySuggestion.ts
> +      const filteredSuggestions = cities.filter(({ name }) => new RegExp(`^${word}`).test(name));
오 굳굳!! 좋ㅇ은거같아요 위로 뺐습니다

2023-07-18 05:11 UTC, dladncks1217 approved these changes

2023-07-18 05:57 UTC, ashleysyheo approved these changes

2023-07-18 05:57 UTC, merged