TripList 페이지 구현
woowacourse-teams/2023-hang-log pull request #51
Opened 2023-07-16 12:40 UTC by dladncks1217

## 📄 Summary
>

### 트립 목록 화면
![Jul-16-2023 21-36-37](https://github.com/woowacourse-teams/2023-hang-log/assets/45068522/05bfad53-f36e-40cc-a061-1ba3a7d85d47)

### 튜토리얼 모달 화면
![Jul-16-2023 21-39-11](https://github.com/woowacourse-teams/2023-hang-log/assets/45068522/39731f95-0080-4c43-a3e1-0e70f936e1bf)

- [x] 여행 목록들을 확인할 수 있다.
- [x] 여행 목록들을 등록순으로 정렬할 수 있다.
- [x] 여행 목록들을 날짜순으로 정렬할 수 있다.
- [x] 여행 목록이 비어있으면 튜토리얼 모달을 띄운다. (인증 인가 기능 구현 전에만 임시로)

<br>

- [x] TripListPage 구현
- [x] Trip List 조회 api msw 모킹
- [x] 튜토리얼 모달 컴포넌트 구현
- [x] 튜토리얼 모달 컴포넌트에 Slick Slider 구현

## 🙋🏻 More
>

#### 튜토리얼 모달
튜토리얼 모달에 대해, 존재하는 trip이 없을 경우 띄워주도록 우선 설정했습니다.
그렇다보니 현재 msw 모킹에 대해서 trip을 0개 반환하는 msw 핸들러와 trip들을 반환하는 핸들러로 나뉘어있습니다. 요청부분만 조금 다르게 해서 테스트할 수 있지 않을까 싶습니다.

close #36

2023-07-16 13:31 UTC, ashleysyheo requested changes
슬링키 주말동안 진짜 수고하셨습니다!!!! 🔥

간략하게(?) 리뷰랑 질문 남겼습니다! 

### 코드 컨밴션 
코드 컨밴션 - css 순서, 타입 온리 임포트, 폴더 구조 등 한 번 더 확인해주세요!

### 마크업
시안 한 번 더 확인 부탁드려요. 뭔가 안 맞는 부분들이 살짝 살짝 있습니다. 

### 튜토리얼
- 튜토리얼 모달 비율이 살짝 이상합니다. 
- 화살표는 안 보이게 하고, 하단에 dots만 보이게 하면 어떨까요?
- 상단에 `x` 아이콘을 추가해서 닫을 수 있게 해주세요 
  - 이건 디자인 시스템에서 `x`를 추가해둔 다음에 `isClosable`을 props로 받아서 이 기능을 사용할 수 있게 하면 좋을 것 같네요. 

### React Query
저희 suspense / error boundary 사용하기로 한 것 아니였나요?? 
아직 error boundary 컴포넌트는 안 만들어서 적용 못하지만 suspense + fallback은 지금 처리해 두면 좋을 것 같아요!

### 스토리북
스토리북도 잊지 말아 주세요!!! 우리 CDD... ㅋㅋㅋ

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsHeader/TripsHeader.tsx
> +        <Box css={SVGBoxStyling} styles={{ width: '70%', height: '18%', paddingRight: '50px' }}>
`Flex` 대신 `Box`를 사용한 이유가 있나요? `.style.ts` 파일에 보니까 따로 flex 관련 css를 추가했더라고요.

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsHeader/TripsHeader.tsx
> +        <Box styles={{ width: '30%', height: '18%' }}>
`30%`, `18%`??? 이 숫자는 뭐죠....?????

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +
![Group 2689](https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/0192f0d7-58b8-448c-99e0-44c301761256)

시안 한 번 더 확인해주세요

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +
그리고 `~` 말고 `-`

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +  padding: '0',
`0`은 그냥 숫자로 적어도 되지 않을까요?

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +  alignSelf: 'start',
css 순서!!!!!

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +  marginBottom: Theme.spacer.spacing1,
css 순서!

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +    marginRight: Theme.spacer.spacing2,
😱 css 순서.....

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.tsx
> +import { Cities } from '@type/trips';
type 온리 임포트

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +import { TripsType } from '@type/trips';
type only import

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +        <Flex styles={{ justify: 'right', paddingRight: '60px' }} css={TripsToggleGroupStyling}>
이 paddingRight 60px의 정체는 뭐죠...???? 50을 적고자 했던건가요??

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +              text="등록순"
`등록순` `날짜순`도 상수화 하면 좋을 것 같아요!

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +  data: TripsType[];
이 `data`가 뭔지 조금 더 명시적이면 이해하는데 도움이 될 것 같아요

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +} from '@components/trips/TripsItemList/TripsItemList.style';
아니 왜 갑자기 대문자?

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemNone/TripsItemNone.tsx
> +      <Text style={{ padding: '5px 0 10px' }}>
5...??? 10....???
![Frame 2687](https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/df5a919f-79ba-4def-85a2-c55c2e0ac408)

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemNone/TripsItemNone.tsx
> +      <Button variant="primary" size="small">
size medium 입니다

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
> +    <Modal isOpen={modalStatus} closeModal={handleModalClose} hasCloseButton={true}>
모달 비율이 조금 이상하군요... 🤔

한 번 더 확인 부탁합니다

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/utils/common/sortByStartDate.ts
> +  return dateA.getTime() - dateB.getTime();
return 위에 개행!

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/types/trips.ts
> +export interface TripsType {
저희 뒤에 Types로 할지 Data로 할지 정하고 통일합시다!

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/hooks/trips/useGetTrips.ts
> +const fetchTrips = async () => {
저희가 처음에 의논한 대로라면 이건 api 폴더의 trips에 위치하는 것이 맞지 않을까요?

그리고 prefix도 get이 맞을것 같습니다.

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/hooks/trips/useGetTrips.ts
> +const fetchTrips = async () => {
여기는 async/await가 안 붙어도 되지 않나요?

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/hooks/trips/useGetTrips.ts
> +  const { isLoading, isFetching, data, isSuccess, refetch } = useQuery(['trips'], fetchTrips);
저희 suspense 사용하는 것 아닌가요???

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/pages/TripsPage.tsx
> +    if (selected === '등록순') refetch();
refetch를 하는 이유가 뭔가요? 어차피 data는 안 변경되지 않나요??

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/hooks/trips/useGetTrips.ts
> +  return { isLoading, isFetching, data, isSuccess, refetch };
네이밍이 더 명시적이면 좋을 것 같습니다. 나중에 한 컴포넌트에서 여려개의 useQuery를 사용한다면 네이밍이 겹칠 것 같아요

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/pages/TripsPage.tsx
> +    if (selected === '등록순') refetch();
질문있습니다! refetch와 invalidate queries의 차이는 뭐죠??? 저는 invalidate queries 했거든요...... 🤔

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/pages/TripsPage.tsx
> +
상태로 관리하는 거 말고 이렇게 처리하는거 나쁘지 않은데요...?!

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/pages/TripsPage.tsx
> +        data && <TripsItemNone />
`data && `한 이유가 있나요?

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/hooks/trips/useGetTrips.ts
> +  return await axiosInstance.get(END_POINTS.TRIPS);
밑에서 `data?.data.trips.length`이렇게 사용하고 있던데, 

```ts
export const getTrip = async (tripId: number) => {
  const { data } = await axiosInstance.get<TripData>(END_POINTS.TRIP(tripId));

  return data;
};
```

요런식으로 구조분해할당 해서 리턴하면 더 깔끔해지지 않을까요?

2023-07-16 13:31 UTC, ashleysyheo commented on frontend/src/types/trips.ts
> +}
imageUrls?? 한 개만 들어오면 imageUrl이 맞지 않나...??

추가적으로 optional인 필드들이 있잖아요. 이 경우에는 null이 들어온다고 했는데, 이 부분도 함께 처리해주면 좋을 것 같습니다.

2023-07-16 13:41 UTC, ashleysyheo commented on frontend/src/pages/TripsPage.tsx
> +    if (selected === '등록순') refetch();
https://careerly.co.kr/qnas/1362

2023-07-17 03:38 UTC, ashleysyheo commented on frontend/src/mocks/handlers/index.ts
> +        trips: [
이건 mock data로 빼는 것은 어떤가요??

2023-07-17 03:38 UTC, ashleysyheo commented on frontend/src/mocks/handlers/index.ts
> +  rest.get('/trips', (req, res, ctx) => {
tripsHandler로 파일을 따로 분리하는 것은 어떤가요? 나중에 모킹할 것들이 많아지면 파일이 너무 길어질 것 같아요

2023-07-17 05:30 UTC, Dahyeeee requested changes
오오 페이지가 멋지군요 슬링키~~ 굳굳 

list 순서를 토글하는 로직을 list컴포넌트로 옮기는 게 어떨지가 큰 질문입니다~~

2023-07-17 05:30 UTC, Dahyeeee commented on frontend/src/components/Trips/TripsItem/TripsItem.tsx
> +  badgeName: Cities[];
이거 저는 cityTags로 했는데 하나로 통일해야겠죠? 선호하시는 게 있나요?
저는 개인적으로 cityTags가 좋습니다 ㅋㅋㅋㅋ

2023-07-17 05:30 UTC, Dahyeeee commented on frontend/src/components/Trips/TripsItem/TripsItem.tsx
> +        {badgeName.map((data) => {
data 대신 badge같은 명시적은 이름 어떠신가요

2023-07-17 05:30 UTC, Dahyeeee commented on frontend/src/components/Trips/TripsItemList/TripsItemList.style.ts
> +  columnGap: '24px',
이것도 Theme에 있답니당~.~

2023-07-17 05:30 UTC, Dahyeeee commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +  sortBy: string | number;
이거 page에서 주입받지 않고 여기서 처리해주는 거 어려우려나요..? 
Toggle도 이 컴포넌트 안에 있어서 그게 자연스러울 거 같아요.

그리고 혹시 sortBy 대신 order 는 어떠심? ㅎㅎ

2023-07-17 05:30 UTC, Dahyeeee commented on frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
> +  const [modalStatus, setModalStatus] = useState(true);
이거 모달 열고 닫는 state 인가요?
디자인 시스템에 있는 userOverlay 쓰면 될 거같은데 초기값이 false이긴 해서 수정하고 재배포해서 써볼까요..?ㅎㅎㅎㅎ 일단 useEffect로 true로 설정해서 사용가능할듯!

2023-07-17 05:30 UTC, Dahyeeee commented on frontend/src/pages/TripsPage.tsx
> +  const { selected, handleSelectClick } = useSelect('등록순');
저 요런 애들 rename해서 가져오면 좋을 것 같은데 어떻게 생각하시나요.
selected: sortSelected 같은 식으로용..

2023-07-17 05:30 UTC, Dahyeeee commented on frontend/src/types/trips.ts
> +export interface TripsType {
굳 api로 들어오는 데이터들만 모아서 정리하면 좋을 것 같아요.

2023-07-17 06:31 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.tsx
> +  badgeName: Cities[];
저도 cityTags 좋아요! 명시적인 네이밍이 더 이해하는데 도움이 되는 것 같아요

2023-07-17 12:52 UTC, dladncks1217 reviewed
리뷰 반영 해 보았습니다~!
확인 한번 부탁드릴게요👍

2023-07-17 12:56 UTC, dladncks1217 commented
+ 스토리북 코드는 내일까지 작성하겠습니다~

2023-07-17 13:06 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +  padding: '0',
음.... 이것도 내일 의논해 보시죠! @Dahyeeee

2023-07-17 13:08 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +    marginRight: Theme.spacer.spacing2,
이 파일 전체적인 css 순서를 말하는 거였어요! 

밑에도...

```
export const tripsDurationTextStyling = css({
  marginTop: '4px',
  width: '100%',
  textOverflow: 'ellipsis',
  overflow: 'hidden',
  wordBreak: 'break-word',
  display: '-webkit-box',
  '-webkit-line-clamp': '2',
  '-webkit-box-orient': 'vertical',
});
```

순서... (저희 진짜 style-lint 도입하시죠...!)

2023-07-17 13:10 UTC, ashleysyheo commented on frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
> +    <Modal isOpen={modalStatus} closeModal={handleModalClose} hasCloseButton={true}>
어... 그거 제대로된거 아닌데요.....!!!!!!???

2023-07-17 13:13 UTC, ashleysyheo commented on frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
> +    <Modal isOpen={modalStatus} closeModal={handleModalClose} hasCloseButton={true}>
![Group 2691](https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/44fbf345-b12d-4e1d-be4e-69470eaa9808)

2023-07-17 13:14 UTC, ashleysyheo commented on frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
> +    <Modal isOpen={modalStatus} closeModal={handleModalClose} hasCloseButton={true}>
모달 총 width x height = 450 x 581

2023-07-17 13:17 UTC, ashleysyheo commented on frontend/src/pages/TripsPage.tsx
> +        data && <TripsItemNone />
`초기 로딩 시에 가`?? 뭐가 어떻다는 거죠....?

2023-07-17 13:18 UTC, ashleysyheo commented on frontend/src/types/trips.ts
> +  description?: string;
없을 때는 `null`이 들어온다고 알고 있는데, 아닌가요? optional로만 처리해 두면 나중에 타입 에러 나지 않을까요??

2023-07-17 13:21 UTC, ashleysyheo commented on frontend/src/pages/TripsPage.tsx
> +    if (sortSelected === ORDER_BY_REGISTRATION) queryClient.invalidateQueries(['trips']);
그런데, 탭을 변경할 때마다 데이터를 요청할 필요가 있을까요?? (진짜 궁금... 왜냐하면 저도 Day 탭 변경할 때마다 데이터를 요청할지에 대한 고민이 많았거든요. 저는 일단 데이터 재요청 안 합니다 ㅋㅋㅋㅋ)

2023-07-17 13:25 UTC, ashleysyheo commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +  sortBy: string | number;
> 개인적으로 hook은 최대한 최상단 컴포넌트에서 호출하는게 컴포넌트의 상태와 라이프사이클 이벤트를 관리하는게 더 쉽다고 느껴지더라구요!
정말 그 컴포넌트에서만 사용하는거면 내부에서 호출하는게 깔끔하겠지만, 밑으로 더 컴포넌트들이 존재하니까요.

이렇게 생각한 이유가 궁금합니다. 왜냐면 저 이 부분 약간 이해가 안 돼요... 밑에 hook을 위로 최상단 컴포넌트에서 호출한다고 밑으로 더 있는 컴포넌트들이 영향을 안 받는건 아니지 않나요?

저는 비슷한 상황에서 page 단 보다는 사용하는 컴포넌트 측으로 hook을 옮겨서 사용하도록 했거든요. 🤔

2023-07-17 13:26 UTC, ashleysyheo commented on frontend/src/components/Trips/TutorialModal/TutorialModal.tsx
> +  const [modalStatus, setModalStatus] = useState(true);
close를 handleModalClose에 한 번 더 감쌀 필요가 있나요???

2023-07-17 13:26 UTC, ashleysyheo reviewed
🔥

2023-07-17 13:49 UTC, dladncks1217 commented on frontend/src/components/Trips/TripsItem/TripsItem.style.ts
> +    marginRight: Theme.spacer.spacing2,
ㅋㅋㅋㅋㅋㅋ 진짜 도입 해야할거같습니다...😂

2023-07-17 13:49 UTC, dladncks1217 commented on frontend/src/pages/TripsPage.tsx
> +    if (sortSelected === ORDER_BY_REGISTRATION) queryClient.invalidateQueries(['trips']);
흠 그러게요... 내일 한번 이야기해봐요!

2023-07-17 13:49 UTC, dladncks1217 commented on frontend/src/types/trips.ts
> +  description?: string;
듣고보니 그렇군요🤔
null도 포함해야겠어요 ㅎㅎ

2023-07-18 04:52 UTC, dladncks1217 commented on frontend/src/components/Trips/TripsItemList/TripsItemList.tsx
> +  sortBy: string | number;
> 정말 그 컴포넌트에서만 사용하는거면 내부에서 호출하는게 깔끔하겠지만, 밑으로 더 컴포넌트들이 존재하니까요.

음... 이 이야기보다는 그 위에있던`쿼리를 호출할만한 책임이 가장 큰`이 핵심입니다!

데이터 fetch가 같은 컴포넌트에 있게 되면 너무 도메인 종속적인 컴포넌트가 만들어질 것 같습니다.
컴포넌트의 복잡도가 너무 높아진다고 생각하기에, UI와 fetch 로직은 분리되어야 한다고 생각하는데, 어떻게 생각하시나요?

2023-07-18 05:16 UTC, ashleysyheo approved these changes

2023-07-18 05:34 UTC, Dahyeeee approved these changes

2023-07-18 05:43 UTC, merged