닉네임 랜덤 숫자 추가 및 수정 시 닉네임 중복 체크
woowacourse-teams/2023-hang-log pull request #565
Opened 2023-09-12 14:56 UTC by mcodnjs

## 📄 Summary
> #564 

## 🙋🏻 More
> 여러분 고민이 많아요 .. 같이 고민해보려고 .. PR 먼저 올려요 .. 
고민되는 부분은 커멘트에 남겨놓을게요 .. 다들 꼭 답글 달아줘요 ..

2023-09-12 15:02 UTC, mcodnjs commented on backend/src/main/java/hanglog/auth/service/AuthService.java
>      }
Random 인스턴스를 static 하게 관리하는게 좋을거 같은데 어떻게 관리하면 좋을지?

2023-09-12 15:02 UTC, mcodnjs commented on backend/src/main/java/hanglog/auth/service/AuthService.java
> +    }
멤버 생성할 때, 난수를 넣는다고 해도 중복의 가능성이 있을 수 있는데, (중복될 가능성이 낮기도함)
- 무시할지 -> 무시한다면, DB에서 exist로 검사 안하고 unique 제약조건으로 인해 오류가 발생할 수 있음 
- 지금처럼 tryCount로 존재하는지 확인할지

2023-09-12 15:58 UTC, jjongwa requested changes
네 해드렸습니다~

2023-09-12 17:33 UTC, mcodnjs commented on backend/src/main/java/hanglog/auth/service/AuthService.java
> +        }
저는 일관성 있게 모두 4자리 붙이는 편이 좋다인데 다른 사람들 의견도 들어봅시당

2023-09-12 17:39 UTC, mcodnjs commented on backend/src/main/java/hanglog/auth/service/AuthService.java
>      }
맞아요! 저도 이 방법을 인지하고 있었는데, 어떤 로직인지 좀 파악하기 어렵다 ?? 싶었어요 
글고 그냥 0492 이런 값도 하고 싶었어서 .. 근데 그 방법도 좋아요 ㅎㅎ

2023-09-13 00:59 UTC, LJW25 commented on backend/src/main/java/hanglog/auth/service/AuthService.java
> +        }
저도 일관성있게 모두 4자리 한표 하겠습니다

2023-09-13 01:00 UTC, LJW25 commented on backend/src/main/java/hanglog/auth/service/AuthService.java
> +    }
존재하는지 확인 필요하다고 생각합니다. 중복이 허용된다면 난수를 붙이는 이유가 퇴색된다고 느껴져서요!

2023-09-13 01:12 UTC, hgo641 approved these changes
Speed~

2023-09-13 01:12 UTC, hgo641 commented on backend/src/main/java/hanglog/auth/service/AuthService.java
>      }
ㅎㅎ `혹은 또다른 유틸성 클래스에서 생성하고 static 메서드로 불러올 것인지` 좋아요. 랜덤 숫자 모음 생성하는 로직 유틸로 분리하는 거 좋아용

2023-09-13 07:02 UTC, waterricecake commented on backend/src/main/java/hanglog/auth/service/AuthService.java
>      }
`String.format("%04d", random.nextInt(10000))` 이건 어떤가요? 이러면 라온이 말한 `0492`이런 숫자도 나오는데

2023-09-14 17:17 UTC, mcodnjs reviewed
로컬에서 테스트 완 ~ 
<img width="121" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/64852591/7b82dda7-040d-4025-92ca-55fece4d530d">

2023-09-14 17:17 UTC, mcodnjs commented on backend/src/main/java/hanglog/auth/service/AuthService.java
>      }
random 객체를 사용한다면 유틸성 클래스로 분리하려했는데, 아래와 같이 해결가능해서 그냥 AuthService에 넣었습니다 ..!

``` java
private String generateRandomFourDigitCode() {
    final int randomNumber = (int) (Math.random() * 10000);
    return String.format("%04d", randomNumber);
}
```

2023-09-15 00:54 UTC, waterricecake approved these changes

2023-09-15 03:36 UTC, LJW25 approved these changes

2023-09-15 05:29 UTC, jjongwa approved these changes

2023-09-15 06:23 UTC, merged