Trip, Like, PublishedTrip 테이블 생성
woowacourse-teams/2023-hang-log pull request #569
Opened 2023-09-14 04:59 UTC by waterricecake

## 📄 Summary
> #568
엔티티부터 db 마이그레이션 스크립트까지 작성하였습니다.
## 🙋🏻 More
>

2023-09-14 05:25 UTC, waterricecake commented
이거 페키지 분리를 어떻게 해야할지 얘기 해보는 게 좋을 것 같습니다. 일단은 현제 다른 서비스 로직이 없기 때문에 trip 패키지에 두었지만 추후 서비스나 컨트롤러가 추가되면서 분리될 여지가 있다면 이 객체를 사용하던 다른 브랜치들이 컨플릭트가 날수도 있을 것같아 정하고 가는 것이 좋을 것 같습니다.

2023-09-14 11:21 UTC, hgo641 approved these changes

2023-09-14 11:21 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +        this.publishedStatus =publishedStatusType;
한 칸 띄우기~

2023-09-15 00:34 UTC, jjongwa requested changes
전체적으로 클래스마다 정렬 한 번씩 해주세요. 언제까지 숨은 그림 찾기 시킬겁니까ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ
3개월째 지적했는데 아직~~~~~~~~~도 못고친다? 이건 습관의 문제입니다. 안되겠다 이건

금쪽 처방 들어갑니다. PR 올리기 전에 저 불러서 정렬하는거 보여주고 올리세요.
단축키 -> `opt` + `cmd` + `L`
아니면 optimize imports 해도 됩니다.

이제 앞으로의 PR에서 정렬 안한거 확인되면 직접 찾아가서 찐한 협업 경험을 쌓게 해드리겠습니다.

2023-09-15 00:34 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +        this.publishedStatus =publishedStatusType;
ㅋㅋㅋㅋ

2023-09-15 02:09 UTC, mcodnjs commented on backend/src/test/java/hanglog/expense/fixture/TripExpenseFixture.java
> +            new ArrayList<>(),
~~근데 우리 Fixture 쓰고 있나 ..~~

2023-09-15 02:25 UTC, waterricecake commented on backend/src/main/resources/db/migration/V3__Creat_table_published_trip_and_like.sql
> +    id BIGINT NOT NULL AUTO_INCREMENT,
앗.... 이러면 머지 순서 중요해지는데

2023-09-15 02:30 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/domain/Trip.java
> +        this.publishedStatus =publishedStatusType;
😅😅😅😅😅😅😅😅😅😅
[style: 코드 컨벤션 적용](https://github.com/woowacourse-teams/2023-hang-log/pull/569/commits/147931313b2c88660d4bfba788d984b408ba9d8d)
적용.... 완.....

2023-09-15 03:38 UTC, LJW25 commented on backend/src/main/resources/db/migration/V3__Creat_table_published_trip_and_like.sql
> +    id BIGINT NOT NULL AUTO_INCREMENT,
오우...

2023-09-15 03:38 UTC, LJW25 approved these changes

2023-09-15 05:33 UTC, jjongwa approved these changes

2023-09-15 07:01 UTC, merged