커뮤니티 여행 조회 페이지네이션 기능 구현
woowacourse-teams/2023-hang-log pull request #587
Opened 2023-09-19 06:20 UTC by waterricecake

## 📄 Summary
>#578

## 🙋🏻 More
>
pageable을 통해 페이지네이션을 구현하였습니다. 
근데 문제가 첫페이지가 1번부터가 아니라 0으로 시작이여서 이부분을 우리가 처리를 해줄려면 Resolver를 통해 기본 페이지를 1로 시작하게 바꿔주는 방법과 받은 페이지보다 1페이지 적은 페이지를 보내주는 방법 2가지가 있습니다. 일단 빠르게 적용할 수 있는 후자를 선택하였습니다.

2023-09-19 06:22 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/service/CommunityService.java
> +            final boolean isLike = likesRepository.existsByMemberIdAndTrip(accessor.getMemberId(), trip);
이 부분에서 하나 이전의 페이지를 반환하게 적용하였습니다.

2023-09-19 06:57 UTC, LJW25 requested changes
RestDocs...^^ 😊

2023-09-19 06:57 UTC, LJW25 commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/community-controller-test/get-trips-by-page/path-parameters.adoc[]
다시 확인하시고 안되면 찾아오십시오..^^

<img width="859" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/569136c9-68c7-4c7b-bab7-eab319a37fe5">

2023-09-19 06:57 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/service/CommunityService.java
> +        return CommunityTripResponse.of(trip, cities, false, likeCount);
false용 정팩메 만드는거 어때요?

2023-09-19 07:09 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/service/CommunityService.java
> +        return CommunityTripResponse.of(trip, cities, false, likeCount);
부연설명하자면 위에는 member용이고 아래는 guest용이라 둘의 응답이 다르다는 게 메소드명에서 드러나면 좋을 것 같았습니다!

2023-09-19 07:35 UTC, waterricecake commented on backend/src/docs/asciidoc/docs.adoc
> +include::{snippets}/community-controller-test/get-trips-by-page/path-parameters.adoc[]
😅[17847c3](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/17847c39648add3ab8839129f403e954c32bd0dc)

2023-09-19 07:36 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/service/CommunityService.java
> +        return CommunityTripResponse.of(trip, cities, false, likeCount);
저는 차이가 어차피 isLike가 false인지 아닌지의 차이인데 굳이 정팩메를 하나 더 만든다?라는 생각이 드네요

2023-09-19 10:22 UTC, hgo641 requested changes
👍

2023-09-19 10:22 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
> +    Long countPublishedTrip();
얘도 `@Query` 써야하나요?
long countByPublishedStatus(PublishedStatusType publishedStatus); 이렇게는 안되나요? 몰라서 여쭤봅니다!

2023-09-19 10:22 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/dto/response/CommunitySingleTripResponse.java
> +    private final Long likeCount;
authorNickname은 여기 없나요?

2023-09-19 10:22 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +    @DisplayName("로그인 된 상태에서 ")
설명 더 해주세요 ~~

2023-09-19 10:40 UTC, hgo641 commented on backend/src/main/resources/db/migration/V5__Rename_table_like_to_heart.sql
> +ALTER TABLE `like` RENAME `likes`;
얘 파일이름 to_heart에요!

2023-09-19 10:45 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +    @DisplayName("로그인 된 상태에서 ")
[4f2a753](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/4f2a7537c40e3108c2befed5cbc1831a11a93272)

2023-09-19 10:46 UTC, waterricecake commented on backend/src/main/resources/db/migration/V5__Rename_table_like_to_heart.sql
> +ALTER TABLE `like` RENAME `likes`;
[0d3184e](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/0d3184eb95e922b7bd2f33030dd5876f074be86e)

2023-09-19 10:47 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/domain/repository/TripRepository.java
> +    Long countPublishedTrip();
[b9195a2](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/b9195a28624527f035b3bf5d03dfd7728665da3d)

2023-09-19 10:47 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/dto/response/CommunitySingleTripResponse.java
> +    private final Long likeCount;
[4f2a753](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/4f2a7537c40e3108c2befed5cbc1831a11a93272)

2023-09-19 11:08 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/presentation/CommunityController.java
> +    ) {
메소드 앞에 public 실종사건❗️❗️❗️

2023-09-19 11:37 UTC, waterricecake commented on backend/src/main/java/hanglog/trip/presentation/CommunityController.java
> +    ) {
[2e19334](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/2e19334749ecdb2aadac0b0e09f5398d817a38b9)

2023-09-19 11:41 UTC, LJW25 approved these changes
정팩메 아쉽지만? 다른건 다 고쳐져서 일단 어프루브

2023-09-19 11:45 UTC, jjongwa approved these changes
아 너무 만족스럽습니다. 컨벤션에서 건들게 없었어요. 
이게 pr이지 
~~봐 하니까 되잖아~~

그냥 간단한 제안 밖에 없어서 바로 approve 하겠습니다~

2023-09-19 11:45 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +package hanglog.trip.presentation;
여기도 패키지 변경해 주시면 감사하겠습니다.!

2023-09-19 11:45 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +                }
```suggestion
                CommunityTripsResponse.class
```

이렇게 하면 안되는 건가요?
다른 컨트롤러 테스트와 달라서요!

2023-09-19 11:45 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +    }
```suggestion
assertThat(communityTripsResponses).usingRecursiveComparison()
                .isEqualTo(new CommunityTripsResponse(
                        List.of(CommunitySingleTripResponse.of(LONDON_TRIP, CITIES, true, 1L)),
                        1L
                ));
                
                
                
                
                
                
                assertThat(communityTripsResponses).usingRecursiveComparison().isEqualTo(new CommunityTripsResponse(
                List.of(CommunitySingleTripResponse.of(LONDON_TRIP, CITIES, true, 1L)),
                1L
        ));
        
```


이런 식으로 줄여도 괜찮을듯..? (그냥 의견임)

2023-09-19 11:45 UTC, jjongwa commented on backend/src/main/java/hanglog/community/service/CommunityService.java
> +                tripRepository.countTripByPublishedStatus(PublishedStatusType.PUBLISHED) / pageable.getPageSize() + 1;
```suggestion
final Long lastPageIndex = tripRepository.countTripByPublishedStatus(PUBLISHED) / pageable.getPageSize() + 1;
```

PublishedStatusType static import로 줄이고 한줄로 하는것도 이쁠것 같아요.(그냥 의견임)

2023-09-19 11:45 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +                );
```suggestion
        when(communityService.getTripsByPage(any(), any()))
                .thenReturn(new CommunityTripsResponse(
                        List.of(CommunitySingleTripResponse.of(LONDON_TRIP, CITIES, true, 1L)),
                        1L
                ));
```

여기도 이하 동문입니다. (그냥 의견이라는 뜻)

2023-09-19 11:48 UTC, jjongwa commented
아 앞에서 이미 다 고쳤었구나.!

그래도 만족스럽습니다 수고하셨어요 달리는기차에바퀴를교체하다

2023-09-19 12:07 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +                }
오 저는 TripControllerTest에 있는 getTrips()의 테스트를 따왔던건데... 개인적으론 CommunityTripsResponse.class를 선호하니 디노의 의견을 체택하겠슴다

2023-09-19 12:13 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +                );
[cbf2455](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/cbf2455b4eff9fb3e879c002b406b53ea3945a15)

2023-09-19 12:13 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +    }
[cbf2455](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/cbf2455b4eff9fb3e879c002b406b53ea3945a15)

2023-09-19 12:13 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +                }
[cbf2455](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/cbf2455b4eff9fb3e879c002b406b53ea3945a15)

2023-09-19 12:13 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/presentation/CommunityControllerTest.java
> +package hanglog.trip.presentation;
[cbf2455](https://github.com/woowacourse-teams/2023-hang-log/pull/587/commits/cbf2455b4eff9fb3e879c002b406b53ea3945a15)

2023-09-20 01:57 UTC, mcodnjs requested changes
굿굿 수고하셨씁니다 
네이밍만 조금 더 고민해보면 좋을거 같아요 ~! 
API Response 변경 때문에 Request Change 걸어놓겠습니다 ~~~ 
RestDocs변경도 잊지말기 !! (feat. 25)

2023-09-20 01:57 UTC, mcodnjs commented on backend/src/main/java/hanglog/community/domain/repository/LikesRepository.java
> +    boolean existsByMemberIdAndTrip(final Long memberID, final Trip trip);
오타인가 .. ? `memberId`로 수정하면 좋을거 같습니돠

2023-09-20 01:57 UTC, mcodnjs commented on backend/src/main/java/hanglog/community/domain/repository/LikesRepository.java
> +    boolean existsByMemberIdAndTrip(final Long memberID, final Trip trip);
tripId로 조회하는건 어떨지 ,,

2023-09-20 01:57 UTC, mcodnjs commented on backend/src/main/java/hanglog/community/presentation/CommunityController.java
> +        final CommunityTripsResponse tripResponses = communityService.getTripsByPage(accessor, pageable);
변수명 tripResponses 대신 CommunityTripsResponse를 제안하려했지만 .. 
현재 CommunityTripsResponse에 Trip인지 Trips인지 잘 구분이 안가는거 같아요
그래서 single을 쓰신거 같은데 어떤 Response인지 파악하는데 조금 오래 걸리네요 ㅠㅠ

lastPageIndex를 주기 위함이라면, 
`CommunityAllTripResponse` ,`CommunityTripListResponse`, `CommunityTripWithLastPageIndexResponse`, `CommunityTripWithPagebleResponse`, `CommunityTripPagingResponse`
좀 그렇죠 ? 반박 시 대안이라 대안을 좀 내봤어요 ^^ ..

2023-09-20 08:56 UTC, mcodnjs approved these changes

2023-09-20 09:02 UTC, waterricecake commented on backend/src/main/java/hanglog/community/dto/response/CommunitySingleTripResponse.java
> +    private final Long likeCount;
이거 내 여행 조회 수정에서 writenResponse있어서 그거 pr되면 rebase하고 사용하려고 합니다...

2023-09-20 09:04 UTC, waterricecake commented on backend/src/main/java/hanglog/community/presentation/CommunityController.java
> +        final CommunityTripsResponse tripResponses = communityService.getTripsByPage(accessor, pageable);
저도 처음에 Trips 사용하려고 했지만? 라온의 말데로 너무 구분이 안갔다.... 저는 `CommunityTripWithLastPageIndexResponse`가 어차피 다 긴데 명확한것 같아 마음에 듭니다.

2023-09-21 03:32 UTC, hgo641 commented on backend/src/main/java/hanglog/community/presentation/CommunityController.java
> +        final CommunityTripsResponse tripResponses = communityService.getTripsByPage(accessor, pageable);
`CommunityAllTripResponse` 이거 좋네요
single 어쩌구는 `CommunityTripResponse`로 바꿔도 될듯

2023-09-21 04:21 UTC, mcodnjs commented on backend/src/main/java/hanglog/community/service/CommunityService.java
> +            final boolean isLike = likesRepository.existsByMemberIdAndTripId(1L, trip.getId());
여기 memberId에 1L을 박은 이유가 있나용 ?

2023-09-21 04:26 UTC, waterricecake commented on backend/src/main/java/hanglog/community/service/CommunityService.java
> +            final boolean isLike = likesRepository.existsByMemberIdAndTripId(1L, trip.getId());
아 아까 db테스트 하다가;;;;;;;;;;;;;;; 대박.....

2023-09-21 04:28 UTC, waterricecake commented on backend/src/main/java/hanglog/community/service/CommunityService.java
> +            final boolean isLike = likesRepository.existsByMemberIdAndTripId(1L, trip.getId());
아 그거... db로 직접 테스트하다가 멤버 고정하고 할려고 바꾼건데;;; 실수했네요;;;; 수정하였습니다.

2023-09-21 04:30 UTC, merged