전체 Item 조회 기능 구현
woowacourse-teams/2023-hang-log pull request #63
Opened 2023-07-17 12:58 UTC by hgo641

## 📄 Summary
> #48
`ItemService`에 전체 `Item`을 조회하는 `getItems` 메소드 구현

## 🙋🏻 More
> `ItemResponse` 정팩메로 생성하고 있는데 이거 괜찮나요? `ItemResponse` 내부에 있는 `PlaceResponse`랑 ExpenseResponse`도 정팩매로 생성중입니다... 더 좋은 방법이 생각난다면? 코멘트 plz~

2023-07-17 13:09 UTC, jjongwa approved these changes
수고수고

2023-07-17 13:09 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
> +    public static Item TAXI_ITEM = new Item(
final?

2023-07-17 13:09 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
> +        List<ItemResponse> items = itemService.getItems();
final?

2023-07-17 13:32 UTC, LJW25 requested changes
드디어 찾았다 ItemResponse

수고하셨슴다 홍고 🍊

2023-07-17 13:32 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/presentation/dto/response/CategoryResponse.java
> +    public static CategoryResponse of(Category category) {
파라미터 final

2023-07-17 13:32 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/presentation/dto/response/ExpenseResponse.java
> +    public static ExpenseResponse of(Expense expense) {
파라미터 final 22

2023-07-17 13:32 UTC, LJW25 commented on backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
> +        assertThat(items.get(1)).usingRecursiveComparison().isEqualTo(ItemResponse.of(ItemFixture.TAXI_ITEM));
assertAll이나 assertSoftly로 묶는건 어떤가요?

2023-07-17 13:52 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
> +        assertThat(items.get(1)).usingRecursiveComparison().isEqualTo(ItemResponse.of(ItemFixture.TAXI_ITEM));
softly 적용완!

2023-07-17 13:53 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/dto/response/CategoryResponse.java
> +    public static CategoryResponse of(Category category) {
앗 차 final을 까먹어부랏스~~~~

2023-07-17 13:53 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/fixture/ItemFixture.java
> +    public static Item TAXI_ITEM = new Item(
크아악

2023-07-17 13:53 UTC, hgo641 commented on backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
> +        List<ItemResponse> items = itemService.getItems();
thx

2023-07-18 01:01 UTC, waterricecake reviewed
수고하셨습니다 홍고

2023-07-18 01:56 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/presentation/dto/response/CategoryResponse.java
> +    private final Long id;
thx

2023-07-18 02:31 UTC, waterricecake approved these changes

2023-07-18 03:01 UTC, LJW25 approved these changes

2023-07-18 03:47 UTC, merged