아이템 생성&수정 쿼리 개선
woowacourse-teams/2023-hang-log pull request #693
Opened 2023-10-10 17:38 UTC by hgo641

## 📄 Summary
> 

## 🙋🏻 More
>
close #690

2023-10-11 04:43 UTC, jjongwa requested changes
오우 고생하셨습니다 홍고
바뀐게 꽤 많네요..
일단 논의하고 싶은 사항 몇개 있어서 남겼습니다..

2023-10-11 04:43 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/domain/Expense.java
> +    }
여기서 매개변수로 Expense을 받지 말고,
curreny와 amount와 category를 받아서 비교하면 어떨까요?
인자의 null check는 서비스 단에서 하구요.!

Expense가 Expense을 받아서 비교하는게 살짝 어색하게 느껴집니다..



+그리고 getter 안쓰고 expense.currency 하면 인자로 받은 expense의 currency가 나오는건가요? 뭔가 당연한거 같으면서도 되게 어색하네요 왤케 낯설지....?

2023-10-11 04:43 UTC, jjongwa commented on backend/src/main/java/hanglog/image/domain/repository/CustomImageRepositoryImpl.java
> +                """;
올

2023-10-11 04:43 UTC, jjongwa commented on backend/src/main/java/hanglog/image/domain/repository/ImageRepository.java
> +    void deleteAll(@Param("images") final List<Image> images);
지금 해당 로직에 대한 쿼리가 
`delete from image where id in (95,96) and (image.status = 'USABLE');`
이렇게 나오는거죠?

image 객체를 넣어도 알아서 where절에 id로만 비교하는군요.. 신기하네요

그리고 image.status = 'USABLE' 조건이 추가되는건 custom이 아닌 JPA 레포라서 그런거 같은데,
굳이 where절에 index인 id로 검색하고 추가적으로 status를 확인하는게 불필요하다고 느껴지기도 합니다..

방법은 이걸 custom으로 바꾸는 건데 지금 보니까 imagRepository를 쓰는데가 ItemService밖에 없네요..?
그러면 그냥 custom으로 바꾸고 imageRepository를 삭제하는게 조금 더 깔끔할지도..?

2023-10-11 04:43 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/domain/repository/DayLogRepository.java
> +    Optional<DayLog> findWithItemDetailsById(@Param("dayLogId") final Long dayLogId);
굉장합니다 정말

2023-10-11 16:13 UTC, hgo641 commented on backend/src/main/java/hanglog/image/domain/repository/ImageRepository.java
> +    void deleteAll(@Param("images") final List<Image> images);
ae47c08a871dda00d50d9e85a9195046a69a8850

2023-10-11 16:19 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/domain/Expense.java
> +    }
어떻게 개선할 지 고민해봤는데, 인자를 전부 받는 것보다 Expense자체를 받아오는 게 더 깔끔해서... 고민이 되는군요
차라리 `isDifferent` 메서드 대신 `equals`를 오버라이딩해서 사용하면 덜 어색하게 느껴질까요?
서비스에서 `!equals(expense)` 이렇게 !붙는 게 싫어서 `isDifferent` 메서드를 만들었는데, 어색하게 느껴진다면 차라리 `equals`를 그대로 사용하면 될까... 싶네요
물론 이 경우엔 `Expense`가 값객체처럼 되겠지만, `Expense`는 값객체로 사용해도 된다고 생각하기 때문에 . . .

2023-10-12 00:54 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/domain/Expense.java
> +    }
아 그러게요..
전 equals 오버라이딩을 하는 편이 조금 더 익숙하게 느껴지는데,
이건 다른 분들의 의견도 들어보는게 좋을 것 같네요.!

2023-10-12 01:33 UTC, LJW25 commented on backend/src/main/java/hanglog/expense/domain/Expense.java
> +    }
expense..가계부가 아니라 item의 expense라면..값객체..Ok..

2023-10-12 01:36 UTC, LJW25 reviewed
궁금한게있어서 어프루브는 안하고 코멘트

2023-10-12 01:36 UTC, LJW25 commented on backend/src/main/java/hanglog/image/domain/repository/CustomImageRepositoryImpl.java
> +    }
저 이거 제커밋에서 만들었는데 히히
근데 JPA 안쓰고 Custom으로 만든 이유가 있나요?
저는 JPA에서 쿼리짜서 구현했어서 궁금합니당

2023-10-12 02:03 UTC, hgo641 commented on backend/src/main/java/hanglog/image/domain/repository/CustomImageRepositoryImpl.java
> +    }
그것은 바로 위에서 디노가 바꿔달라고 했기 때문입니다. . .
https://github.com/woowacourse-teams/2023-hang-log/pull/693#discussion_r1354053136

2023-10-12 02:05 UTC, hgo641 commented on backend/src/main/java/hanglog/image/domain/repository/CustomImageRepositoryImpl.java
> +    }
원래 JPA로 했었는데 위에서 디노가 말한 걸 듣고 설득당했습니다 😄
https://github.com/woowacourse-teams/2023-hang-log/pull/693#discussion_r1354053136

2023-10-12 03:43 UTC, LJW25 commented on backend/src/main/java/hanglog/image/domain/repository/CustomImageRepositoryImpl.java
> +    }
3자대면 하시죠. 지금 이대로면 제거랑 중복코드 됨 헤헤
일단 제 코드에서는 ImageRepository가 더 자연스럽기 때문에..전 ImageRepository 주장 예정..

2023-10-12 04:40 UTC, mcodnjs approved these changes
홍고홍고생하셨습니다 🍊🍊🍊🍊🍊🍊
ImageRepository은 조금 더 얘기해보는걸로!

2023-10-12 04:40 UTC, mcodnjs commented on backend/src/main/java/hanglog/trip/service/ItemService.java
>          }
별건 아니고 .. ! 이런 로직은 어떨지 제안합니다 ..! 
어렵네요 .. 한참생각함 (틀릴수도있음)

```java
final Place updatedPlace = makeUpdatedPlace(itemUpdateRequest, item);

private Place makeUpdatedPlace(final ItemUpdateRequest itemUpdateRequest, final Item item) {
    if (item.getItemType() == ItemType.NON_SPOT) {
        if (itemUpdateRequest.getItemType() && itemUpdateRequest.getIsPlaceUpdated()) { // non_spot -> spot
            return makePlace(itemUpdateRequest.getPlace());
        }
        return null; // non_spot -> nothing
    }

    final Place originalPlace = item.getPlace();
    if (item.getItemType() == ItemType.SPOT) {
        if (itemUpdateRequest.getItemType() && !itemUpdateRequest.getIsPlaceUpdated()) { // spot -> no update
            return originalPlace;
        }
        
        placeRepository.delete(originalPlace);
        if (itemUpdateRequest.getItemType() && itemUpdateRequest.getIsPlaceUpdated()) {
            return makePlace(itemUpdateRequest.getPlace()); // spot -> new spot
        }
        return null;  // spot -> non_spot
    }
}
```

2023-10-13 06:32 UTC, closed without merging