단일 여행, 아이템 삭제 쿼리 개선
woowacourse-teams/2023-hang-log pull request #700
Opened 2023-10-11 14:00 UTC by LJW25

## 📄 Summary
 #688  
- 단일 여행 삭제 쿼리 개선
- 아이템 삭제 쿼리 개선

## 🙋🏻 More

세부 결과는 노션 StudyLog의 삭제쿼리개선 참고

### 1. 단일여행 삭제 쿼리 개선

**queryCounts=3731 -> queryCounts=14**
> 실험 대상: day 60일, item 각 day당 20개, 각 item에 spot, expense 포함 (이미지 포함x)

개선 전
<img width="931" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/d4559d88-528f-46f0-9b41-67f5b5c53a4b">

개선 후
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/0bcd9353-3561-43ce-8e87-6e0ab3741d4f)

### 2. 아이템 삭제 쿼리 개선

**queryCounts=14 -> queryCounts=7**
> 실험 대상: 장소, 경비, 이미지 5장 포함된 item

개선 전
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/981e9677-5268-4385-afa7-5cdc808df66b)

개선 후
멤버검증 2 + item 조회 1 + image, place, expense 각각 있으면 1 (없으면 0) + item 삭제 1
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/ca94fda4-3ee9-487e-bafa-7fd81b47e24a)
![image](https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/cb32e89c-66a3-44a4-ac1c-916fe7650c76)

2023-10-11 15:42 UTC, jjongwa reviewed
테스트가 터져서 내일 리뷰를 남겨야 하나 생각하다가 
코드가 그리 많이 바뀔것 같진 않아서 간단하게 리뷰 하려고 했는데

딱히 건들게 없네요.. 코드가 분열한 느낌 ~~Like 메타몽~~

간단하게 감상평 정도만 적고 갑니다..

2023-10-11 15:42 UTC, jjongwa commented on backend/src/main/java/hanglog/listener/DeleteEventListener.java
> +        tripCityRepository.deleteAllByTripId(event.getTripId());
시원하군요

2023-10-11 15:42 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/ItemService.java
> +    private final ExpenseRepository expenseRepository;
itemService도 점점 비대해 지는군요..

2023-10-11 15:42 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        }
해당 트립이 존재하는지는 Accessor에서 한 번 검증하고 있는거 아닌가요오?
(Accessor 로직 아직 제대로 파악 못함..)

2023-10-11 15:42 UTC, jjongwa commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        tripRepository.deleteById(tripId);
멋집니다

2023-10-11 15:42 UTC, jjongwa commented on backend/src/test/java/hanglog/member/event/DeleteEventListenerTest.java
> +    }
레전드 테스트

2023-10-11 15:42 UTC, jjongwa commented on backend/src/test/java/hanglog/trip/service/TripServiceTest.java
> +        given(tripRepository.existsById(invalidTripId)).willReturn(false);
레전드 스터빙

2023-10-12 01:00 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/service/TripService.java
> +        }
레전드

2023-10-12 01:34 UTC, jjongwa approved these changes
👍👍👍

2023-10-12 02:20 UTC, hgo641 requested changes
이오고생고생하셨습니다 studyLog오랜만이네요 키키킥 👍

2023-10-12 02:20 UTC, hgo641 commented on backend/src/main/java/hanglog/trip/infrastructure/CustomDayLogRepositoryImpl.java
> +    }
얘는 jpql로 안하고 jdbcTemplate쓰신 이유가 있나요? 궁금!
`@Query("SELECT dayLog FROM DayLog dayLog WHERE dayLog.trip IN :trips")`

2023-10-12 03:40 UTC, LJW25 commented on backend/src/main/java/hanglog/trip/infrastructure/CustomDayLogRepositoryImpl.java
> +    }
trip 여러개의 dayLog를 한번에 가져오는 메소드인 `findDayLogIdsByTripIds`가 jdbcTemplate으로 구현이 되어 있어서, 통일성 있게 가져가려고 현재와 같은 구조로 만들었습니당

2023-10-13 01:14 UTC, closed without merging