단일 여행 조회 및 경비 조회 api 개선
woowacourse-teams/2023-hang-log pull request #711
Opened 2023-10-13 08:30 UTC by waterricecake

## 📄 Summary
> #692

1. 공유된 단일 여행 조회 api 개선

      기존 : 6번

      - sharedtrip 조회 (3번)
      - trip 조회 (2번)
      - city 조회

      개선 : 3번
      - sharedtrip 조회
      - trip 조회
      - city 조회

2. 공개된 단일 여행 조회 api 개선

      기존 : 9번

      - 토큰 확인
      - trip 조회
      - trip 조회
      - publishedTrip 공개 날짜 조회
      - 좋아요 갯수 조회
      - 좋아요 조회 (멤버가 좋아하는지)
      - 도시 조회
      - 도시 조회 (tripCity가 city 참조)
      - member (trip이 member 참조) 조회
      
      개선 : 5번
      - 로그인
      - trip 조회
      - 도시 조회
      - publishedTrip 조회
      - 좋아요 갯수 및 좋아요 여부 조회

3. 경비 조회 api 개선

     기존 : 7 ~ 6
     - 토큰 확인
     - 본인 여행 확인
     - 여행 조회
     - 환율 조회 (날짜로 부터 가장 최신값)
        - 실패시 : 환율 조회 (가장 오래된 값)
     - 카테고리 목록 조회
     - 도시 조회

      개선 : 5
      - 토큰 확인
      - 본인 여행 확인
      - 여행조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
      - 도시 조회

4. 공유된 여행 경비 조회 api 개선

      기존 : 6 ~ 5
      - 공유여행 조회
      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
          - 실패시 : 환율 조회 ( 가장 오래된 값)
      - 카테고리 목록 조회
      - 도시 조회

      개선 : 4
      - 공유여행 조회
      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
      - 도시 조회

5. 공개된 여행 경비 조회 api 개선

     기존 : 5 ~ 4

      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
          - 실패시 : 환율 조회 ( 가장 오래된 값)
      - 카테고리 목록 조회
      - 도시 조회

      개선 : 4
      - 공유여행 조회
      - 여행 조회
      - 환율 조회 ( 날짜로 부터 가장 최신값)
      - 도시 조회

## 🙋🏻 More
>

2023-10-13 08:32 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +    }
어플리케이션 실행 후 최초 1회는 카테고리에서 경비 카테고리 목록을 조회하고 그 이후에는 static으로 가지고 있어서 평상시에는 요청이 없습니다.

2023-10-13 08:32 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +        return currency;
어플리케이션 실행 후 최초 1회는 환욜에서 가장 오래된 환율을 조회하고 그 이후에는 static으로 가지고 있어서 평상시에는 요청이 없습니다.

2023-10-13 08:47 UTC, jjongwa approved these changes
수고하셨습니당

2023-10-13 08:47 UTC, jjongwa commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +                categoryAmounts.put(category, categoryAmount.add(KRWAmount));
```
dayLog.getItems().stream()
      .map(item -> Optional.ofNullable(item.getExpense()))
      .filter(Optional::isPresent)
      .forEach(expense -> {
          final Amount KRWAmount = changeToKRW(expense.get(), currency);
          final Amount dayLogAmount = dayLogAmounts.get(dayLog);
          dayLogAmounts.put(dayLog, dayLogAmount.add(KRWAmount));
          final Category category = expense.get().getCategory();
          final Amount categoryAmount = categoryAmounts.get(category);
          categoryAmounts.put(category, categoryAmount.add(KRWAmount));
      });
```

이런식도 가능하긴 할듯

2023-10-13 08:47 UTC, jjongwa commented on backend/src/main/java/hanglog/category/domain/DefaultCategories.java
> +    }
요런 setter 네이밍 관련 부분은 다른 팀원들 의견 한 번 들어 봅시당

2023-10-13 08:55 UTC, LJW25 commented on backend/src/main/java/hanglog/category/domain/DefaultCategories.java
> +    }
저는 set 상과없다고 생각하는데 그것보다 `setDefaultExpenseCategories`면 더 좋겠다는 생각.

그런데..여기는..final...왜..또..없지..?

2023-10-13 09:01 UTC, LJW25 approved these changes
사소한 수정사항들이라 어프루브하겠습니다. 한번씩 봐주세용.

2023-10-13 09:01 UTC, LJW25 commented on backend/src/main/java/hanglog/currency/domain/DefaultCurrency.java
> +    }
여기도 final 없음요

2023-10-13 09:03 UTC, waterricecake commented on backend/src/main/java/hanglog/currency/domain/DefaultCurrency.java
> +    }
[50da444](https://github.com/woowacourse-teams/2023-hang-log/pull/711/commits/50da4440b9118137bdef94a5afe0ff3243da9b76)

2023-10-13 09:21 UTC, hgo641 requested changes
달리고생고생하셨습니다~~~

2023-10-13 09:21 UTC, hgo641 commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +        return currency;
`DefaultCurrency` 클래스를 따로 만드는 대신, 기존에 `Currency`를 관리하는 클래스에서 static field를 만들고 set하는 건 어떨까요?

`DefaultCategories`도... `Expense`에 static field로 두는 거 나쁘지 않을지도?

꼭 변경하자! 는 아니긴 합니다 ㅎㅎㅎ 편하게 반영해주세요!

2023-10-13 09:21 UTC, hgo641 commented on backend/src/main/java/hanglog/category/domain/DefaultCategories.java
> +public class DefaultCategories {
비용 카테고리만 관리하고 있어서 이름이  `ExpenseCategories` 여도 좋을 것 같아요.
메서드 이름은 `getDefaultCategories()`!

2023-10-13 09:22 UTC, waterricecake commented on backend/src/main/java/hanglog/category/domain/DefaultCategories.java
> +    }
아 진짜 대단....

[50da444](https://github.com/woowacourse-teams/2023-hang-log/pull/711/commits/50da4440b9118137bdef94a5afe0ff3243da9b76)

2023-10-13 11:14 UTC, mcodnjs requested changes
리달리달리 고생하셨습니다 !! 
코멘트 남긴거 확인 부탁드리겠습니다 🙃 
혹시 코멘트나 반영이 완료됐다면 슬랙으로 한번 더 말씀 주시면 빠르게 다시 확인하겠습니다 :)

2023-10-13 11:14 UTC, mcodnjs commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +    }
```java
final Optional<List<Category>> expenseCategories = DefaultCategories.getExpenseCategories();
```

1. 저 잘 이해가 안가서 그러는데 ..! 혹시 이 부분을 `Optional<List<Category>> ` 로 받으신 이유가 있나요 ?! 
List가 비어있을 경우, empty List가 오는게 맞다는 생각이 들어서요 ..!!! 

2. 그리고 이 로직이 경비 카테고리 == 음식, 숙박, 교통, 문화 등등을 가져오는 로직이 맞을까용 ?

2023-10-13 11:17 UTC, waterricecake commented on backend/src/test/java/hanglog/expense/service/ExpenseServiceTest.java
> +        lenient().when(currencyRepository.findTopByOrderByDateAsc())
아 이게 단일 테스트 실행할때 초기 oldestCurrency와 expencecategories 가 없어서 실행이 되지만 테스트 전체를 돌릴때 해당 스터빙이 되지 않아 불필요한 스터빙을 했다고 스프링 단에서 예외를 실행시킵니다. 그래서 단일 테스트를 실행시키기 위해서 추가하엿습니다.

2023-10-13 11:19 UTC, waterricecake commented on backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
> -
아 이거 기현상 분명히 이거 위에 expenseRepository(58번쨰줄) 있어서 빨간줄뜨는데 이번에 pull당기니까 있더라고요? 지금 dev확인해보시면 2개가 있어요. 근데 왜 테스트가 통과됬는지 의문이네요. 그래서 일단 삭제했스빈다.

2023-10-13 12:06 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +    }
>저 잘 이해가 안가서 그러는데 ..! 혹시 이 부분을 Optional<List<Category>>  로 받으신 이유가 있나요 ?!
List가 비어있을 경우, empty List가 오는게 맞다는 생각이 들어서요 ..!!!

DefaultCategories가 일종의 일급 컬랙션입니다. 근데 static으로 내부에 ExpenseCategories를 가지고 있어 이를 외부에서 주입시켜 줄려고 final이 아니게 하였습니다. 그래서 spring이 구동된 후 한번도 해당 객체를 불러오지 않았다면 null값을 가지고 있어서 Optional로 햇습니다.

>그리고 이 로직이 경비 카테고리 == 음식, 숙박, 교통, 문화 등등을 가져오는 로직이 맞을까용 ?

네 맞아요! 100, 200, 300, 400, 500, 600번의 경비카테고리를 가져오는 로직이 맞습니다. 가져온 후에 이를 DefaultCategories에 넣어서 싱글톤으로 관리합니다. 때문에 한번 가져오게 되면 이후에는 다시 요청을 안보내게 되는 것입니다.

2023-10-13 12:40 UTC, mcodnjs commented on backend/src/test/java/hanglog/trip/service/ItemServiceTest.java
> -
아니 .. 레전드 진짜 이상하네 ..  제 PR에서 테스트 터지길래 .. 아래 추가했는데 뭐지 .. ...

2023-10-13 12:59 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +        return currency;
이것도 다같이 얘기해봐야할 것 같은데 다들 의견이 달라요....

2023-10-13 12:59 UTC, waterricecake commented on backend/src/main/java/hanglog/category/domain/DefaultCategories.java
> +public class DefaultCategories {
이것도 의견이 달라서 다같이 얘기해봐야겠네요

2023-10-13 13:14 UTC, mcodnjs commented on backend/src/main/java/hanglog/category/domain/DefaultCategories.java
> +public class DefaultCategories {
나도 이거 좋아 
static 메서드라서 그냥 get()만 써도 될거 같아요 ㅎㅎ 근데 대신 set()보단 init()이 좋을지도 ? 
```
ExpenseCategories.get()
ExpenseCategories.init()
```

2023-10-13 14:02 UTC, waterricecake commented on backend/src/main/java/hanglog/category/domain/DefaultCategories.java
> +public class DefaultCategories {
[0946927](https://github.com/woowacourse-teams/2023-hang-log/pull/711/commits/094692789191a29e9cccb9adf190630cbfdd3acd)

2023-10-13 14:02 UTC, waterricecake commented on backend/src/main/java/hanglog/expense/service/ExpenseService.java
> +        return currency;
[0946927](https://github.com/woowacourse-teams/2023-hang-log/pull/711/commits/094692789191a29e9cccb9adf190630cbfdd3acd)

2023-10-14 04:47 UTC, hgo641 commented
.

2023-10-14 04:48 UTC, hgo641 approved these changes

2023-10-14 05:33 UTC, mcodnjs approved these changes

2023-10-14 05:34 UTC, merged