DeleteEventListener 내부 로직 비동기 처리
woowacourse-teams/2023-hang-log pull request #748
Opened 2023-11-06 12:54 UTC by jjongwa

## 📄 Summary
> AsyncDeleteProcessor 라는걸 만들었습니다.. 네이밍은 잘 모르겠어서 지선생님께 맡겼습니다..
이렇게 말고 각 서비스에 delete 메서드를 만들고 `@Async` 를 붙이는 방법도 생각해 봤는데, 
그것보단 AsyncDeleteProcessor라는 클래스를 만들어 관리하는게 조금 더 보기 편하지 않을까 라는 생각이 들어서 
이렇게 진행해 봤습니다.
질문 반박 뭐든 만관부

## 🙋🏻 More
> close #747

2023-11-06 12:58 UTC, LJW25 reviewed
이런건 어디서 배워오셨죠 디노

2023-11-06 12:58 UTC, LJW25 commented on backend/src/main/java/hanglog/listener/DeleteEventListener.java
> +        asyncDeleteProcessor.deleteItems(itemIds);
Item에 DayLogId ForeignKey 걸려있는데 데이로그 먼저 삭제해도 되나요?! 헷갈려서 물어봄

2023-11-06 13:16 UTC, hgo641 requested changes
디 노 짱

2023-11-06 13:28 UTC, jjongwa commented on backend/src/main/java/hanglog/listener/DeleteEventListener.java
> +        asyncDeleteProcessor.deleteItems(itemIds);
Soft Delete는 무적입니다

2023-11-06 13:30 UTC, jjongwa commented on backend/src/main/java/hanglog/listener/DeleteEventListener.java
> +    @TransactionalEventListener
저번에 실험하다가 붙여놓고 까먹었습니다..
대충 요약하면
<img width="518" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/77482065/564a1a80-833d-4b25-895e-918ba1c17263">
이런데 그냥 디폴트 해놔도 될듯...!

2023-11-06 13:35 UTC, hgo641 commented on backend/src/main/java/hanglog/listener/DeleteEventListener.java
> +        asyncDeleteProcessor.deleteItems(itemIds);
이거 개발자가 신경 잘 써야겠네요 ㅋㅋㅜ 잘하면 죽은 데이로그에 살아있는 아이템 만들 수 있겠네

2023-11-06 13:38 UTC, jjongwa commented on backend/src/main/java/hanglog/listener/AsyncDeleteProcessor.java
> +public class AsyncDeleteProcessor {
1. 어싱크 요놈은 내부 메서드에서 못붙입니다.. 그래서 이런 짓을 해버림

2. 날카로운 지적입니다.
그래서 다른 방법이 각각의 서비스에다 메서드를 만든 다음 어싱크 붙여서 해당 메서드를 리스너에서 호출하는 건데, 
위에 말한대로 가독성 측면에서 별로인거 같구,
서비스에 갑자기 어싱크 하나 띡 달려있는 메서드 있으면 이상한거 같기도 하고 그래서 고민입니다...
그리고 또 다른 고민은 이렇게 안하면 리스너에서 Repository랑 Service 모두 의존하고 있는 형식이라(사실 지금도 이름만 다르지 같은 상황이긴 함) 그것도 좀 걸리긴 했어요..

2023-11-06 13:39 UTC, LJW25 commented on backend/src/main/java/hanglog/listener/DeleteEventListener.java
> +        asyncDeleteProcessor.deleteItems(itemIds);
와우 soft Delete를 생각안했네 엄청나군요..

2023-11-06 13:39 UTC, LJW25 approved these changes

2023-11-07 05:24 UTC, hgo641 commented on backend/src/main/java/hanglog/listener/AsyncDeleteProcessor.java
> +public class AsyncDeleteProcessor {
굉장한 고민을 하셨군요 디노! ! ! 역시 리더 디노입니다!!! 더 좋은 구조를 고민해보겠습니다! ! !

2023-11-12 07:01 UTC, hgo641 commented on backend/src/main/java/hanglog/listener/DeleteEventListener.java
> +    @TransactionalEventListener
현재 메서드에 `@Transactional`이 붙어있으니 무조건 트랜잭션이 있는 상태에서 이벤트를 처리하므로 상관이 없다는 뜻 맞죠?  👍

2023-11-12 07:02 UTC, hgo641 approved these changes

2023-11-12 07:05 UTC, hgo641 approved these changes

2023-11-12 07:05 UTC, hgo641 commented on backend/src/main/java/hanglog/listener/TransactionalDeleteProcessor.java
> +public class TransactionalDeleteProcessor {
특정한 로직을 transactional하게 delete해준다는 invoker느낌이 강해지는 것 같네요! 이젠 얘한테 void타입의 delete로직을 수행하는 함수형인터페이스를 넘겨줘서 실행해도 괜찮겠다는 생각이 ......... 들었습니다...

2023-11-13 05:31 UTC, waterricecake approved these changes

2023-11-13 05:31 UTC, waterricecake commented on backend/src/main/java/hanglog/listener/TransactionalDeleteProcessor.java
> +public class TransactionalDeleteProcessor {
이런 느낌일까요?
```java
    public void invoke(final Long memberId, final DeleteInvoker invoker) {
        tripDeleteInvoker.delete(memberId, tripRepository);
    }
````
- 함수 호출시
```java
transactionalDeleteProcessor
     .invoke(
           event.getMemberId(),
          (Long memberId, TripRepository repository) -> repository.deleteByMemberId(memberId)
);
```

2023-11-23 05:29 UTC, hgo641 commented on backend/src/main/java/hanglog/listener/TransactionalDeleteProcessor.java
> +public class TransactionalDeleteProcessor {
굉장합니다!

2024-03-19 15:18 UTC, closed without merging