이미지 리스트 업로드 병렬 처리로 변경 및 롤백 기능 추가
woowacourse-teams/2023-hang-log pull request #756
Opened 2023-11-22 11:34 UTC by hgo641

## 📄 Summary
> close #755 

## 🙋🏻 More
> 아자자자자!!! 매우 간단하고 귀여운 PR 등장! 많관부!

2023-11-22 15:12 UTC, jjongwa requested changes

2023-11-22 15:12 UTC, jjongwa commented on backend/src/main/java/hanglog/image/infrastructure/ImageUploader.java
> +        List<CompletableFuture<String>> imageUploadsFuture = imageFiles.stream()
final 안되는건가요

2023-11-22 15:12 UTC, jjongwa commented on backend/src/main/java/hanglog/image/infrastructure/ImageUploader.java
> +        List<String> fileNames = new ArrayList<>();
ditto

2023-11-22 17:58 UTC, hgo641 commented on backend/src/main/java/hanglog/image/infrastructure/ImageUploader.java
> +        List<CompletableFuture<String>> imageUploadsFuture = imageFiles.stream()
후하하하하하!!!!!!!!

2023-11-22 17:58 UTC, hgo641 commented on backend/src/main/java/hanglog/image/infrastructure/ImageUploader.java
> +        List<String> fileNames = new ArrayList<>();
후하하하하하하하하하!!!!!!!!!!!!!!!!!!!1 새맥북에게 final의 중요성을 일깨워주고오겠습니다아ㅏㅏ아ㅏ

2023-11-28 05:14 UTC, waterricecake approved these changes

2023-11-28 11:25 UTC, LJW25 approved these changes

2024-04-23 18:12 UTC, merged