관리자 기능 백엔드 구현
woowacourse-teams/2023-hang-log pull request #780
Opened 2024-01-20 12:57 UTC by LJW25

## 📄 Summary
> #778 

## 🙋🏻 More
> 그..욕심내다보니..상당히 거대한 녀석이 만들어져버렸습니다...보기 번거로우시겠지만..리뷰부탁드립니다..부디..
상세한 PR 메세지는 다시 작성하겠습니다..커밋 내역 쪼개서 설명 달아놓겠습니다..

2024-01-21 13:27 UTC, jjongwa commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security'
스프링 시큐리티를 추가했군요! 
사용한 이유는 비밀번호 암호화를 위해서인가요?

2024-01-21 13:29 UTC, jjongwa commented on backend/src/main/java/hanglog/admin/SecurityConfig.java
> +    }
BCrypt 말고 다른 기본 단방향 암호화 알고리즘으로는 어떤 문제가 있었나요?

2024-01-21 13:38 UTC, jjongwa reviewed
와 너무 빡세요 양이 이렇게 많을 줄은 몰랐는데
이러면 처음부터 모듈을 분리해서 구현해 놓는게 훨씬 낫지 않나 하는 생각입니다.!

우선 시큐리티 추가에 대한 부분만 조금 더 얘기 나눠보고 싶네요.

2024-01-21 14:03 UTC, LJW25 commented on backend/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security'
네 맞습니다!

2024-01-21 14:10 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/SecurityConfig.java
> +    }
다른 방법들을 예시로 들자면
- PBKDF2 (Password-Based Key Derivation Function 2) : 반복 횟수를 조절하여 성능과 보안 수준을 조절할 수 있다는 장점이 있지만,  BCrypt에 비해 GPU를 이용한 공격에 더 취약하고 설정에 따라 성능 저하가 발생할 수 있다는 단점이 있음.
- Argon2: 최신 알고리즘으로  메모리와 CPU 사용을 동시에 조절하여 더 나은 보안성 제공함. 하지만 상대적으로 새로운 알고리즘이기 때문에 다른 알고리즘보다 검증된 시간이 짧고, 자료가 적음.
- SHA-256: 널리 알려져 있고, 많이 사용되며 구현하기 쉬움. 하지만 단순한 해시 함수이기 때문에 빠른 계산 속도가 오히려 단점으로 작용함 (무차별 대입 공격에 취약).
- SCrypt: 메모리 집약적 해싱 방식을 사용하여 GPU 공격에 강함. 하지만 메모리 요구량이 높을 수 있으며, 구현이 복잡할 수 있음.

요약하자면 BCrypt가 많은 케이스를 통해 검증된 방식이고, 자료가 많아 개발 시간이 단축되며, 구현 방식 또한 단순하다는 것이 결정에 가장 크게 작용한 요인입니다!

2024-01-21 14:21 UTC, jjongwa commented on backend/src/main/java/hanglog/admin/SecurityConfig.java
> +    }
결국 BCrypt를 사용하기 위해 스프링 시큐리티를 적용한 거라면 너무 과도한 의존성 추가가 아닐까 싶네요..!
어떠한 프레임워크를 추가하는게 생각보다 꽤 복잡한 추가 설정과 에러 대응이 필요할 수도 있거든요(특히 시큐리티는 더!)

간단하게 BCypt 라이브러리만 추가하는게 어떠신지....!

https://jj-yi.tistory.com/22

2024-01-22 14:19 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/SecurityConfig.java
> +    }
[5db7c03](https://github.com/woowacourse-teams/2023-hang-log/pull/780/commits/5db7c0381c3f5466abf707bad890251b15d09c3c)

반영하였습니다! 저도 그부분이 걸렸지만 방법을 못찾았었는데, 디노 짱짱입니다. 덕분에 불필요하게 exclude 하던 서브모듈 또한 변경하였습니다. 감사합니다👍

2024-01-22 18:13 UTC, hgo641 requested changes
`빠르게 진행하려 욕심을 부리다 보니 한 PR에 너무 많은 녀석들이 들어가버렸습니다..죄송합니다..그치만 진짜 빨랐음`
-> ㅋㅋㅋ 하지만 빨랐죠?

이오좌........... 코드가 굉장히 많군요 매우 고생하셨습니다 . . .

2.3. 고민
구현하면서 고민했던 내용들입니다. 의견 환영합니다!

Controller는 Admin에, Service는 City에 구현하면서 DTO는 어느 패키지에 둬야할까?를 고민했습니다.
→ 관점의 차이인 문제라 어느쪽에 둬도 말이 되지만, Admin 패키지에 둘 경우 패키지간 상호참조가 발생할 위험이 있기 때문에 우선 이를 막기위해 city 패키지에 두었습니다.
> 좋은데요?

city 도메인 response에 담길 정보가 완전히 동일한데(타입까지) response DTO를 만들 필요가 있을까?
→ 만약에 도메인이 변경되더라도 response의 형태는 변경되지 않아야 하므로 DTO를 만들었습니다. 반대의 경우도 마찬가지!
> 좋은데요??

2024-01-22 18:13 UTC, hgo641 commented on backend/src/main/java/hanglog/admin/dto/request/AdminMemberCreateRequest.java
> +    private String password;
얘 DB랑 max 조건 다른 이유 있나요?.? 궁금

2024-01-22 18:13 UTC, hgo641 commented on backend/src/main/java/hanglog/admin/AdminLoginArgumentResolver.java
> +    }
refreshTokenRepository 일반 유저 리프레시토큰 저장용으로 만든거라, 잘하면 어드민이 아니라 일반 유저로 로그인 시도했을 때 Admin으로 로그인이 돼버릴지도?..

2024-01-22 18:13 UTC, hgo641 commented on backend/src/main/java/hanglog/admin/service/AdminLoginService.java
> +            refreshTokenRepository.save(savedRefreshToken);
일반 유저의 id와 어드민 유저의 id가 같으면 refreshTokenRepository에서 서로 덮어씌워버릴수도 있겠군요!! 레파지토리 분리하면 좋을 것 같아요

2024-01-23 04:39 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/domain/AdminMember.java
> +@SQLDelete(sql = "UPDATE admin_member SET status = 'DELETED' WHERE id = ?")
저도 고민했던 내용인데요! 사실 Soft Delete와 Hard Delete 모두 크게 차이가 나는 장단점이 없다가 결론이었습니다!

저희 시스템 규모에서 AdminUser는 진짜 많아져 봐야 100개가 안될 데이터라서, 성능적으로 비교하는건 의미가 적겠더라구요.
그래서 결국 낮은 확률이라도 대비할 수 있는 상황이 많고, 기록의 의미도 담을 수 있도록 Soft Delete로 구현하였습니다.

2024-01-23 04:43 UTC, LJW25 commented on backend/src/main/java/hanglog/category/service/CategoryService.java
>  }
이름은 변경하지 않은 경우에는 무조건 DB에 이미 존재하니까 무조건 예외가 던져질 수 밖에 없어서 변경이 된게 맞는지 검증을 추가해주었습니다!
그런데 다시 생각해보니까 category 특성상 이름이 안바뀌면 그냥 update 자체를 할 필요가 없는것 같기도 하고..?
id 추가하면서 한번더 고민해보겠습니다

2024-01-23 04:44 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/AdminLoginArgumentResolver.java
> +    }
배포시에 일반 행록과 admin 행록의 도메인이 다를 것이기 때문에 캐시도 따로 저장되서, 해당 문제는 발생하지 않습니다!

2024-01-23 04:49 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/service/AdminLoginService.java
> +            refreshTokenRepository.save(savedRefreshToken);
현재 RefreshToken 레포의 키가 RefreshToken, 값이 id여서 RefreshToken이 겹치지 않으면 해당 문제는 발생하지 않습니다. (JwtProvider.java의 44~61줄 참고)
만약 시간이 완벽히 동일하게 겹친다면 RefreshToken이 겹칠 수도 있는데, 이는 어드민과 일반 사용자간이 아니라 모든 사용자간에 발생할 수 있는 문제입니다. 이를 UUID를 주입하는 방식으로 해결할 수 있을 것으로 보이는데, 해당 PR에서 포함할 범위가 아니라고 생각되어 구현하지 않았습니다!

2024-01-23 09:15 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        return currencyRepository.save(Currency.of(currencyRequest)).getId();
근데 애초에 환율 api 스케줄링 로직에서 jpy * 100하고 DB에 저장하는 게 나았겠네 
왜 그 땐 생각을 못했을까 . . . 헷

2024-01-23 09:19 UTC, hgo641 commented on backend/src/main/java/hanglog/admin/service/AdminLoginService.java
> +            refreshTokenRepository.save(savedRefreshToken);
아 아아 완전 refreshToken value값으로 구분되는구나 이해했습니다

2024-01-23 09:21 UTC, hgo641 commented on backend/src/main/java/hanglog/admin/AdminLoginArgumentResolver.java
> +    }
도메인 다르면 같은 레디스 사용해도 캐시 따로 저장돼요?! 진짜 몰랐음

2024-01-23 12:39 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/AdminLoginArgumentResolver.java
> +    }
앗 아니 레디스에는 똑같이 적용 되는데, 브라우저에서 캐시가 다르게 저장되기 때문에 hanglog.com에 관리자 페이지 캐시로 접근할 수 는 없다는 의미였습니다!

2024-01-23 14:13 UTC, LJW25 commented on backend/src/main/java/hanglog/category/service/CategoryService.java
> +    }
정말 큰걸 놓치고있었군요.. Mock 테스트의 헛점을 이렇게 마주하다니..흑흑
큰 사고를 막았습니다 감사합니다..

해당 부분 ID 추가하고, 생성 및 수정시 ID 중복여부 검사 추가, 
전반적으로 (관리자 로그인, 기본데이터 CRU)에 대한 통합테스트 추가하였습니다!

2024-01-23 14:20 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/AdminLoginArgumentResolver.java
> +        if (adminMemberRepository.existsAdminMemberByIdAndAdminType(memberId, AdminType.MASTER)) {
어차피 Master가 AdminType 밖에 없긴 해서 static import로 변경!

2024-01-23 14:21 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/domain/repository/AdminMemberRepository.java
> +    Boolean existsAdminMemberByUserName(String userName);
[ca62ca7](https://github.com/woowacourse-teams/2023-hang-log/pull/780/commits/ca62ca72cfc38d1279d64c9ecc2b4b2c25fe1457) 반영완!

2024-01-23 14:31 UTC, LJW25 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        return currencyRepository.save(Currency.of(currencyRequest)).getId();
이부분은 서비스적인 부분이라 더 논의가 필요할것같아요!

일단 100배 크게 넘어오기 때문에 1비율로 하려면 100을 나눠야 하긴 한데,
현재 100배 크게 넘어오는 정보가 다른 환율 들과 통일되게 소수점 아래 두자리까지거든요. 아마 이것 때문에 한국 수출입은행 API에서 100배로 넘겨주는 것 같아요.
그래서 고민해야 할 부분은 1비율로 해서 100배 나누는 것이 진짜 가독성이 좋은가?! 입니다.

사실 저는 JPY(100) 으로 두고 다른 애들이랑 비슷한 크기로 두는게 덜 헷갈린다 주의입니다. 
저희가 스케줄링 해 놓은 코드로 자동으로 들어간게 아니라, 추가로 입력을 하는 상황을 가정해도 10개의 통화를 하나하나 검색하기 보다는 10개를 한번에 조회할 수 있는 다른 은행의 데이터를 가져오지 않을까 싶어요. 이 경우 다른 은행도 일본 엔화는 100배로 데이터를 보여줍니다. (ex, [하나은행 환율 API](https://www.hanafnapimarket.com/#/apis/guide?apiId=hbk00004)) 그래서 정보를 가져오기도 보기도 엔화는 100배로 해놓는게 통상적이다! 라는 의견!

근데 이건 진짜 선호의 차이인것 같아서 다른분들 의견도 궁금해요. 😄

2024-01-23 14:35 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/dto/response/AdminMemberResponse.java
> +    private final String userName;
반영 완!

2024-01-23 14:47 UTC, hgo641 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +        return currencyRepository.save(Currency.of(currencyRequest)).getId();
소수점 통일성을 위해 100배를 해주는 거였군요. 
저는 그럼 처음 말했던 대로 UI에서는 실제 엔화의 환율을 넘겨 받고, 저장할 때 저희가 임의로 100배하는 게 좋을 것 같네요!

2024-01-23 15:08 UTC, mcodnjs reviewed
안녕하세요, 지우씨
리뷰가 조금 늦었습니다 제송합니다 😂
일단 이걸 이렇게 빨리 구현했다는 것에 매우 놀랐습니다. 야무지네요 
테스트는 못봄 다음 리뷰 때 다시 볼게요 .. ㅠㅠ 
별거없고 저도 변수명이랑 검증 로직, 재사용 가능한 거들 위주로 리뷰 남겼어요! 
고생하셨습니다 ~~!!~~~!!~

2024-01-23 15:08 UTC, mcodnjs commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    private Long getLastPageIndex(final int pageSize) {
오

2024-01-23 15:08 UTC, mcodnjs commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    private void validateDateDuplicate(final Currency currency, final LocalDate newDate) {
`validateDuplicatedDate` 어떠신지 .. ㅎㅎ 여기도 currency.getDate()를 넘겨주면 좋을거 같아요!

2024-01-23 15:16 UTC, hgo641 commented on backend/src/main/java/hanglog/category/service/CategoryService.java
> +    }
매의 눈 라온ㄷㄷ 영어이름만 중복체크해야겠는데요?

2024-01-24 04:47 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/presentation/AdminCurrencyController.java
> +    public ResponseEntity<Void> updateCategory(
사실 한국수출입은행에서 오류나지 않는 이상 없긴 하지만? 일단 만드는김에 샥 만들었슴다!
오타ㅎ 수정완

2024-01-24 04:49 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/service/AdminLoginService.java
> +                .orElseThrow(() -> new AdminException(INVALID_USER_NAME));
으아아 이놈의 자동정렬 수정 완!

2024-01-24 04:51 UTC, LJW25 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    private Long getLastPageIndex(final int pageSize) {
아?

2024-01-24 05:38 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/domain/AdminMember.java
> +    public AdminMember(final Long id, final String userName, final String password, final AdminType adminType) {
오 그러네요?!?! 근데 Member는 createdAt 어떻게 유지되고 있는거죠..?!

2024-01-24 06:10 UTC, LJW25 commented on backend/src/main/java/hanglog/category/service/CategoryService.java
> +    }
[114cd24](https://github.com/woowacourse-teams/2023-hang-log/pull/780/commits/114cd242c96be39f8f674c6f026b48bedaa2c28d) 한글, 영어 이름 모두 각각 검증하도록 수정하였습니다!

2024-01-24 06:10 UTC, LJW25 commented on backend/src/main/java/hanglog/category/service/CategoryService.java
> +        if (!category.isSameNames(categoryRequest.getEngName(), categoryRequest.getKorName())) {
[114cd24](https://github.com/woowacourse-teams/2023-hang-log/pull/780/commits/114cd242c96be39f8f674c6f026b48bedaa2c28d)

2024-01-24 06:10 UTC, LJW25 commented on backend/src/main/java/hanglog/category/service/CategoryService.java
> +        validateCategoryDuplicateName(categoryRequest);
[114cd24](https://github.com/woowacourse-teams/2023-hang-log/pull/780/commits/114cd242c96be39f8f674c6f026b48bedaa2c28d)

두단계로 나누어 검증하도록 변경!

2024-01-24 06:11 UTC, LJW25 commented on backend/src/main/java/hanglog/currency/service/CurrencyService.java
> +    private void validateDateDuplicate(final Currency currency, final LocalDate newDate) {
[8a374bb](https://github.com/woowacourse-teams/2023-hang-log/pull/780/commits/8a374bb09b374acfe3b78386b64394e78d8f38f6) 수정 완!

2024-01-25 15:12 UTC, jjongwa commented on backend/src/main/java/hanglog/admin/dto/response/AdminMemberResponse.java
> +    private final String userName;
'userName'

2024-01-25 15:16 UTC, jjongwa approved these changes
정말 든 든하네요
잠깐 안본것 같은데 comment가 71개나 달려서 놀랐습니다.
얼른 머지하고 릴리즈까지 샤샤샥 가시죠

2024-01-29 07:50 UTC, waterricecake approved these changes
고생하셨습니다! 이오! 제가 저번주 조금 바빠서 늦게 봤네요;;;

2024-01-29 07:50 UTC, waterricecake commented on backend/src/main/java/hanglog/admin/domain/type/AdminType.java
> +    ADMIN, MASTER;
저희 이넘 첫 줄 개행 한것도 있고 안한것도 있던데 이것도 클래스니까 개행합니까? (`trip`패키지의 이넘들은 개행되어 있는데 `auth`는 안되어있음)
```suggestion
public enum AdminType {

    ADMIN, 
    MASTER;
```

2024-01-29 07:50 UTC, waterricecake commented on backend/src/main/java/hanglog/auth/domain/Accessor.java
> +        return new Accessor(memberId, Authority.MASTER);
이부분 static import에서 바꾸신 이유가 있나요? (진짜 궁금해서 제가 또 놓쳤나해서)

2024-01-30 04:31 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/service/AdminLoginService.java
> +    public String renewalAccessToken(final String refreshTokenRequest, final String authorizationHeader) {
해당 내용은 슬랙+미팅에서 이야기했던 대로..!

2024-01-30 04:54 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/domain/type/AdminType.java
> +    ADMIN, MASTER;
일단 AdminType은 Auth랑 같은 방식을 따르는게 맞는것 같아서 개행을 안했었는데, Trip까지 전부 보니까 Auth가 잘못되있었던것도 같구요..? 둘 모두 개행 하는 쪽으로 수정하였습니다.

2024-01-30 04:57 UTC, LJW25 commented on backend/src/main/java/hanglog/auth/domain/Accessor.java
> +        return new Accessor(memberId, Authority.MASTER);
이게 Authroity로의 ADMIN, MASTER가 있고 AdminType으로서의 ADMIN, MASTER가 있어서 명시해주었습니다.
Authority의 ADMIN, MASTER는 인증/인가에만 사용되고 나머지 부분에서 ADMIN, MASTER는 AdminType이 사용되는 구조에요!

2024-01-30 04:58 UTC, LJW25 commented on backend/src/main/java/hanglog/admin/AdminLoginArgumentResolver.java
> +    }
검증 시 Admin, master id 인지 검증 하는 로직 추가했습니다!

2024-01-31 12:37 UTC, hgo641 approved these changes
볼륨이 어마어마하게 크군요! 고생하셨습니다 리더 이오...

2024-02-03 16:38 UTC, LJW25 commented
최종 변경 사항
- 카테고리 추가 및 수정 시 한글명 검증 삭제 (한글명은 중복될 수 있음.)
- 환율 추가 및 수정 시 krw 삭제 (항상 1이라 불필요함.)
- 컨플릭트 해결을 위한 merge!

2024-02-03 16:39 UTC, merged