관리자 페이지 구현 - 관리자멤버, 카테고리, 환율 관리 페이지 구현
woowacourse-teams/2023-hang-log pull request #790
Opened 2024-02-03 16:08 UTC by LJW25

## 📄 Summary
> 관리자 멤버 관리 페이지, 카테고리 관리 페이지, 환율 관리 페이지와 각 페이지별 추가 & 수정 모달 구현

## 🙋🏻 More
> 다음은 인증/인가 🙃

### - 관리자 멤버 관리 페이지 (/admin/member) 
<img width="1128" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/bfa77077-4e66-446e-8ea1-7205e2c46ae6">

### - 관리자 추가 모달
<img width="507" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/0e7f99d5-06ed-4b06-b95d-89be925d89fd">

### - 관리자 비밀번호 수정 모달
<img width="463" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/cc9aa57a-8df1-4536-8bc0-d7e692b19dea">

---

### - 카테고리 관리 페이지 (/admin/category)
<img width="1126" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/41afa6fd-55f7-48ae-bded-46f15ec0685c">

### - 카테고리 추가 및 수정 모달
<img width="552" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/a50dea04-595a-41e5-bb23-f5b2dd258eb0">

<img width="480" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/7ffd143a-70ef-481e-8ff1-140075d23d2b">

---

### - 환율 관리 페이지 (/admin/category)
<img width="1123" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/767777bb-2a1f-41f2-9002-254f0f7ba78a">

### 환율 추가 및 수정 모달
<img width="738" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/0f49cbe7-c486-4289-8d2d-d580a4f920ae">
<img width="747" alt="image" src="https://github.com/woowacourse-teams/2023-hang-log/assets/49433615/e5e68d33-56d2-4997-af57-dbcbf5a29adc">

2024-02-03 16:17 UTC, ashleysyheo commented
😮🙌👍

2024-02-04 06:26 UTC, dladncks1217 requested changes
**"프론트엔드"** 가 되어버린 리더 이오의 코드 잘 봤습니다

사실 file changes가 86개라서 빠르게 훑는 느낌으로 보긴 했는데, 전체적으로 import관련한 부분을 수정해야 할 게 많이 보이더라구요!
alias 적용했으니 이왕이면 쓰는게 좋겠죠!?
`'@/constants/api'`같은 경로들은 tsconfig 확인해보고 '@constants/api'처럼 수정하는게 좋을 것 같아요.
근데 생각해보면 vite.config.js파일에서도 추가해줘야하려나??
근데 제대로 적용되어있는것들 잘 돌아가는거보면 문제 없어보이기도 하고...
제가 프로젝트 세팅한게 아니다보니 좀 더 봐야 알겠네요 ㅋㅋㅋ

그나저나 이제와서 co-location으로 구조 변경하기에는 좀 늦었겠죠?
리뷰하려는데 파일이 여기저기 막 돌아다니다보니 읽기가 쉽지 않군요😅

일단 request changes 보내둘테니 코멘트 남긴것들이랑 경로 관련한 것들만 확인해주시죠 크크

멋집니다멋집니다👍👍

2024-02-04 06:26 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/components/adminMember/PasswordUpdateModal/PasswordUpdateModal.tsx
> +  } = UseUpdatePasswordForm({ adminMemberId: adminMemberId, onSuccess: onClose });
`useUpdatePasswordForm`으로 바꾸는거 어떤가여 훅인데 앞자리 대문자 좀 이상하네요
마치 `UseState` 같은느낌

2024-02-04 06:26 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/adminMember/useUpdatePasswordForm.ts
> +  const UpdatePasswordMutaion = useUpdateAdminMemberPasswordMutation();
밑에서는 `updateInputValue`같이 썼는데 여긴 대문자인 이유가 있나요!?

2024-02-04 06:26 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/category/useAddCategoryForm.ts
> +  const updateInputValue = useCallback(
`updateInputValue`가 여기저기 퍼져있군요?
뭔가 하고 보니, 기존에 있던 데이터중 일부만 수정하는 코드 같더라구요. 도메인에따라 네이밍을 조금 수정하는게 어떨까요?
디렉토리 구조가 co-location이 아닌데 PR 하나에 `updateInputValue`가 86번 등장해서, 파일 여기저기 돌면서 코드 확인하는데 흐름쫒기가 쉽지 않더라구요🥲

2024-02-04 06:26 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/currency/useAddCurrencyForm.ts
> +  //   };
주석이 남아있어용

2024-02-04 06:26 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/currency/useAddCurrencyForm.ts
> +    // }
여기도여

2024-02-04 06:26 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/pages/AdminMemberPage/AdminMemberPage.style.ts
> +};
꼭 함수여야 할 이유도 없는 것 같기도 하고...
함수로 다 통일하려고 쓰는거라면 return문이 필요할까 싶기도 하구요??
`()=>css({ ~~~` 와 같이 사용할 수 있어요!

2024-02-04 10:14 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/components/adminMember/PasswordUpdateModal/PasswordUpdateModal.tsx
> +  } = UseUpdatePasswordForm({ adminMemberId: adminMemberId, onSuccess: onClose });
일반적으로 js에서 함수명은 camelCase를 사용해요
타입, 클래스, 컴포넌트는 PascalCase

2024-02-04 10:31 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/hooks/adminMember/useAddAdminMemberForm.ts
> +  const [isConfirmPasswordError, setIsConfirmPasswordError] = useState(false);
각 에러에 대해 개별적으로 상태를 정의하는 대신, 위에 adminMemberInformation처럼 객체로 선언해도 괜찮을 것 같아요!

2024-02-04 10:31 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/hooks/adminMember/useAddAdminMemberForm.ts
> +
위 코멘트처럼 에러를 객체로 관리한다면 에러 관련 처리 함수도 추상화 할 수 있을 것 같아여 
`updateInputValue` 함수처럼요!

2024-02-04 10:31 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/hooks/adminMember/useAddAdminMemberForm.ts
> +      },
```suggestion
      {
        ...adminMemberInformation
      },
```

2024-02-04 10:31 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/hooks/api/useAdminMemberQuery.ts
> +    gcTime: 24 * 60 * 60 * 60 * 1000,
gcTime을 추가한 이유는 뭔가요??

2024-02-04 10:31 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/hooks/category/useAddCategoryForm.ts
> +  const updateInputValue = useCallback(
co-location으로 구조 변경하는 것도 나쁘지 않을 것 같아요! 
공통적으로 사용되는 hook은 최상위로 빼고 관련된 것들은 ex. city 폴더 내부에 둔다.

2024-02-04 10:31 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/pages/AdminMemberPage/AdminMemberPageSkeleton.tsx
> +};
여기서 `관리자 멤버 관리`, `추가하기` 코드 같은 경우에는 `AdminMemberPage`에 있는 코드를 그대로 가져오고 있는데, 이렇게 반복 하는 대신 `Suspense`를 감싸는 범위를 좁혀봐도 좋을 것 같아요!

```
<Suspense fallback={<FallbackComponent />}>
  <section css={tableStyling}>
    <AdminMemberTable adminMembers={currentPageData} />
  </section>
  <PageNavigation
    pages={pageIndexDatas}
    selected={page}
    maxPage={lastPageIndex}
    onChangeNavigate={handleSetPage}
  />
</Suspense>
```

2024-02-04 10:31 UTC, ashleysyheo commented on frontend-monorepo/packages/hanglog-admin/src/utils/validator.ts
> +};
여기 숫자들이 뭐를 의미하는지 잘 모르겠어요 상수화 해두면 좋을 것 같아여!

2024-02-04 15:04 UTC, jjongwa commented
풀스택 개발자 이오의 도전을 응원합니다

2024-02-05 08:00 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/currency/useAddCurrencyForm.ts
> +  //   };
으어억 이스터에그 발견! 당첨되셨습니다!

2024-02-10 12:14 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/api/adminMember/patchAdminMember.ts
> +import { END_POINTS } from '@/constants/api';
[@trivago/prettier-plugin-sort-imports](https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports) 라이브러리로 자동정렬 적용했습니다. 이게 그냥 알아서 적용되는게 아니더군요? 
> **Note: There may be an issue with some package managers, such as pnpm. You can solve it by providing additional configuration option in prettier config file.

공식문서에서 이렇다는데 하라는대로 따라하니까 자동정렬 따라란 성공! 순서는 노션 참고했슴다

2024-02-10 15:33 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/pages/AdminMemberPage/AdminMemberPage.style.ts
> +};
[ed14a01](https://github.com/woowacourse-teams/2023-hang-log/pull/790/commits/ed14a01a5dfd6c67fd671cd5a5fed4c827582123)

파라미터 필요없는 것들은 일반 변수로 수정했습니다!

2024-02-10 15:34 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/pages/AdminMemberPage/AdminMemberPageSkeleton.tsx
> +};
[ebb0bb3](https://github.com/woowacourse-teams/2023-hang-log/pull/790/commits/ebb0bb36a8c3f751e189d32f66992ccf0b0b6096)
애슐리 말대로 고치니까 *pageSkeleton 자체가 필요없더라구요! 싹 수정했습니다 👍

2024-02-10 15:36 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/adminMember/useUpdatePasswordForm.ts
> +  const UpdatePasswordMutaion = useUpdateAdminMemberPasswordMutation();
이것또한 저의 실수..수정했습니다!

2024-02-10 15:39 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/category/useAddCategoryForm.ts
> +  const updateInputValue = useCallback(
확실히 저도 개발하면서 co-location 구조를 썼으면 더 편했겠다는 생각이 많이 들었던것 같아요! 처음이라 기존 행록 구조를 따라하면서 익숙해지려 했는데, 이제 구조를 좀 익혔으니 더 늦기전에 구조를 바꿔볼까 합니다.
이번 PR에서 바꾸면 여차했을 때 롤백이 어려울것같아 기능상 문제가 없는 상태에서 머지하고 바로 새 PR파서 co-location 구조로 변경해보려는데 어떨까요?!

2024-02-10 15:52 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/utils/validator.ts
> +};
[0c5be44](https://github.com/woowacourse-teams/2023-hang-log/pull/790/commits/0c5be443cbc3b8447cf8229c7c4e3c997513f2b4)

상수화 완! 사실 대부분 이미 상수로 선언은 해놓고 validator에만 적용을 안해놨더라구요..? 수정했습니다..ㅎㅎ

2024-02-14 14:29 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/category/useAddCategoryForm.ts
> +  const updateInputValue = useCallback(
너무좋은데요!?

2024-02-14 14:30 UTC, dladncks1217 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/currency/useAddCurrencyForm.ts
> +  //   };
오 좋은데요??

2024-02-15 06:56 UTC, dladncks1217 approved these changes

2024-02-23 12:04 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/adminMember/useAddAdminMemberForm.ts
> +  const [isConfirmPasswordError, setIsConfirmPasswordError] = useState(false);
[15a47cf](https://github.com/woowacourse-teams/2023-hang-log/pull/790/commits/15a47cffb37d23b1b556c4e3cb636437a2ba7487)

전체적으로 반영 완! 좋은 의견 감사합니당

2024-02-23 12:10 UTC, LJW25 commented on frontend-monorepo/packages/hanglog-admin/src/hooks/api/useAdminMemberQuery.ts
> +    gcTime: 24 * 60 * 60 * 60 * 1000,
gcTime이 캐시가 삭제되지 않게 유지하는 시간으로 알고있는데 맞을까요?!
관리자 데이터의 경우 수정이 빈번하게 일어나는 데이터는 아니라고 생각해서 넣었습니다!

2024-02-23 12:10 UTC, merged