Feature/#52
woowacourse-teams/2023-hang-log pull request #99
Opened 2023-07-19 08:30 UTC by ashleysyheo

## 📄 Summary

<img width="1512" alt="Trip Item Add Modal - non spot-1" src="https://github.com/woowacourse-teams/2023-hang-log/assets/51967731/c4dbcbc3-5946-4851-a745-f06138aba3ce">

<br>

TripItem 추가 모달 일부 구현

<br>

- [x] 카테고리, 날짜, 제목을 필수로 입력해야 한다. 
  - [x] 날짜는 모달 생성을 클릭한 탭의 날짜가 디폴트로 설정된다.
  - [ ] 카테고리 `장소` 선택 시 제목은 구글 map api를 사용해서 검색 결과 확인 및 자동완성을 할 수 있다. 
  - [x] 카테코리 `기타` 선택 시 제목은 사용자가 입력한 값이 된다. 
- [ ] 옵셔널로는 별점, 비용 (카테고리, 통화, 금액), 메모, 사진을 입력할 수 있다. 
  - [x] 비용 카테고리 디폴트는 `음식`, 통화 디폴트는 `₩(원)`이다. 
- [ ] 사진은 최대 5장 업로드할 수 있다. 
- [ ] 일정 추가/수정 성공 시 성공했다는 토스트 메세지를 볼 수 있다. 

## 🙋🏻 More
TripItem 추가 모달 일부 구현했습니다! 

위에서 체크 안 된 부분들은 코드량이 많아질 것 같아서 새로 이슈 파서 작업하겠습니다. 

현재 `기타` 카테고리에 대해서만 입력 추가할 수 있습니다. 
제목이 입력되지 않은 경우에는 에러 메세지가 뜹니다. 추가하면 Day 1 목록 밑에 추가되는 것을 볼 수 있습니다.

2023-07-19 10:49 UTC, Dahyeeee requested changes
아주 복잡하고 어려운 로직을 애슐리가 다 맡아서 해주셨군요~~ 
수고 아주 많으셨어요!! 감사합니당 :)

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemDateInput/TripItemDateInput.tsx
> +        {Array.from({ length: dates.length - 1 }, (_, index) => (
이거 length 만큼 만들어야하지 않나요? 아닌가?!

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemDateInput/TripItemDateInput.tsx
> +        {!currentCategory && (
카테고리가 '장소'일 때도 '기타'탭에 장소 입력할 수 있어도 괜찮지 않을까요? 
논의했던 거 같은데 '장소' 입력도 가능했던 거 같아요 ..?

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/hooks/useAddTripItemForm.ts
> +import { FormEvent, useCallback, useState } from 'react';
type 분리해주세용~

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/hooks/useAddTripItemForm.ts
> +import { useAddTripItemMutation } from './api/useAddTripItemMutation';
경로!

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/hooks/useAddTripItemForm.ts
> +    memo: null,
저는 initialData 컴포넌트 상단에서 뒀는데 혹쉬 분리하는게 어떠신가요?

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/pages/TripEditPage/TripEditPage.tsx
> +  const { selected, handleSelectClick } = useSelect(tripData.dayLogs[0].id);
이친구들 rename으로 무슨 open인고 무슨 select인지 알려주실 수 있나요~

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
> +  const [_, setExpenseValue] = useState<TripItemFormType['expense']>(
이 친구들(setExpenseValue로 값바꾸는 친구들 로직) 훅으로 분리하는 거는 어때요?

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemCategoryInput/TripItemCategoryInput.tsx
> +  updateInputValue: <K extends keyof TripItemFormType>(key: K, value: TripItemFormType[K]) => void;
Generic 넘 멋있음

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemTitleInput/TripItemTitleInput.tsx
막상 이렇게 보니 소제목을 꼭 써야하는지 의문이 드는군요..! 귀찮을 거 같을지도..
회의때 함 논의해보시죠

2023-07-19 10:49 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
> +              {name}
그 KRW같은 정보도 같이 보여주면 좋을 것 같아여
저는 아이콘만으로 화폐정보 모르거든요..호헤헤

2023-07-19 12:00 UTC, dladncks1217 commented on frontend/src/components/trip/TripItemAddModal/TripItemAddModal.tsx
> +            {/* TODO : 이미지 업로드 관련 로직 처리 필요함 */}
👍

2023-07-19 12:02 UTC, dladncks1217 commented on frontend/src/hooks/api/useExpenseCategoryQuery.ts
> +import { ExpenseCategoryData } from '@/types/expense';
절대경로!

2023-07-19 12:02 UTC, dladncks1217 commented on frontend/src/hooks/api/useExpenseCategoryQuery.ts
> +import { ExpenseCategoryData } from '@/types/expense';
타입임포트도 빠진 것 같아요!

2023-07-19 12:04 UTC, dladncks1217 commented on frontend/src/utils/formatter.ts
> +export const formatNumberToMoney = (number: number) => {
number:number로 바꾼 이유가 있나요?!

2023-07-19 12:05 UTC, dladncks1217 commented on frontend/src/hooks/api/useAddTripItemMutation.ts
> +export const useAddTripItemMutation = (onSuccess?: CallableFunction) => {
여기도 `CallableFunction`을 쓴 이유가 궁금해요!

2023-07-19 12:05 UTC, dladncks1217 commented on frontend/src/hooks/useAddTripItemForm.ts
> +  onSuccess?: CallableFunction
여기도 `CallableFunction`을 쓴 이유가 궁금해요!

2023-07-19 12:59 UTC, ashleysyheo commented on frontend/src/components/trip/TripItemAddModal/TripItemDateInput/TripItemDateInput.tsx
> +        {Array.from({ length: dates.length - 1 }, (_, index) => (
기타 날짜도 마지막 날짜 + 1로 들어온데요! 그래서 마지막 날짜 + 1, 즉, 기타인 날은 `기타`로 표기하기 위해서 여기서 `- 1`한 다음에 하단에서 조건부 렌더링을 하도록 했습니다.

2023-07-19 13:02 UTC, ashleysyheo commented on frontend/src/components/trip/TripItemAddModal/TripItemTitleInput/TripItemTitleInput.tsx
흠... 장소 입력할 때 필요한 인풋 창이어서 있어야하긴 한데....🤔

2023-07-19 13:02 UTC, ashleysyheo commented on frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
> +              {name}
이거 저도 고민이 많았습니다 ㅎㅎㅎㅎㅎㅎㅎ 그런데 그럼 셀렉트 박스가 너무 커져서 어떻게 해야 할지 모르겠어요 🥲 어떻게 하죠?!

2023-07-19 13:03 UTC, ashleysyheo commented on frontend/src/api/tripItem/postTripItem.ts
> +import { END_POINTS } from '@/constants/api';
😳 vs code.....

2023-07-19 13:05 UTC, ashleysyheo commented on frontend/src/utils/formatter.ts
> +export const formatNumberToMoney = (number: number) => {
정확히 말하면 숫자를 돈으로 변환하는 거니까요?? 그래서 인자 이름이 money인게 조금 어색하게 느껴져서요!

2023-07-19 13:06 UTC, ashleysyheo commented on frontend/src/hooks/api/useAddTripItemMutation.ts
> +export const useAddTripItemMutation = (onSuccess?: CallableFunction) => {
onSuccess가 정확히 어떤 형태일지 모르니까요?? 그런데 이 상황에서는 `() => void`만 들어올 것 같네요!

2023-07-19 13:07 UTC, ashleysyheo commented on frontend/src/hooks/useAddTripItemForm.ts
> +  onSuccess?: CallableFunction
위와 같은 이유입니다!

2023-07-19 13:15 UTC, ashleysyheo commented on frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
> +      currency: 'KRW',
음 그런데 그건 키 값이네요.....

2023-07-19 13:30 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemTitleInput/TripItemTitleInput.tsx
아! 아이템 제목이군요~~ 저는 데이로그 소제목을 말한거였습니당! 죄송

2023-07-19 13:31 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemDateInput/TripItemDateInput.tsx
> +        {!currentCategory && (
ㅋㅋㅋㅋㅋㅋ그렇군요 기억이 희미합니다~~

2023-07-19 13:32 UTC, Dahyeeee commented on frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
> +              {name}
오호 고민해보겠습니다~ 논의도 해보죠~

2023-07-20 00:55 UTC, ashleysyheo commented on frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
> +  const [_, setExpenseValue] = useState<TripItemFormType['expense']>(
분리했습니다!

2023-07-20 01:55 UTC, dladncks1217 approved these changes
고생 많으셨습니다💯💯

2023-07-20 01:55 UTC, dladncks1217 commented on frontend/src/components/trip/TripItemAddModal/TripItemExpenseInput/TripItemExpenseInput.tsx
> +              {name}
정보 같이 보여주는거 좋은데요?!

2023-07-20 02:37 UTC, Dahyeeee approved these changes

2023-07-20 03:08 UTC, merged